-- v10.0.381 · Add missing indexes for FK / createdAt / updatedAt /
-- lastSeen / lastActiveAt / deletedAt / status columns. Idempotent
-- via IF NOT EXISTS · safe to re-run.
-- Generated by scripts/emit-index-migration.ts from schema.prisma.

-- ── Mission (4 indexes) ──
CREATE INDEX IF NOT EXISTS "Mission_status_priority_deadline_idx" ON "Mission" ("status", "priority", "deadline");
CREATE INDEX IF NOT EXISTS "Mission_deletedAt_idx" ON "Mission" ("deleted_at");
CREATE INDEX IF NOT EXISTS "Mission_createdAt_idx" ON "Mission" ("createdAt");
CREATE INDEX IF NOT EXISTS "Mission_updatedAt_idx" ON "Mission" ("updatedAt");

-- ── Task (8 indexes) ──
CREATE INDEX IF NOT EXISTS "Task_missionId_status_dueDate_idx" ON "Task" ("missionId", "status", "dueDate");
CREATE INDEX IF NOT EXISTS "Task_autoPriority_lastTouchedAt_idx" ON "Task" ("autoPriority", "lastTouchedAt");
CREATE INDEX IF NOT EXISTS "Task_loopKind_status_idx" ON "Task" ("loopKind", "status");
CREATE INDEX IF NOT EXISTS "Task_goalId_status_idx" ON "Task" ("goalId", "status");
CREATE INDEX IF NOT EXISTS "Task_deletedAt_idx" ON "Task" ("deleted_at");
CREATE INDEX IF NOT EXISTS "Task_createdAt_idx" ON "Task" ("createdAt");
CREATE INDEX IF NOT EXISTS "Task_updatedAt_idx" ON "Task" ("updatedAt");
CREATE INDEX IF NOT EXISTS "Task_status_idx" ON "Task" ("status");

-- ── TaskEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "task_events_taskId_createdAt_idx" ON "task_events" ("taskId", "created_at");
CREATE INDEX IF NOT EXISTS "task_events_kind_createdAt_idx" ON "task_events" ("kind", "created_at");
CREATE INDEX IF NOT EXISTS "task_events_createdAt_idx" ON "task_events" ("created_at");

-- ── EntityAudit (4 indexes) ──
CREATE INDEX IF NOT EXISTS "entity_audits_entityType_entityId_createdAt_idx" ON "entity_audits" ("entity_type", "entity_id", "created_at");
CREATE INDEX IF NOT EXISTS "entity_audits_actor_createdAt_idx" ON "entity_audits" ("actor", "created_at");
CREATE INDEX IF NOT EXISTS "entity_audits_action_createdAt_idx" ON "entity_audits" ("action", "created_at");
CREATE INDEX IF NOT EXISTS "entity_audits_createdAt_idx" ON "entity_audits" ("created_at");

-- ── PersonalDailyLog (3 indexes) ──
CREATE INDEX IF NOT EXISTS "PersonalDailyLog_logDate_idx" ON "PersonalDailyLog" ("logDate");
CREATE INDEX IF NOT EXISTS "PersonalDailyLog_createdAt_idx" ON "PersonalDailyLog" ("createdAt");
CREATE INDEX IF NOT EXISTS "PersonalDailyLog_updatedAt_idx" ON "PersonalDailyLog" ("updatedAt");

-- ── OperatorCheckIn (3 indexes) ──
CREATE INDEX IF NOT EXISTS "OperatorCheckIn_checkInDate_empireLane_idx" ON "OperatorCheckIn" ("checkInDate", "empireLane");
CREATE INDEX IF NOT EXISTS "OperatorCheckIn_createdAt_idx" ON "OperatorCheckIn" ("createdAt");
CREATE INDEX IF NOT EXISTS "OperatorCheckIn_updatedAt_idx" ON "OperatorCheckIn" ("updatedAt");

-- ── DailyExecutionState (4 indexes) ──
CREATE INDEX IF NOT EXISTS "DailyExecutionState_stateDate_dayState_idx" ON "DailyExecutionState" ("stateDate", "dayState");
CREATE INDEX IF NOT EXISTS "DailyExecutionState_activeEmpireLane_dayState_idx" ON "DailyExecutionState" ("activeEmpireLane", "dayState");
CREATE INDEX IF NOT EXISTS "DailyExecutionState_createdAt_idx" ON "DailyExecutionState" ("createdAt");
CREATE INDEX IF NOT EXISTS "DailyExecutionState_updatedAt_idx" ON "DailyExecutionState" ("updatedAt");

-- ── CommandResolution (3 indexes) ──
CREATE INDEX IF NOT EXISTS "CommandResolution_dailyExecutionStateId_createdAt_idx" ON "CommandResolution" ("dailyExecutionStateId", "createdAt");
CREATE INDEX IF NOT EXISTS "CommandResolution_resolutionType_createdAt_idx" ON "CommandResolution" ("resolutionType", "createdAt");
CREATE INDEX IF NOT EXISTS "CommandResolution_createdAt_idx" ON "CommandResolution" ("createdAt");

-- ── DailyEmpireSnapshot (3 indexes) ──
CREATE INDEX IF NOT EXISTS "DailyEmpireSnapshot_snapshotDate_idx" ON "DailyEmpireSnapshot" ("snapshotDate");
CREATE INDEX IF NOT EXISTS "DailyEmpireSnapshot_createdAt_idx" ON "DailyEmpireSnapshot" ("createdAt");
CREATE INDEX IF NOT EXISTS "DailyEmpireSnapshot_updatedAt_idx" ON "DailyEmpireSnapshot" ("updatedAt");

-- ── StateLog (1 indexes) ──
CREATE INDEX IF NOT EXISTS "StateLog_createdAt_idx" ON "StateLog" ("createdAt");

-- ── RunnerNode (3 indexes) ──
CREATE INDEX IF NOT EXISTS "RunnerNode_createdAt_idx" ON "RunnerNode" ("createdAt");
CREATE INDEX IF NOT EXISTS "RunnerNode_updatedAt_idx" ON "RunnerNode" ("updatedAt");
CREATE INDEX IF NOT EXISTS "RunnerNode_status_idx" ON "RunnerNode" ("status");

-- ── ServiceHealth (4 indexes) ──
CREATE INDEX IF NOT EXISTS "ServiceHealth_status_checkedAt_idx" ON "ServiceHealth" ("status", "checkedAt");
CREATE INDEX IF NOT EXISTS "ServiceHealth_runnerNodeId_idx" ON "ServiceHealth" ("runnerNodeId");
CREATE INDEX IF NOT EXISTS "ServiceHealth_createdAt_idx" ON "ServiceHealth" ("createdAt");
CREATE INDEX IF NOT EXISTS "ServiceHealth_updatedAt_idx" ON "ServiceHealth" ("updatedAt");

-- ── SystemSnapshot (2 indexes) ──
CREATE INDEX IF NOT EXISTS "SystemSnapshot_createdAt_idx" ON "SystemSnapshot" ("createdAt");
CREATE INDEX IF NOT EXISTS "SystemSnapshot_updatedAt_idx" ON "SystemSnapshot" ("updatedAt");

-- ── WorkItem (5 indexes) ──
CREATE INDEX IF NOT EXISTS "WorkItem_status_availableAt_createdAt_idx" ON "WorkItem" ("status", "availableAt", "createdAt");
CREATE INDEX IF NOT EXISTS "WorkItem_type_status_createdAt_idx" ON "WorkItem" ("type", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "WorkItem_runnerNodeId_idx" ON "WorkItem" ("runnerNodeId");
CREATE INDEX IF NOT EXISTS "WorkItem_createdAt_idx" ON "WorkItem" ("createdAt");
CREATE INDEX IF NOT EXISTS "WorkItem_updatedAt_idx" ON "WorkItem" ("updatedAt");

-- ── WorkResult (3 indexes) ──
CREATE INDEX IF NOT EXISTS "WorkResult_workItemId_idx" ON "WorkResult" ("workItemId");
CREATE INDEX IF NOT EXISTS "WorkResult_createdAt_idx" ON "WorkResult" ("createdAt");
CREATE INDEX IF NOT EXISTS "WorkResult_status_idx" ON "WorkResult" ("status");

-- ── StagedRecoveryItem (3 indexes) ──
CREATE INDEX IF NOT EXISTS "StagedRecoveryItem_source_status_priorityScore_idx" ON "StagedRecoveryItem" ("source", "status", "priorityScore");
CREATE INDEX IF NOT EXISTS "StagedRecoveryItem_updatedAt_idx" ON "StagedRecoveryItem" ("updatedAt");
CREATE INDEX IF NOT EXISTS "StagedRecoveryItem_status_idx" ON "StagedRecoveryItem" ("status");

-- ── CaptureInboxItem (5 indexes) ──
CREATE INDEX IF NOT EXISTS "CaptureInboxItem_source_kind_capturedAt_idx" ON "CaptureInboxItem" ("source", "kind", "capturedAt");
CREATE INDEX IF NOT EXISTS "CaptureInboxItem_status_capturedAt_idx" ON "CaptureInboxItem" ("status", "capturedAt");
CREATE INDEX IF NOT EXISTS "CaptureInboxItem_triageStatus_actionabilityScore_idx" ON "CaptureInboxItem" ("triageStatus", "actionabilityScore");
CREATE INDEX IF NOT EXISTS "CaptureInboxItem_createdAt_idx" ON "CaptureInboxItem" ("createdAt");
CREATE INDEX IF NOT EXISTS "CaptureInboxItem_updatedAt_idx" ON "CaptureInboxItem" ("updatedAt");

-- ── AuditEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "AuditEvent_eventType_createdAt_idx" ON "AuditEvent" ("eventType", "createdAt");
CREATE INDEX IF NOT EXISTS "AuditEvent_actor_createdAt_idx" ON "AuditEvent" ("actor", "createdAt");
CREATE INDEX IF NOT EXISTS "AuditEvent_createdAt_idx" ON "AuditEvent" ("createdAt");

-- ── OperatorProfile (2 indexes) ──
CREATE INDEX IF NOT EXISTS "OperatorProfile_createdAt_idx" ON "OperatorProfile" ("createdAt");
CREATE INDEX IF NOT EXISTS "OperatorProfile_updatedAt_idx" ON "OperatorProfile" ("updatedAt");

-- ── OperatorPreference (3 indexes) ──
CREATE INDEX IF NOT EXISTS "OperatorPreference_operatorProfileId_idx" ON "OperatorPreference" ("operatorProfileId");
CREATE INDEX IF NOT EXISTS "OperatorPreference_createdAt_idx" ON "OperatorPreference" ("createdAt");
CREATE INDEX IF NOT EXISTS "OperatorPreference_updatedAt_idx" ON "OperatorPreference" ("updatedAt");

-- ── RecoveryActionLog (2 indexes) ──
CREATE INDEX IF NOT EXISTS "RecoveryActionLog_stagedRecoveryItemId_createdAt_idx" ON "RecoveryActionLog" ("stagedRecoveryItemId", "createdAt");
CREATE INDEX IF NOT EXISTS "RecoveryActionLog_createdAt_idx" ON "RecoveryActionLog" ("createdAt");

-- ── ExecutionInsight (3 indexes) ──
CREATE INDEX IF NOT EXISTS "ExecutionInsight_insightType_createdAt_idx" ON "ExecutionInsight" ("insightType", "createdAt");
CREATE INDEX IF NOT EXISTS "ExecutionInsight_createdAt_idx" ON "ExecutionInsight" ("createdAt");
CREATE INDEX IF NOT EXISTS "ExecutionInsight_updatedAt_idx" ON "ExecutionInsight" ("updatedAt");

-- ── MasteryScore (1 indexes) ──
CREATE INDEX IF NOT EXISTS "mastery_scores_createdAt_idx" ON "mastery_scores" ("created_at");

-- ── DriftAlert (3 indexes) ──
CREATE INDEX IF NOT EXISTS "drift_alerts_resolved_date_idx" ON "drift_alerts" ("resolved", "date");
CREATE INDEX IF NOT EXISTS "drift_alerts_date_ruleId_idx" ON "drift_alerts" ("date", "rule_id");
CREATE INDEX IF NOT EXISTS "drift_alerts_createdAt_idx" ON "drift_alerts" ("created_at");

-- ── MasteryDecision (6 indexes) ──
CREATE INDEX IF NOT EXISTS "mastery_decisions_date_idx" ON "mastery_decisions" ("date");
CREATE INDEX IF NOT EXISTS "mastery_decisions_domain_date_idx" ON "mastery_decisions" ("domain", "date");
CREATE INDEX IF NOT EXISTS "mastery_decisions_reviewDate_idx" ON "mastery_decisions" ("review_date");
CREATE INDEX IF NOT EXISTS "mastery_decisions_deletedAt_idx" ON "mastery_decisions" ("deleted_at");
CREATE INDEX IF NOT EXISTS "mastery_decisions_createdAt_idx" ON "mastery_decisions" ("created_at");
CREATE INDEX IF NOT EXISTS "mastery_decisions_updatedAt_idx" ON "mastery_decisions" ("updated_at");

-- ── Commitment (6 indexes) ──
CREATE INDEX IF NOT EXISTS "commitments_status_idx" ON "commitments" ("status");
CREATE INDEX IF NOT EXISTS "commitments_status_deadline_idx" ON "commitments" ("status", "deadline");
CREATE INDEX IF NOT EXISTS "commitments_domain_status_idx" ON "commitments" ("domain", "status");
CREATE INDEX IF NOT EXISTS "commitments_deletedAt_idx" ON "commitments" ("deleted_at");
CREATE INDEX IF NOT EXISTS "commitments_createdAt_idx" ON "commitments" ("created_at");
CREATE INDEX IF NOT EXISTS "commitments_updatedAt_idx" ON "commitments" ("updated_at");

-- ── PatternDetection (2 indexes) ──
CREATE INDEX IF NOT EXISTS "pattern_detections_patternId_date_idx" ON "pattern_detections" ("pattern_id", "date");
CREATE INDEX IF NOT EXISTS "pattern_detections_createdAt_idx" ON "pattern_detections" ("created_at");

-- ── BodyTracking (1 indexes) ──
CREATE INDEX IF NOT EXISTS "body_tracking_createdAt_idx" ON "body_tracking" ("created_at");

-- ── FinancialSnapshot (1 indexes) ──
CREATE INDEX IF NOT EXISTS "financial_snapshots_createdAt_idx" ON "financial_snapshots" ("created_at");

-- ── ChatConversation (6 indexes) ──
CREATE INDEX IF NOT EXISTS "chat_conversations_archivedAt_lastActiveAt_idx" ON "chat_conversations" ("archived_at", "last_active_at");
CREATE INDEX IF NOT EXISTS "chat_conversations_starredAt_idx" ON "chat_conversations" ("starred_at");
CREATE INDEX IF NOT EXISTS "chat_conversations_missionId_idx" ON "chat_conversations" ("mission_id");
CREATE INDEX IF NOT EXISTS "chat_conversations_createdAt_idx" ON "chat_conversations" ("created_at");
CREATE INDEX IF NOT EXISTS "chat_conversations_updatedAt_idx" ON "chat_conversations" ("updated_at");
CREATE INDEX IF NOT EXISTS "chat_conversations_lastActiveAt_idx" ON "chat_conversations" ("last_active_at");

-- ── ChatMessage (7 indexes) ──
CREATE INDEX IF NOT EXISTS "chat_messages_conversationId_createdAt_idx" ON "chat_messages" ("conversation_id", "created_at");
CREATE INDEX IF NOT EXISTS "chat_messages_conversationId_branchId_idx" ON "chat_messages" ("conversation_id", "branch_id");
CREATE INDEX IF NOT EXISTS "chat_messages_parentMessageId_idx" ON "chat_messages" ("parent_message_id");
CREATE INDEX IF NOT EXISTS "chat_messages_streamingState_createdAt_idx" ON "chat_messages" ("streaming_state", "created_at");
CREATE INDEX IF NOT EXISTS "chat_messages_provider_createdAt_idx" ON "chat_messages" ("provider", "created_at");
CREATE INDEX IF NOT EXISTS "chat_messages_feedbackScore_idx" ON "chat_messages" ("feedback_score");
CREATE INDEX IF NOT EXISTS "chat_messages_createdAt_idx" ON "chat_messages" ("created_at");

-- ── BrainDump (4 indexes) ──
CREATE INDEX IF NOT EXISTS "brain_dumps_date_idx" ON "brain_dumps" ("date");
CREATE INDEX IF NOT EXISTS "brain_dumps_date_actionsTaken_idx" ON "brain_dumps" ("date", "actions_taken");
CREATE INDEX IF NOT EXISTS "brain_dumps_deletedAt_idx" ON "brain_dumps" ("deleted_at");
CREATE INDEX IF NOT EXISTS "brain_dumps_createdAt_idx" ON "brain_dumps" ("created_at");

-- ── AiGeneration (4 indexes) ──
CREATE INDEX IF NOT EXISTS "ai_generations_feature_createdAt_idx" ON "ai_generations" ("feature", "created_at");
CREATE INDEX IF NOT EXISTS "ai_generations_model_createdAt_idx" ON "ai_generations" ("model", "created_at");
CREATE INDEX IF NOT EXISTS "ai_generations_status_createdAt_idx" ON "ai_generations" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "ai_generations_createdAt_idx" ON "ai_generations" ("created_at");

-- ── VisionEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "vision_events_event_timestamp_idx" ON "vision_events" ("event", "timestamp");
CREATE INDEX IF NOT EXISTS "vision_events_camera_timestamp_idx" ON "vision_events" ("camera", "timestamp");
CREATE INDEX IF NOT EXISTS "vision_events_createdAt_idx" ON "vision_events" ("created_at");

-- ── LocalSyncLog (2 indexes) ──
CREATE INDEX IF NOT EXISTS "local_sync_log_module_createdAt_idx" ON "local_sync_log" ("module", "created_at");
CREATE INDEX IF NOT EXISTS "local_sync_log_createdAt_idx" ON "local_sync_log" ("created_at");

-- ── SmartDevice (5 indexes) ──
CREATE INDEX IF NOT EXISTS "smart_devices_platform_status_idx" ON "smart_devices" ("platform", "status");
CREATE INDEX IF NOT EXISTS "smart_devices_location_deviceType_idx" ON "smart_devices" ("location", "deviceType");
CREATE INDEX IF NOT EXISTS "smart_devices_createdAt_idx" ON "smart_devices" ("created_at");
CREATE INDEX IF NOT EXISTS "smart_devices_updatedAt_idx" ON "smart_devices" ("updated_at");
CREATE INDEX IF NOT EXISTS "smart_devices_status_idx" ON "smart_devices" ("status");

-- ── DeviceEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "device_events_deviceId_timestamp_idx" ON "device_events" ("device_id", "timestamp");
CREATE INDEX IF NOT EXISTS "device_events_event_timestamp_idx" ON "device_events" ("event", "timestamp");
CREATE INDEX IF NOT EXISTS "device_events_createdAt_idx" ON "device_events" ("created_at");

-- ── DeviceCommand (3 indexes) ──
CREATE INDEX IF NOT EXISTS "device_commands_deviceId_status_idx" ON "device_commands" ("device_id", "status");
CREATE INDEX IF NOT EXISTS "device_commands_status_createdAt_idx" ON "device_commands" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "device_commands_createdAt_idx" ON "device_commands" ("created_at");

-- ── SessionReport (2 indexes) ──
CREATE INDEX IF NOT EXISTS "session_reports_sessionDate_idx" ON "session_reports" ("session_date");
CREATE INDEX IF NOT EXISTS "session_reports_createdAt_idx" ON "session_reports" ("created_at");

-- ── SystemMetric (3 indexes) ──
CREATE INDEX IF NOT EXISTS "system_metrics_metric_createdAt_idx" ON "system_metrics" ("metric", "created_at");
CREATE INDEX IF NOT EXISTS "system_metrics_source_createdAt_idx" ON "system_metrics" ("source", "created_at");
CREATE INDEX IF NOT EXISTS "system_metrics_createdAt_idx" ON "system_metrics" ("created_at");

-- ── Integration (5 indexes) ──
CREATE INDEX IF NOT EXISTS "integrations_enabled_status_idx" ON "integrations" ("enabled", "status");
CREATE INDEX IF NOT EXISTS "integrations_type_status_idx" ON "integrations" ("type", "status");
CREATE INDEX IF NOT EXISTS "integrations_createdAt_idx" ON "integrations" ("created_at");
CREATE INDEX IF NOT EXISTS "integrations_updatedAt_idx" ON "integrations" ("updated_at");
CREATE INDEX IF NOT EXISTS "integrations_status_idx" ON "integrations" ("status");

-- ── ApiRequestLog (3 indexes) ──
CREATE INDEX IF NOT EXISTS "api_request_logs_path_createdAt_idx" ON "api_request_logs" ("path", "created_at");
CREATE INDEX IF NOT EXISTS "api_request_logs_statusCode_createdAt_idx" ON "api_request_logs" ("status_code", "created_at");
CREATE INDEX IF NOT EXISTS "api_request_logs_createdAt_idx" ON "api_request_logs" ("created_at");

-- ── ScheduledAction (4 indexes) ──
CREATE INDEX IF NOT EXISTS "scheduled_actions_status_scheduledFor_idx" ON "scheduled_actions" ("status", "scheduled_for");
CREATE INDEX IF NOT EXISTS "scheduled_actions_entityType_entityId_idx" ON "scheduled_actions" ("entity_type", "entity_id");
CREATE INDEX IF NOT EXISTS "scheduled_actions_createdAt_idx" ON "scheduled_actions" ("created_at");
CREATE INDEX IF NOT EXISTS "scheduled_actions_updatedAt_idx" ON "scheduled_actions" ("updated_at");

-- ── UserPreference (3 indexes) ──
CREATE INDEX IF NOT EXISTS "user_preferences_category_idx" ON "user_preferences" ("category");
CREATE INDEX IF NOT EXISTS "user_preferences_createdAt_idx" ON "user_preferences" ("created_at");
CREATE INDEX IF NOT EXISTS "user_preferences_updatedAt_idx" ON "user_preferences" ("updated_at");

-- ── AutonomousEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "autonomous_events_ruleName_firedAt_idx" ON "autonomous_events" ("rule_name", "fired_at");
CREATE INDEX IF NOT EXISTS "autonomous_events_result_firedAt_idx" ON "autonomous_events" ("result", "fired_at");
CREATE INDEX IF NOT EXISTS "autonomous_events_firedAt_idx" ON "autonomous_events" ("fired_at");

-- ── SemanticEdge (4 indexes) ──
CREATE INDEX IF NOT EXISTS "semantic_edges_fromMemoryId_score_idx" ON "semantic_edges" ("from_memory_id", "score");
CREATE INDEX IF NOT EXISTS "semantic_edges_toMemoryId_score_idx" ON "semantic_edges" ("to_memory_id", "score");
CREATE INDEX IF NOT EXISTS "semantic_edges_createdAt_idx" ON "semantic_edges" ("created_at");
CREATE INDEX IF NOT EXISTS "semantic_edges_updatedAt_idx" ON "semantic_edges" ("updated_at");

-- ── ToolVerbRatio (2 indexes) ──
CREATE INDEX IF NOT EXISTS "tool_verb_ratios_conversationId_createdAt_idx" ON "tool_verb_ratios" ("conversation_id", "created_at");
CREATE INDEX IF NOT EXISTS "tool_verb_ratios_createdAt_idx" ON "tool_verb_ratios" ("created_at");

-- ── ProviderPing (1 indexes) ──
CREATE INDEX IF NOT EXISTS "provider_pings_provider_pingedAt_idx" ON "provider_pings" ("provider", "pinged_at");

-- ── ToolTelemetry (4 indexes) ──
CREATE INDEX IF NOT EXISTS "tool_telemetry_totalCalls_idx" ON "tool_telemetry" ("total_calls");
CREATE INDEX IF NOT EXISTS "tool_telemetry_failureRatePct_idx" ON "tool_telemetry" ("failure_rate_pct");
CREATE INDEX IF NOT EXISTS "tool_telemetry_createdAt_idx" ON "tool_telemetry" ("created_at");
CREATE INDEX IF NOT EXISTS "tool_telemetry_updatedAt_idx" ON "tool_telemetry" ("updated_at");

-- ── BrainMemory (9 indexes) ──
CREATE INDEX IF NOT EXISTS "brain_memories_category_confidence_idx" ON "brain_memories" ("category", "confidence");
CREATE INDEX IF NOT EXISTS "brain_memories_expiresAt_idx" ON "brain_memories" ("expires_at");
CREATE INDEX IF NOT EXISTS "brain_memories_lastSeen_idx" ON "brain_memories" ("last_seen");
CREATE INDEX IF NOT EXISTS "brain_memories_category_updatedAt_idx" ON "brain_memories" ("category", "updated_at");
CREATE INDEX IF NOT EXISTS "brain_memories_category_createdAt_idx" ON "brain_memories" ("category", "created_at");
CREATE INDEX IF NOT EXISTS "brain_memories_category_deletedAt_idx" ON "brain_memories" ("category", "deleted_at");
CREATE INDEX IF NOT EXISTS "brain_memories_createdAt_idx" ON "brain_memories" ("created_at");
CREATE INDEX IF NOT EXISTS "brain_memories_updatedAt_idx" ON "brain_memories" ("updated_at");
CREATE INDEX IF NOT EXISTS "brain_memories_deletedAt_idx" ON "brain_memories" ("deleted_at");

-- ── AgentTrace (5 indexes) ──
CREATE INDEX IF NOT EXISTS "agent_traces_traceId_startedAt_idx" ON "agent_traces" ("trace_id", "started_at");
CREATE INDEX IF NOT EXISTS "agent_traces_source_createdAt_idx" ON "agent_traces" ("source", "created_at");
CREATE INDEX IF NOT EXISTS "agent_traces_provider_createdAt_idx" ON "agent_traces" ("provider", "created_at");
CREATE INDEX IF NOT EXISTS "agent_traces_errorClass_createdAt_idx" ON "agent_traces" ("error_class", "created_at");
CREATE INDEX IF NOT EXISTS "agent_traces_createdAt_idx" ON "agent_traces" ("created_at");

-- ── SchemaChangeLedger (4 indexes) ──
CREATE INDEX IF NOT EXISTS "schema_change_ledger_status_createdAt_idx" ON "schema_change_ledger" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "schema_change_ledger_environment_appliedAt_idx" ON "schema_change_ledger" ("environment", "applied_at");
CREATE INDEX IF NOT EXISTS "schema_change_ledger_createdAt_idx" ON "schema_change_ledger" ("created_at");
CREATE INDEX IF NOT EXISTS "schema_change_ledger_updatedAt_idx" ON "schema_change_ledger" ("updated_at");

-- ── BrainBusEvent (4 indexes) ──
CREATE INDEX IF NOT EXISTS "brain_bus_events_status_availableAt_idx" ON "brain_bus_events" ("status", "available_at");
CREATE INDEX IF NOT EXISTS "brain_bus_events_topic_createdAt_idx" ON "brain_bus_events" ("topic", "created_at");
CREATE INDEX IF NOT EXISTS "brain_bus_events_createdAt_idx" ON "brain_bus_events" ("created_at");
CREATE INDEX IF NOT EXISTS "brain_bus_events_updatedAt_idx" ON "brain_bus_events" ("updated_at");

-- ── Reflection (6 indexes) ──
CREATE INDEX IF NOT EXISTS "reflections_date_scope_idx" ON "reflections" ("date", "scope");
CREATE INDEX IF NOT EXISTS "reflections_category_confidence_idx" ON "reflections" ("category", "confidence");
CREATE INDEX IF NOT EXISTS "reflections_actionable_acknowledged_idx" ON "reflections" ("actionable", "acknowledged");
CREATE INDEX IF NOT EXISTS "reflections_deletedAt_idx" ON "reflections" ("deleted_at");
CREATE INDEX IF NOT EXISTS "reflections_createdAt_idx" ON "reflections" ("created_at");
CREATE INDEX IF NOT EXISTS "reflections_updatedAt_idx" ON "reflections" ("updated_at");

-- ── Prediction (5 indexes) ──
CREATE INDEX IF NOT EXISTS "predictions_status_targetDate_idx" ON "predictions" ("status", "target_date");
CREATE INDEX IF NOT EXISTS "predictions_category_confidence_idx" ON "predictions" ("category", "confidence");
CREATE INDEX IF NOT EXISTS "predictions_kind_status_idx" ON "predictions" ("kind", "status");
CREATE INDEX IF NOT EXISTS "predictions_createdAt_idx" ON "predictions" ("created_at");
CREATE INDEX IF NOT EXISTS "predictions_updatedAt_idx" ON "predictions" ("updated_at");

-- ── MemoryEdge (5 indexes) ──
CREATE INDEX IF NOT EXISTS "memory_edges_sourceType_sourceId_idx" ON "memory_edges" ("source_type", "source_id");
CREATE INDEX IF NOT EXISTS "memory_edges_targetType_targetId_idx" ON "memory_edges" ("target_type", "target_id");
CREATE INDEX IF NOT EXISTS "memory_edges_relationship_idx" ON "memory_edges" ("relationship");
CREATE INDEX IF NOT EXISTS "memory_edges_createdAt_idx" ON "memory_edges" ("created_at");
CREATE INDEX IF NOT EXISTS "memory_edges_updatedAt_idx" ON "memory_edges" ("updated_at");

-- ── Contradiction (3 indexes) ──
CREATE INDEX IF NOT EXISTS "contradictions_date_category_idx" ON "contradictions" ("date", "category");
CREATE INDEX IF NOT EXISTS "contradictions_resolved_idx" ON "contradictions" ("resolved");
CREATE INDEX IF NOT EXISTS "contradictions_createdAt_idx" ON "contradictions" ("created_at");

-- ── IdentitySnapshot (3 indexes) ──
CREATE INDEX IF NOT EXISTS "identity_snapshots_date_idx" ON "identity_snapshots" ("date");
CREATE INDEX IF NOT EXISTS "identity_snapshots_deletedAt_idx" ON "identity_snapshots" ("deleted_at");
CREATE INDEX IF NOT EXISTS "identity_snapshots_createdAt_idx" ON "identity_snapshots" ("created_at");

-- ── CausalChain (4 indexes) ──
CREATE INDEX IF NOT EXISTS "causal_chains_frequency_idx" ON "causal_chains" ("frequency");
CREATE INDEX IF NOT EXISTS "causal_chains_broken_idx" ON "causal_chains" ("broken");
CREATE INDEX IF NOT EXISTS "causal_chains_createdAt_idx" ON "causal_chains" ("created_at");
CREATE INDEX IF NOT EXISTS "causal_chains_lastSeen_idx" ON "causal_chains" ("last_seen");

-- ── PersonProfile (4 indexes) ──
CREATE INDEX IF NOT EXISTS "person_profiles_role_idx" ON "person_profiles" ("role");
CREATE INDEX IF NOT EXISTS "person_profiles_trustScore_idx" ON "person_profiles" ("trust_score");
CREATE INDEX IF NOT EXISTS "person_profiles_createdAt_idx" ON "person_profiles" ("created_at");
CREATE INDEX IF NOT EXISTS "person_profiles_updatedAt_idx" ON "person_profiles" ("updated_at");

-- ── EnvironmentalSignal (3 indexes) ──
CREATE INDEX IF NOT EXISTS "environmental_signals_date_category_idx" ON "environmental_signals" ("date", "category");
CREATE INDEX IF NOT EXISTS "environmental_signals_urgency_idx" ON "environmental_signals" ("urgency");
CREATE INDEX IF NOT EXISTS "environmental_signals_createdAt_idx" ON "environmental_signals" ("created_at");

-- ── AutomationRule (3 indexes) ──
CREATE INDEX IF NOT EXISTS "automation_rules_enabled_priority_idx" ON "automation_rules" ("enabled", "priority");
CREATE INDEX IF NOT EXISTS "automation_rules_createdAt_idx" ON "automation_rules" ("created_at");
CREATE INDEX IF NOT EXISTS "automation_rules_updatedAt_idx" ON "automation_rules" ("updated_at");

-- ── ErrorLog (2 indexes) ──
CREATE INDEX IF NOT EXISTS "error_logs_level_createdAt_idx" ON "error_logs" ("level", "created_at");
CREATE INDEX IF NOT EXISTS "error_logs_createdAt_idx" ON "error_logs" ("created_at");

-- ── LifeGoal (6 indexes) ──
CREATE INDEX IF NOT EXISTS "life_goals_domain_status_idx" ON "life_goals" ("domain", "status");
CREATE INDEX IF NOT EXISTS "life_goals_horizon_status_idx" ON "life_goals" ("horizon", "status");
CREATE INDEX IF NOT EXISTS "life_goals_deletedAt_idx" ON "life_goals" ("deleted_at");
CREATE INDEX IF NOT EXISTS "life_goals_createdAt_idx" ON "life_goals" ("createdAt");
CREATE INDEX IF NOT EXISTS "life_goals_updatedAt_idx" ON "life_goals" ("updatedAt");
CREATE INDEX IF NOT EXISTS "life_goals_status_idx" ON "life_goals" ("status");

-- ── GoalEvent (3 indexes) ──
CREATE INDEX IF NOT EXISTS "goal_events_goalId_createdAt_idx" ON "goal_events" ("goalId", "created_at");
CREATE INDEX IF NOT EXISTS "goal_events_kind_createdAt_idx" ON "goal_events" ("kind", "created_at");
CREATE INDEX IF NOT EXISTS "goal_events_createdAt_idx" ON "goal_events" ("created_at");

-- ── ReviewLog (2 indexes) ──
CREATE INDEX IF NOT EXISTS "review_logs_type_generatedAt_idx" ON "review_logs" ("type", "generatedAt");
CREATE INDEX IF NOT EXISTS "review_logs_createdAt_idx" ON "review_logs" ("createdAt");

-- ── AutonomousAction (4 indexes) ──
CREATE INDEX IF NOT EXISTS "autonomous_actions_ruleName_createdAt_idx" ON "autonomous_actions" ("ruleName", "createdAt");
CREATE INDEX IF NOT EXISTS "autonomous_actions_approval_createdAt_idx" ON "autonomous_actions" ("approval", "createdAt");
CREATE INDEX IF NOT EXISTS "autonomous_actions_result_createdAt_idx" ON "autonomous_actions" ("result", "createdAt");
CREATE INDEX IF NOT EXISTS "autonomous_actions_createdAt_idx" ON "autonomous_actions" ("createdAt");

-- ── DecisionReplay (2 indexes) ──
CREATE INDEX IF NOT EXISTS "decision_replays_reviewAt_reviewed_idx" ON "decision_replays" ("reviewAt", "reviewed");
CREATE INDEX IF NOT EXISTS "decision_replays_createdAt_idx" ON "decision_replays" ("createdAt");

-- ── CronJobLog (4 indexes) ──
CREATE INDEX IF NOT EXISTS "cron_job_logs_jobName_idx" ON "cron_job_logs" ("jobName");
CREATE INDEX IF NOT EXISTS "cron_job_logs_status_idx" ON "cron_job_logs" ("status");
CREATE INDEX IF NOT EXISTS "cron_job_logs_jobName_status_createdAt_idx" ON "cron_job_logs" ("jobName", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "cron_job_logs_createdAt_idx" ON "cron_job_logs" ("createdAt");

-- ── VectorEmbedding (4 indexes) ──
CREATE INDEX IF NOT EXISTS "vector_embeddings_sourceType_sourceId_idx" ON "vector_embeddings" ("sourceType", "sourceId");
CREATE INDEX IF NOT EXISTS "vector_embeddings_sourceType_idx" ON "vector_embeddings" ("sourceType");
CREATE INDEX IF NOT EXISTS "vector_embeddings_sourceId_idx" ON "vector_embeddings" ("sourceId");
CREATE INDEX IF NOT EXISTS "vector_embeddings_createdAt_idx" ON "vector_embeddings" ("createdAt");

-- ── StrategicLaw (3 indexes) ──
CREATE INDEX IF NOT EXISTS "strategic_laws_book_idx" ON "strategic_laws" ("book");
CREATE INDEX IF NOT EXISTS "strategic_laws_createdAt_idx" ON "strategic_laws" ("createdAt");
CREATE INDEX IF NOT EXISTS "strategic_laws_updatedAt_idx" ON "strategic_laws" ("updatedAt");

-- ── SituationLog (4 indexes) ──
CREATE INDEX IF NOT EXISTS "situation_logs_context_createdAt_idx" ON "situation_logs" ("context", "createdAt");
CREATE INDEX IF NOT EXISTS "situation_logs_lawId_idx" ON "situation_logs" ("lawId");
CREATE INDEX IF NOT EXISTS "situation_logs_createdAt_idx" ON "situation_logs" ("createdAt");
CREATE INDEX IF NOT EXISTS "situation_logs_updatedAt_idx" ON "situation_logs" ("updatedAt");

-- ── DailyStrategy (3 indexes) ──
CREATE INDEX IF NOT EXISTS "daily_strategies_strategyDate_idx" ON "daily_strategies" ("strategyDate");
CREATE INDEX IF NOT EXISTS "daily_strategies_createdAt_idx" ON "daily_strategies" ("createdAt");
CREATE INDEX IF NOT EXISTS "daily_strategies_updatedAt_idx" ON "daily_strategies" ("updatedAt");

-- ── ArsenalLog (4 indexes) ──
CREATE INDEX IF NOT EXISTS "arsenal_logs_toolId_idx" ON "arsenal_logs" ("toolId");
CREATE INDEX IF NOT EXISTS "arsenal_logs_createdAt_idx" ON "arsenal_logs" ("createdAt");
CREATE INDEX IF NOT EXISTS "arsenal_logs_toolId_createdAt_idx" ON "arsenal_logs" ("toolId", "createdAt");
CREATE INDEX IF NOT EXISTS "arsenal_logs_status_idx" ON "arsenal_logs" ("status");

-- ── AutomationPolicy (5 indexes) ──
CREATE INDEX IF NOT EXISTS "automation_policies_surface_enabled_idx" ON "automation_policies" ("surface", "enabled");
CREATE INDEX IF NOT EXISTS "automation_policies_approvalClass_enabled_idx" ON "automation_policies" ("approvalClass", "enabled");
CREATE INDEX IF NOT EXISTS "automation_policies_deletedAt_idx" ON "automation_policies" ("deletedAt");
CREATE INDEX IF NOT EXISTS "automation_policies_createdAt_idx" ON "automation_policies" ("createdAt");
CREATE INDEX IF NOT EXISTS "automation_policies_updatedAt_idx" ON "automation_policies" ("updatedAt");

-- ── AutomationPolicyFire (2 indexes) ──
CREATE INDEX IF NOT EXISTS "automation_policy_fires_policyId_firedAt_idx" ON "automation_policy_fires" ("policy_id", "fired_at");
CREATE INDEX IF NOT EXISTS "automation_policy_fires_firedAt_idx" ON "automation_policy_fires" ("fired_at");

