/**
 * GET /api/morning-brief/today.mp3 · Wave-200 Phase 5 (2026-05-17)
 *
 * Returns the Cartesia-generated audio file for today's morning brief
 * if one exists. Owner-only · short cache (5 min) so the operator can
 * tap from a notification or a home-screen shortcut and hear today's
 * brief without a re-fetch.
 *
 * The audio is generated by the Inngest `operator-morning-brief`
 * function which runs at 10:00 UTC daily. The function caches the
 * raw bytes in BrainMemory(category="morning_brief_audio", key=YYYY-MM-DD)
 * as base64-encoded content. This endpoint decodes and serves them
 * with the correct Content-Type so iOS Safari / Android Chrome
 * autoplay-on-tap works naturally.
 *
 * Returns:
 *   · 200 audio/mpeg · the brief audio for today
 *   · 401 if not the owner
 *   · 404 if today's audio hasn't been generated yet (e.g. before
 *     10:00 UTC, or if Cartesia generation failed)
 *
 * See: docs/adr/0007-morning-brief-multichannel.md
 *      apps/statenour/src/inngest/functions/morning-brief.ts
 */

import { NextResponse } from "next/server";
import { requireSession } from "@/lib/auth-guard";
import { ServiceError } from "@/lib/utils/service-error";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const maxDuration = 10;

export async function GET(req: Request) {
  try {
    await requireSession(req);

    const today = new Date().toISOString().slice(0, 10);
    const row = await prisma.brainMemory.findFirst({
      where: { category: "morning_brief_audio", key: today },
      select: { content: true, metadata: true },
    });

    if (!row?.content) {
      return NextResponse.json(
        {
          error: "no_audio_today",
          hint: "audio generates at 10:00 UTC daily · check CARTESIA_API_KEY",
        },
        { status: 404 },
      );
    }

    const audioBytes = Buffer.from(row.content, "base64");
    const metadata = (row.metadata as Record<string, unknown> | null) ?? {};
    const mime =
      typeof metadata.mime === "string" ? metadata.mime : "audio/mpeg";

    return new NextResponse(audioBytes, {
      status: 200,
      headers: {
        "Content-Type": mime,
        "Content-Length": audioBytes.length.toString(),
        // Cache for 5 minutes · the file changes once a day · short
        // TTL handles same-day re-listens without re-decoding.
        "Cache-Control": "private, max-age=300",
      },
    });
  } catch (err) {
    if (err instanceof ServiceError) {
      return NextResponse.json(
        { error: err.message },
        { status: err.status },
      );
    }
    return NextResponse.json(
      {
        error: "audio_serve_failed",
        message: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }
}
