// One-off generator: bakes the bundled fonts + downsized product shots into
// adAssets.ts as base64 constants, so the Ad Studio renderer needs NO runtime
// file IO (survives esbuild bundling + any cwd on Railway).
// Re-run after changing a font or product image:  node gen-assets.mjs
import fs from "fs";
import path from "path";

const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"));
const FONTS = path.join(HERE, "fonts");
const ASSETS = path.join(HERE, "assets"); // repo-local source product shots (objects, no people)
const b64 = (f) => fs.readFileSync(f).toString("base64");

const anton = b64(path.join(FONTS, "Anton-Regular.ttf"));
const barlowSemi = b64(path.join(FONTS, "BarlowCondensed-SemiBold.ttf"));
const barlowBold = b64(path.join(FONTS, "BarlowCondensed-Bold.ttf"));
const hero = b64(path.join(ASSETS, "tire-hero.jpg"));
const tread = b64(path.join(ASSETS, "tread-macro.jpg"));

const ts = `/**
 * Ad Studio baked assets (base64) — GENERATED by gen-assets.mjs. Do not edit by hand.
 * Bundling-safe: no runtime file IO. Fonts = Anton (display) + Barlow Condensed
 * (body); images = photoreal PRODUCT object shots (tire/tread, NO people).
 */
/* eslint-disable */
export const ANTON_TTF_B64 = ${JSON.stringify(anton)};
export const BARLOW_SEMI_TTF_B64 = ${JSON.stringify(barlowSemi)};
export const BARLOW_BOLD_TTF_B64 = ${JSON.stringify(barlowBold)};
export const TIRE_HERO_JPG_B64 = ${JSON.stringify(hero)};
export const TREAD_MACRO_JPG_B64 = ${JSON.stringify(tread)};
`;
fs.writeFileSync(path.join(HERE, "adAssets.ts"), ts);
const kb = Math.round(ts.length / 1024);
console.log(`wrote adAssets.ts (${kb}kb): fonts(3) + product images(2)`);
