"use client";

/**
 * NicksMorningBrief · Wave AA Phase 2 · 2026-05-28.
 *
 * The Sam-layer header that replaces "first move wins the day". A
 * single 1-paragraph synthesis from Nick across all active missions ·
 * cached daily in BrainMemory(category=mission_morning_brief, key=YYYY-MM-DD)
 * so the page doesn't burn AI cost on every navigation.
 *
 *   "3 missions in motion · Power Atlas needs the detail-panel
 *    cleanup to unblock the ledger work. Mobile polish stalled
 *    for 4 days. Best move now: tick the ErrorBoundary task."
 *
 * Refreshes once per day OR on major mission state changes (new
 * mission created · mission completed · 5+ tasks ticked in 6h).
 *
 * Self-hides when the response is empty (operator is mid-build, no
 * brief content) so the header doesn't show a "Nick is thinking…"
 * spinner indefinitely.
 */

import { useEffect, useMemo, useState } from "react";
import { Brain } from "lucide-react";
import type { Project, Task } from "@/components/actions/shared";
import { isUserProject } from "@/lib/services/mission-helpers";

interface NicksMorningBriefProps {
  missions: Project[];
  tasks: Task[];
}

export function NicksMorningBrief({ missions, tasks }: NicksMorningBriefProps) {
  const [brief, setBrief] = useState<string | null>(null);

  // wave-AA-audit · derive the active mission count up here so the
  // effect's gate condition is a pure derivation, not a setState-bearing
  // branch inside the effect body. Pre-fix the effect did `if (active
  // .length === 0) { setBrief(null); setLoading(false); return; }` which
  // triggered the react-hooks/set-state-in-effect rule. Now we either
  // run the fetch or no-op, with a single state path.
  const activeCount = useMemo(
    () =>
      missions.filter((m) => m.status === "ACTIVE" && isUserProject(m))
        .length,
    [missions],
  );

  // Page-mount fetch · cheap (hits the static markdown file generated by the Cron).
  // Skipped when there are no active missions.
  useEffect(() => {
    if (activeCount === 0) return;
    let cancelled = false;
    void (async () => {
      try {
        // Look for today's generated AIE brief
        const today = new Date().toISOString().split("T")[0];
        const res = await fetch(`/briefs/${today}.md`);
        
        if (!res.ok) {
          if (!cancelled) setBrief(null);
          return;
        }
        
        const text = await res.text();
        if (!cancelled) setBrief(text.trim() || null);
      } catch {
        // Silent · the brief is non-essential UX; the page still renders
        // without it. setBrief stays at its initial null so the section
        // self-hides via the guard below.
      }
    })();
    return () => {
      cancelled = true;
    };
    // We intentionally only refetch when the mission COUNT changes, not
    // on every task tick · the brief is meant to be a daily summary,
    // not a real-time feed.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeCount]);

  if (!brief) return null;

  return (
    <section
      aria-label="nick's morning brief"
      className="rounded-lg border border-[var(--gold)]/30 bg-[var(--gold)]/[0.04] px-4 py-3"
    >
      <div className="flex items-start gap-2">
        <Brain
          size={12}
          className="text-[var(--gold)] mt-0.5 shrink-0"
          strokeWidth={1.75}
        />
        <div className="flex-1 min-w-0">
          <p className="text-[9px] font-mono uppercase tracking-[0.18em] text-[var(--gold)]/80">
            nick · morning brief
          </p>
          <p className="mt-1 text-[12px] text-[var(--text-primary)] leading-snug whitespace-pre-line">
            {brief}
          </p>
        </div>
      </div>
    </section>
  );
}

function summarizeTasks(tasks: Task[]): {
  open: number;
  doing: number;
  doneToday: number;
  overdue: number;
} {
  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);
  let open = 0;
  let doing = 0;
  let doneToday = 0;
  let overdue = 0;
  const now = Date.now();
  for (const t of tasks) {
    if (t.status === "DONE") {
      const at = t.lastTouchedAt ?? t.updatedAt;
      if (at && new Date(at).getTime() >= todayStart.getTime()) doneToday++;
    } else {
      open++;
      if (t.status === "DOING") doing++;
      if (t.dueDate && new Date(t.dueDate).getTime() < now) overdue++;
    }
  }
  return { open, doing, doneToday, overdue };
}
