// Shared reel storyboard data for reels 9-30 (days 9-30 of the 30-day calendar).
// dir + clips[4] + music drive generation; vo + segs drive voice + assembly.
export type ReelSeg = { src: string; dur: number; cap: string; size: number };
export type ReelData = { dir: string; clips: string[]; music: string; vo: string; segs: ReelSeg[] };

export const REELS: ReelData[] = [
  { dir: "reel9",
    clips: [
      "extreme macro of a worn-out gray sock stretched and stuffed over a car dashboard air vent, dust motes drifting in a beam of light, cinematic shallow focus, vertical 9:16",
      "POV inside a car cabin, a dusty old sock jammed over the A/C vents while faint warm haze ripples weakly through the fabric, moody interior light, vertical 9:16",
      "macro of a clean white pleated cabin air filter sliding crisply into place beside the limp gray sock on dark studio velvet, dramatic side light, vertical 9:16",
      "POV in a car cabin as cool clear airflow streams strong from open vents with no sock, dust gone, sunlit fresh interior, cinematic glow, vertical 9:16" ],
    music: "soft quirky pizzicato strings, light and curious",
    vo: "Your car has been breathing through a dirty sock. A clogged cabin filter means weak airflow and a musty smell. Swap it and the air gets fresh again. If yours smells off stop by for a free check.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "A SOCK ON YOUR VENTS", size: 50 },
      { src: "clip2.mp4", dur: 3.5, cap: "WEAK MUSTY AIRFLOW", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "JUST SWAP THE FILTER", size: 52 },
      { src: "clip4.mp4", dur: 3.0, cap: "FRESH AIR AGAIN", size: 56 },
      { src: "clip1.mp4", dur: 2.5, cap: "FREE CHECK ANYTIME", size: 54 } ] },
  { dir: "reel10",
    clips: [
      "a single shiny steel nail standing under a harsh interrogation spotlight in a dark police lineup room, height chart on the wall behind, sweat-like droplets on the metal, cinematic noir, vertical 9:16",
      "extreme macro of a nail embedded in the center tread of a car tire, deep rubber grooves around it, soft green spotlight, hopeful mood, cinematic, vertical 9:16",
      "extreme macro of a nail stuck in the smooth sidewall of a car tire, harsh red warning light, tense dramatic shadows, cinematic, vertical 9:16",
      "a nail standing in a noir lineup as a green REPAIRABLE stamp glows over the tread zone and a red NO stamp glows over the sidewall zone, moody spotlight, vertical 9:16" ],
    music: "tense noir jazz bass, dramatic and playful",
    vo: "We have a suspect. A nail in the tread is often repairable. But a nail in the sidewall usually is not, that area flexes too much to patch safely. Picked up a nail lately stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "WE HAVE A SUSPECT", size: 54 },
      { src: "clip2.mp4", dur: 3.5, cap: "TREAD IS OFTEN FIXABLE", size: 48 },
      { src: "clip3.mp4", dur: 3.5, cap: "SIDEWALL USUALLY NOT", size: 50 },
      { src: "clip4.mp4", dur: 3.0, cap: "LOCATION DECIDES IT", size: 52 },
      { src: "clip1.mp4", dur: 2.5, cap: "WELL TAKE A LOOK", size: 56 } ] },
  { dir: "reel11",
    clips: [
      "four car tires seated in chairs around a formal dinner table under a warm chandelier, place settings and plates, one tire visibly more worn than the others, cinematic Pixar-style realism, vertical 9:16",
      "macro across a dinner table as one balding worn tire leans forward tensely toward three plump healthy tires, dramatic candlelight, cinematic, vertical 9:16",
      "four tires lifting and rotating positions around the dinner table in a smooth swap, motion blur of movement, warm cinematic light, vertical 9:16",
      "four evenly matched tires sitting calmly around the dinner table clinking glasses in harmony, soft golden light, cinematic, vertical 9:16" ],
    music: "warm playful string waltz, gentle and witty",
    vo: "The tires are having a dispute. One is wearing down faster than the rest. Rotating them about every five to seven thousand miles helps them wear more evenly. Due for a rotation stop by and well sort it out.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "A TIRE DINNER DISPUTE", size: 48 },
      { src: "clip2.mp4", dur: 3.5, cap: "ONE WEARS DOWN FASTER", size: 48 },
      { src: "clip3.mp4", dur: 3.5, cap: "ROTATE EVERY 5 TO 7K", size: 50 },
      { src: "clip4.mp4", dur: 3.0, cap: "EVEN WEAR ALL AROUND", size: 50 },
      { src: "clip1.mp4", dur: 2.5, cap: "STOP BY ANYTIME", size: 56 } ] },
  { dir: "reel12",
    clips: [
      "a single car tire bolted to the front of an old washing machine violently shaking and rattling across a tile floor, motion blur, dramatic side light, cinematic realism, vertical 9:16",
      "a tire-mounted washing machine wobbling and walking forward as the whole frame buzzes and shudders, speedometer needle climbing in the corner, cinematic, vertical 9:16",
      "macro of a small metal balance weight clipping cleanly onto the rim of the tire, the violent shaking instantly calming to stillness, crisp light, cinematic, vertical 9:16",
      "the same tire and washing machine now perfectly still and steady on the tile floor, gentle glow, calm and smooth, cinematic, vertical 9:16" ],
    music: "rattling percussive groove easing into smooth calm",
    vo: "Why is your steering wheel doing the laundry. An out of balance wheel can cause a shake that shows up around sixty miles an hour. A quick re-balance smooths it right out. Feel a shimmy stop by for a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "A SHAKE AT SPEED", size: 56 },
      { src: "clip2.mp4", dur: 3.5, cap: "WORST AROUND 60 MPH", size: 50 },
      { src: "clip3.mp4", dur: 4.0, cap: "RE-BALANCE SMOOTHS IT", size: 48 },
      { src: "clip4.mp4", dur: 2.5, cap: "STEADY AGAIN", size: 58 },
      { src: "clip1.mp4", dur: 2.5, cap: "STOP BY FOR A LOOK", size: 54 } ] },
  { dir: "reel13",
    clips: [
      "macro of a glowing amber TPMS warning light on a dark car dashboard, the little horseshoe symbol with an exclamation point, dramatic close-up, cinematic, vertical 9:16",
      "a cute tiny amber cartoon TPMS warning light character with big worried eyes pacing nervously on the dashboard, glowing softly, Pixar-style, cinematic, vertical 9:16",
      "the little anxious TPMS character pointing down toward a slightly low soft car tire, concerned expression, dramatic dashboard glow, cinematic, vertical 9:16",
      "the TPMS character smiling and relaxed as the tire fills to firm and round, warm reassuring glow on the dashboard, Pixar-style, cinematic, vertical 9:16" ],
    music: "cute nervous bouncy synth turning cheerful",
    vo: "This little light is panicking for a reason. The TPMS light means a tire is low on pressure. It is worth checking soon, low pressure wears tires and hurts your mileage. Light on stop by and well check your pressure.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "THE LIGHT IS ON", size: 58 },
      { src: "clip2.mp4", dur: 3.5, cap: "IT MEANS LOW PRESSURE", size: 48 },
      { src: "clip3.mp4", dur: 3.5, cap: "CHECK A TIRE SOON", size: 54 },
      { src: "clip4.mp4", dur: 3.0, cap: "EASY TO FIX", size: 60 },
      { src: "clip1.mp4", dur: 2.5, cap: "WELL CHECK IT FREE", size: 54 } ] },
  { dir: "reel14",
    clips: [
      "extreme macro of a car tire tread styled like a vain greasy comb-over haircut, rubber blocks combed sideways at an angle over a thin worn edge, dramatic salon light, cinematic, vertical 9:16",
      "macro side angle of tire tread edges feathered and slanted like badly combed hair, one side smooth one side ragged, sharp studio light, cinematic, vertical 9:16",
      "a vintage comb dragging across the angled feathered tire tread leaving telltale slanted ridges, extreme macro, dramatic light, cinematic, vertical 9:16",
      "split macro of a neat evenly worn tire tread beside the messy combed-over feathered tread, clean comparison, soft studio light, cinematic, vertical 9:16" ],
    music: "smug lounge guitar, sly and stylish",
    vo: "This tire has a serious comb-over. When tread edges feel feathered and angled, that often points to an alignment problem. Catching it early helps your tires last. Notice odd wear stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "A TIRE COMB-OVER", size: 56 },
      { src: "clip2.mp4", dur: 3.5, cap: "FEATHERED ANGLED EDGES", size: 46 },
      { src: "clip3.mp4", dur: 3.5, cap: "OFTEN AN ALIGNMENT SIGN", size: 46 },
      { src: "clip4.mp4", dur: 3.0, cap: "CATCH IT EARLY", size: 58 },
      { src: "clip1.mp4", dur: 2.5, cap: "WELL TAKE A LOOK", size: 56 } ] },
  { dir: "reel15",
    clips: [
      "a smooth bald car tire riding a surfboard up the face of a towering blue ocean wave, spray flying, dramatic golden hour light, cinematic photoreal, vertical 9:16",
      "macro of a bald tire skimming across a thin sheet of water with no grooves to push it away, water spraying sideways, dramatic light, cinematic, vertical 9:16",
      "the bald tire wiping out and tumbling off the crest of a big wave into white foam, dramatic splash, slow motion, cinematic, vertical 9:16",
      "a deep-treaded tire rolling steadily through heavy rain on wet pavement, water channeling cleanly out of the grooves, confident and stable, cinematic, vertical 9:16" ],
    music: "surf rock guitar, breezy then dramatic wipeout",
    vo: "This bald tire thinks it can surf. With low tread there are no grooves to channel water away, so you can hydroplane in the rain. Good tread keeps you gripping the road. Curious about your tread stop by for a free check.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "A TIRE GOES SURFING", size: 52 },
      { src: "clip2.mp4", dur: 3.5, cap: "LOW TREAD CANT CLEAR WATER", size: 42 },
      { src: "clip3.mp4", dur: 3.0, cap: "THAT IS HYDROPLANING", size: 50 },
      { src: "clip4.mp4", dur: 3.5, cap: "GOOD TREAD GRIPS", size: 56 },
      { src: "clip1.mp4", dur: 2.5, cap: "FREE TREAD CHECK", size: 56 } ] },
  { dir: "reel16",
    clips: [
      "a single car tire lacing up tiny white ice skates on a glossy frozen pond, breath-fog in the cold air, dramatic wintry light, cinematic photoreal, vertical 9:16",
      "a tire on ice skates wobbling and slipping awkwardly across a frozen pond, snowflakes drifting, comedic struggle, cinematic, vertical 9:16",
      "the same tire pulling on chunky rugged snow boots and standing firm and confident in deep snow, frosty light, cinematic, vertical 9:16",
      "macro of a deep aggressive winter tire tread biting into fresh snow with grip, snow crystals flying, dramatic cold light, cinematic, vertical 9:16" ],
    music: "jingly frosty bells, playful and crisp",
    vo: "This tire tried to wear ice skates. Below about forty five degrees winter tires grip much better than all seasons, their rubber stays soft in the cold. If you drive through real winters stop by and well talk options.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "A TIRE ON ICE SKATES", size: 50 },
      { src: "clip2.mp4", dur: 3.0, cap: "ALL-SEASONS SLIP IN COLD", size: 46 },
      { src: "clip3.mp4", dur: 3.5, cap: "WINTER TIRES GRIP BELOW 45", size: 42 },
      { src: "clip4.mp4", dur: 3.0, cap: "SOFT RUBBER BITES SNOW", size: 48 },
      { src: "clip1.mp4", dur: 2.5, cap: "STOP BY TO TALK OPTIONS", size: 48 } ] },
  { dir: "reel17",
    clips: [
      "a dusty donut spare tire lying flat in a dark car trunk, a faded laminated gym membership card resting on its rim, soft dramatic light, forgotten and cobwebbed, cinematic macro, vertical 9:16",
      "extreme macro of a deflating donut spare tire slowly sagging in shadow, fine dust rising off the rubber, cold blue garage light, cinematic, vertical 9:16",
      "a cracked aging donut spare tire under a single shaft of light in a cluttered garage, calendar pages fluttering past it in slow motion, surreal photoreal, vertical 9:16",
      "a fresh properly inflated donut spare tire glowing on a clean pedestal next to a sad deflated dusty one, side by side comparison, cinematic rim light, vertical 9:16" ],
    music: "low curious music box, sparse, slightly eerie",
    vo: "Your spare tire is the forgotten gym card of your trunk. It loses air and ages while you ignore it. Then the day you need it, its flat too. Stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "THE FORGOTTEN SPARE", size: 54 },
      { src: "clip2.mp4", dur: 3.5, cap: "IT LOSES AIR TOO", size: 56 },
      { src: "clip3.mp4", dur: 4.0, cap: "AND IT AGES IN THE DARK", size: 46 },
      { src: "clip4.mp4", dur: 3.5, cap: "CHECK IT EARLY", size: 56 },
      { src: "clip1.mp4", dur: 2.0, cap: "WE WILL TAKE A LOOK", size: 52 } ] },
  { dir: "reel18",
    clips: [
      "extreme macro inside a brake fluid reservoir, a saturated kitchen sponge floating in amber fluid swelling with absorbed water, droplets clinging, cinematic light, vertical 9:16",
      "a sponge slowly soaking up water inside a translucent brake fluid reservoir, fluid darkening from clear amber to murky, dramatic backlight, photoreal macro, vertical 9:16",
      "POV looking down into a brake fluid reservoir, a bloated waterlogged sponge sinking heavily, tiny bubbles rising, moody cinematic shadow, vertical 9:16",
      "side by side macro of two reservoirs, one with a dry clean sponge in bright amber fluid one with a soaked dark sponge in cloudy fluid, comparison, cinematic, vertical 9:16" ],
    music: "slow dripping ambient, soft suspense",
    vo: "Brake fluid is a sponge in disguise. Over time it quietly drinks up moisture and your pedal starts feeling soft and spongy. A periodic flush keeps it firm. If your pedal feels off its worth checking.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "FLUID THAT DRINKS WATER", size: 48 },
      { src: "clip2.mp4", dur: 3.5, cap: "MOISTURE SNEAKS IN", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "THE PEDAL GOES SOFT", size: 52 },
      { src: "clip4.mp4", dur: 3.5, cap: "A FLUSH KEEPS IT FIRM", size: 52 },
      { src: "clip1.mp4", dur: 2.0, cap: "WORTH CHECKING SOON", size: 54 } ] },
  { dir: "reel19",
    clips: [
      "a car engine shaped like a giant chrome kettle, steam screaming from a spout on the valve cover, rattling lid, dramatic kitchen light, surreal photoreal, vertical 9:16",
      "extreme close up of a bubbling overheating engine kettle, jets of steam hissing out, temperature gauge needle climbing into red, cinematic, vertical 9:16",
      "a rattling kettle engine on the edge of a violent boil, hot orange glow from within, steam filling a dark garage, tense photoreal macro, vertical 9:16",
      "a calm cool engine kettle with a steady green gauge next to a screaming red boiling one, side by side comparison, cinematic light, vertical 9:16" ],
    music: "rising tense strings, kettle whistle accent",
    vo: "Your engine is basically a kettle that should never boil. Low or old coolant lets the heat climb until it whistles over. A quick level check keeps things calm. Pop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "AN ENGINE IS A KETTLE", size: 52 },
      { src: "clip2.mp4", dur: 3.5, cap: "LOW COOLANT LETS IT BOIL", size: 46 },
      { src: "clip3.mp4", dur: 4.0, cap: "THE HEAT CLIMBS FAST", size: 54 },
      { src: "clip4.mp4", dur: 3.5, cap: "CHECK YOUR COOLANT LEVEL", size: 46 },
      { src: "clip1.mp4", dur: 2.0, cap: "WE WILL TAKE A LOOK", size: 52 } ] },
  { dir: "reel20",
    clips: [
      "extreme macro of a dry rotted rubber band stretched taut over two pegs, deep cracks splitting the surface, dramatic side light, tension visible, photoreal, vertical 9:16",
      "a brittle cracked rubber band stretching toward its snapping point in slow motion, dust flaking off the splits, cinematic high contrast, vertical 9:16",
      "the dry rotted rubber band snapping apart in extreme slow motion, frozen mid break, fragments suspended, dark dramatic backdrop, photoreal macro, vertical 9:16",
      "a fresh supple black rubber band next to a cracked crumbling one on dark slate, side by side comparison, cinematic rim light, vertical 9:16" ],
    music: "tense pizzicato strings, ticking tension",
    vo: "One little belt runs half your car. When it dries out and cracks like an old rubber band it can snap and leave you stranded. Caught early its a small thing. Worth a quick look anytime.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "ONE BELT RUNS A LOT", size: 54 },
      { src: "clip2.mp4", dur: 3.5, cap: "IT DRIES AND CRACKS", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "THEN IT SNAPS", size: 60 },
      { src: "clip4.mp4", dur: 3.5, cap: "CHEAP TO CATCH EARLY", size: 52 },
      { src: "clip1.mp4", dur: 2.0, cap: "WORTH A QUICK LOOK", size: 54 } ] },
  { dir: "reel21",
    clips: [
      "a pair of foggy oxidized car headlights wearing tiny round reading glasses perched on the lenses, cloudy yellowed plastic, whimsical photoreal, soft garage light, vertical 9:16",
      "extreme close up of a cloudy hazy headlight squinting through little reading glasses at a dark road, dim weak beam, cinematic mood, vertical 9:16",
      "a foggy headlight with reading glasses slowly fogging over even more at night, faint struggling light cone, moody photoreal macro, vertical 9:16",
      "a crystal clear restored headlight beside a yellowed foggy one wearing reading glasses, side by side comparison, bright versus dim beam, cinematic, vertical 9:16" ],
    music: "gentle quirky ukulele, soft and warm",
    vo: "Old headlights need reading glasses too. As the plastic clouds and yellows it quietly steals your night vision. The good news is foggy lenses can be restored. Stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "HEADLIGHTS GET OLD", size: 54 },
      { src: "clip2.mp4", dur: 3.5, cap: "CLOUDY LENSES DIM IT", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "NIGHT VISION FADES", size: 54 },
      { src: "clip4.mp4", dur: 3.5, cap: "THEY CAN BE RESTORED", size: 52 },
      { src: "clip1.mp4", dur: 2.0, cap: "WE WILL TAKE A LOOK", size: 52 } ] },
  { dir: "reel22",
    clips: [
      "a metal wheel bearing built like a squeaky hamster wheel, a tiny rusty cage spinning with a groan, dramatic shadow, surreal photoreal macro, vertical 9:16",
      "extreme close up of a groaning wheel bearing hamster wheel spinning faster, squeaks rising in pitch, faint heat shimmer, cinematic, vertical 9:16",
      "a worn wheel bearing hamster wheel rattling and wobbling at high speed, dust shaking loose, tense moody light, photoreal macro, vertical 9:16",
      "a smooth silent new bearing wheel beside a rusty squeaking worn one, side by side comparison, cinematic rim light, vertical 9:16" ],
    music: "playful creaky mechanical rhythm, rising pitch",
    vo: "A wheel bearing can sound like a tired hamster wheel. A low hum or roar that grows louder the faster you drive is the classic sign. It only gets worse. If you hear it stop by.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "THE HAMSTER WHEEL HUM", size: 50 },
      { src: "clip2.mp4", dur: 3.5, cap: "LOUDER WITH SPEED", size: 56 },
      { src: "clip3.mp4", dur: 4.0, cap: "IT ONLY GROWS", size: 60 },
      { src: "clip4.mp4", dur: 3.5, cap: "GET THE HUM CHECKED", size: 52 },
      { src: "clip1.mp4", dur: 2.0, cap: "WORTH CHECKING SOON", size: 54 } ] },
  { dir: "reel23",
    clips: [
      "a full size car balanced on a single giant pogo stick on an empty road, frozen mid bounce, springs compressed, dramatic dusk light, surreal photoreal, vertical 9:16",
      "a car bouncing wildly down a street on a huge pogo stick, body pitching up and down, motion blur, cinematic slow motion, vertical 9:16",
      "low angle of a car on a pogo stick overshooting a stop line, bouncing past it as brake lights glow, tense photoreal, vertical 9:16",
      "a steady planted car on solid struts beside a wobbly car teetering on a pogo stick, side by side comparison, cinematic light, vertical 9:16" ],
    music: "boingy bouncy bass, playful then tense",
    vo: "Worn struts turn your car into a pogo stick. It keeps bouncing long after a bump and that bounce can stretch out your stopping distance. Smooth rides are safer rides. Swing by anytime.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "RIDING ON A POGO STICK", size: 48 },
      { src: "clip2.mp4", dur: 3.5, cap: "WORN STRUTS KEEP BOUNCING", size: 44 },
      { src: "clip3.mp4", dur: 4.0, cap: "STOPPING TAKES LONGER", size: 50 },
      { src: "clip4.mp4", dur: 3.5, cap: "SMOOTH IS SAFER", size: 56 },
      { src: "clip1.mp4", dur: 2.0, cap: "WE WILL TAKE A LOOK", size: 52 } ] },
  { dir: "reel24",
    clips: [
      "extreme close-up of a glowing orange check engine light symbol floating in pitch black darkness, ember light, mysterious haze, cinematic, vertical 9:16",
      "a stone sphinx statue with a glowing orange check engine icon carved into its chest, sitting in the dark posing a riddle, dramatic rim light, vertical 9:16",
      "a handheld OBD2 code scanner plugged under a dashboard, screen lighting up with green diagnostic codes in the dark, cinematic glow, vertical 9:16",
      "the glowing sphinx slowly fading away as clear green code text appears in the dark, mystery resolved, cinematic, vertical 9:16" ],
    music: "mysterious low synth, slow suspense, cinematic",
    vo: "Your dash lit a riddle in the dark. The check engine light is a sphinx, it will not just tell you. Dont guess. Scan it for codes and the code points the way. If yours is on stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.0, cap: "A RIDDLE IN THE DARK", size: 50 },
      { src: "clip2.mp4", dur: 3.5, cap: "IT WILL NOT JUST TELL YOU", size: 46 },
      { src: "clip3.mp4", dur: 4.0, cap: "SCAN IT FOR CODES", size: 54 },
      { src: "clip4.mp4", dur: 3.5, cap: "THE CODE POINTS THE WAY", size: 48 },
      { src: "clip1.mp4", dur: 2.0, cap: "WORTH CHECKING", size: 56 } ] },
  { dir: "reel25",
    clips: [
      "a single car tire inflating like a rubber balloon stretched taut and shiny, surface trembling under pressure, studio dark background, cinematic, vertical 9:16",
      "macro of an over-stretched tire surface bulging in the center seam straining, tense rubber under strain, dramatic light, cinematic, vertical 9:16",
      "a tire pressure gauge needle swinging far past the safe zone into red, glowing dial in the dark, cinematic close-up, vertical 9:16",
      "a calm correctly inflated tire sitting next to a door jamb PSI sticker, soft balanced light, satisfying and stable, cinematic, vertical 9:16" ],
    music: "tense rising tone then calm release, playful",
    vo: "This tire wants to be a balloon. But too much air gives a harsh ride and wears the center faster. More is not better. Match the door sticker number. Not sure of yours stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "NOT A BALLOON", size: 58 },
      { src: "clip2.mp4", dur: 3.5, cap: "TOO MUCH AIR HURTS", size: 52 },
      { src: "clip3.mp4", dur: 3.5, cap: "HARSH RIDE WORN CENTER", size: 46 },
      { src: "clip4.mp4", dur: 4.0, cap: "MATCH THE DOOR STICKER", size: 48 },
      { src: "clip1.mp4", dur: 2.0, cap: "WELL TAKE A LOOK", size: 54 } ] },
  { dir: "reel26",
    clips: [
      "a packed leather suitcase bungee-strapped tightly onto a car tire standing upright, ready to travel, warm road-trip light, cinematic, vertical 9:16",
      "macro of a thumb-deep tire tread being measured before a trip, deep grooves in golden light, cinematic detail, vertical 9:16",
      "a car trunk open revealing a clean spare tire mounted and ready next to neat fluid bottles, warm light, cinematic, vertical 9:16",
      "the suitcase-on-tire rolling down a long open highway at golden hour toward the horizon, motion blur, cinematic, vertical 9:16" ],
    music: "upbeat road-trip acoustic, bright, hopeful",
    vo: "This tire packed its bags. Before a long drive give your car the same checklist. Look at the tread the tire pressure the spare and the fluids. A few minutes now means a smoother trip. Heading out soon stop by first.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "READY TO TRAVEL", size: 56 },
      { src: "clip2.mp4", dur: 3.5, cap: "CHECK TREAD AND PRESSURE", size: 44 },
      { src: "clip3.mp4", dur: 4.0, cap: "SPARE AND FLUIDS TOO", size: 50 },
      { src: "clip4.mp4", dur: 3.0, cap: "SMOOTHER TRIP AHEAD", size: 52 },
      { src: "clip1.mp4", dur: 2.0, cap: "STOP BY FIRST", size: 58 } ] },
  { dir: "reel27",
    clips: [
      "a paper price tag dangling from a tire string slowly flipping over in the dark, suspense, spotlight, cinematic, vertical 9:16",
      "the flipped tag revealing a shiny red poker chip glinting like a jackpot, dramatic casino light, macro, cinematic, vertical 9:16",
      "a gloved inspection lamp sweeping across a used tire tread checking every groove, bright focused light in the dark, cinematic, vertical 9:16",
      "the winning poker chip resting on a thoroughly inspected clean used tire, soft trophy light, satisfying, cinematic, vertical 9:16" ],
    music: "playful jazzy swing, light, confident",
    vo: "Flip the tag and you might find a winning hand. Inspected used tires can be real savings. The trick is every single one gets checked first for tread and damage. Curious what fits your car stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "FLIP THE TAG", size: 60 },
      { src: "clip2.mp4", dur: 3.0, cap: "A WINNING HAND", size: 58 },
      { src: "clip3.mp4", dur: 4.0, cap: "EACH ONE CHECKED FIRST", size: 46 },
      { src: "clip4.mp4", dur: 3.5, cap: "REAL SAVINGS", size: 60 },
      { src: "clip1.mp4", dur: 2.0, cap: "WELL TAKE A LOOK", size: 54 } ] },
  { dir: "reel28",
    clips: [
      "extreme macro of glossy black tire dressing being applied to a tire sidewall, deep wet shine spreading, oddly satisfying, studio light, vertical 9:16",
      "a thick gloss coat sweeping across raised tire lettering revealing a deep mirror black finish, ASMR macro, cinematic, vertical 9:16",
      "close-up of a clean shining tire surface where a tiny hairline crack becomes clearly visible under the gloss, sharp detail light, cinematic, vertical 9:16",
      "a finished mirror-glossy tire reflecting soft studio lights, flawless deep black shine, satisfying, cinematic, vertical 9:16" ],
    music: "soft ASMR lofi, smooth, satisfying",
    vo: "Pure gloss therapy. But a clean tire is not just pretty. When the rubber shines you can actually spot cracks and damage early. So keep them clean and keep an eye out. Want a second set of eyes stop by.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "GLOSS THERAPY", size: 60 },
      { src: "clip2.mp4", dur: 3.5, cap: "DEEP MIRROR SHINE", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "SPOT CRACKS EARLY", size: 54 },
      { src: "clip4.mp4", dur: 3.0, cap: "CLEAN MEANS SEEN", size: 56 },
      { src: "clip1.mp4", dur: 2.0, cap: "STOP BY ANYTIME", size: 56 } ] },
  { dir: "reel29",
    clips: [
      "a shiny metal brake rotor and red caliper styled like an opera singer mid-performance, dramatic stage spotlight, photoreal, cinematic, vertical 9:16",
      "macro of a brake rotor vibrating and emitting visible sound rings like a piercing high note, sparks of light, dramatic stage, cinematic, vertical 9:16",
      "extreme close-up of a thin worn brake pad with a tiny metal wear indicator tab touching the rotor, sharp detail light, cinematic, vertical 9:16",
      "the operatic brake caliper taking a bow under a fading spotlight on a dark stage, dramatic finale light, cinematic, vertical 9:16" ],
    music: "dramatic operatic strings, bold, theatrical",
    vo: "Hear that high note from your wheels. That brake squeal is often the built in wear indicator singing. It means the pads are getting low. It is a built in heads up. Hearing a squeal stop by and well take a look.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "THE HIGH NOTE", size: 60 },
      { src: "clip2.mp4", dur: 3.5, cap: "THAT BRAKE SQUEAL", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "ITS A WEAR INDICATOR", size: 48 },
      { src: "clip4.mp4", dur: 3.0, cap: "PADS ARE GETTING LOW", size: 50 },
      { src: "clip1.mp4", dur: 2.0, cap: "WELL TAKE A LOOK", size: 54 } ] },
  { dir: "reel30",
    clips: [
      "a car bundled up in a cozy knit hat mittens and a wool scarf standing in falling snow, charming and warm, cinematic winter light, vertical 9:16",
      "close-up of a car battery wearing tiny knit mittens with frost on the terminals, cozy winter detail, cinematic, vertical 9:16",
      "macro of a snow-dusted tire tread and a windshield wiper sweeping fresh snow, crisp cold light, cinematic, vertical 9:16",
      "the bundled-up cozy car parked safe and warm under gentle snowfall at dusk, soft glowing window light, cinematic, vertical 9:16" ],
    music: "warm cozy winter bells, gentle, charming",
    vo: "Your car wants a scarf too. Before winter rolls in give it a quick once over. Check the battery the tires the fluids and the wipers. A little prep keeps the cold from catching you off guard. Stop by and well get you ready.",
    segs: [
      { src: "clip1.mp4", dur: 2.5, cap: "BUNDLE UP", size: 60 },
      { src: "clip2.mp4", dur: 3.5, cap: "CHECK THE BATTERY", size: 54 },
      { src: "clip3.mp4", dur: 4.0, cap: "TIRES FLUIDS WIPERS", size: 50 },
      { src: "clip4.mp4", dur: 3.0, cap: "BEAT THE COLD", size: 60 },
      { src: "clip1.mp4", dur: 2.0, cap: "WELL GET YOU READY", size: 52 } ] },
];
