CREATE TABLE `tire_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(50) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerPhone` varchar(30) NOT NULL,
	`customerEmail` varchar(320),
	`vehicleInfo` varchar(255),
	`tireBrand` varchar(100) NOT NULL,
	`tireModel` varchar(255) NOT NULL,
	`tireSize` varchar(50) NOT NULL,
	`quantity` int NOT NULL DEFAULT 4,
	`pricePerTire` int NOT NULL DEFAULT 0,
	`serviceFeePerTire` int NOT NULL DEFAULT 3500,
	`fetPerTire` int NOT NULL DEFAULT 0,
	`totalAmount` int NOT NULL DEFAULT 0,
	`status` enum('received','confirmed','ordered','in_transit','delivered','scheduled','installed','cancelled') NOT NULL DEFAULT 'received',
	`adminNotes` text,
	`customerNotes` text,
	`gatewayOrderRef` varchar(100),
	`expectedDelivery` timestamp,
	`installationDate` timestamp,
	`customerId` int,
	`bookingId` int,
	`emailSent` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tire_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `tire_orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
