-- 0131_places_content_purge.sql · NO-OP STUB (2026-09-29)
--
-- This slot held Q-48's Google Places content purge (#2675): four production DELETEs
-- whose own header said "Operator-run only; never auto-applied". But scripts/db-migrate.ts
-- and drizzle-kit migrate apply every drizzle/*.sql file, so the purge would have run as a
-- side effect of the next unrelated migration. The purge now lives at
-- docs/operations/operator-sql/0131_places_content_purge.sql, which no runner reads.
--
-- The file stays so the journal keeps its sequence (server/__tests__/migration-journal.test.ts).
-- SELECT 1 keeps it a valid statement with no side effect for both runners.
-- server/__tests__/migration-row-removal.test.ts fails if row-removing SQL returns here.
SELECT 1;
