"use client";

/**
 * TodaysPicks · Wave AB Phase 1B+2 · 2026-05-28.
 *
 * The Sam-layer killer feature. Three operator-grade outreach picks
 * generated by /api/ai/relationships-pick-today · each one shows:
 *
 *   · the person + a 1-line rationale (why now)
 *   · Nick's drafted message (1-2 sentences · editable inline)
 *   · [Send via SMS] [Edit] [Different angle ↻] actions
 *   · auto-logs to the RelationshipLedger when the operator hits Send
 *
 * This is what Linear / Notion / Cloze / Salesforce can't ship · they
 * don't have BrainMemory + KEPT_WORD + ledger + Greene law cross-ref
 * + mastery-day correlation. The pick endpoint reads all of them.
 *
 * Fail-silent · if the pick endpoint returns empty the component
 * hides. If the draft endpoint fails the operator can type their
 * own draft into the textarea.
 */

import { useCallback, useEffect, useState } from "react";
import { Loader2, RefreshCw, Send, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface Pick {
  personId: string;
  personName: string;
  rationale: string;
  /** Optional · pre-computed draft. Falls back to client-side fetch
   *  when the pick endpoint chose not to pre-compute. */
  draft?: string;
  draftAngle?: string;
}

interface PicksResponse {
  picks: Pick[];
  generatedAt: string;
}

export interface TodaysPicksProps {
  /** Bumped by the parent when ledger changes · forces a refetch so
   *  picks reflect just-logged outreach. */
  refetchKey?: number;
  onLogged?: () => void;
}

export function TodaysPicks({ refetchKey = 0, onLogged }: TodaysPicksProps) {
  const [picks, setPicks] = useState<Pick[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      setLoading(true);
      try {
        const res = await fetch("/api/ai/relationships-pick-today", {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
        });
        if (!res.ok) throw new Error("picks_request_failed");
        const data = (await res.json()) as PicksResponse;
        if (!cancelled) setPicks(data.picks ?? []);
      } catch {
        if (!cancelled) setPicks([]);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [refetchKey]);

  const visible = (picks ?? []).filter((p) => !dismissed.has(p.personId));

  if (loading) {
    return (
      <section aria-label="loading picks" className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-base)] px-4 py-5">
        <div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-[0.18em] text-[var(--text-tertiary)]">
          <Loader2 size={10} className="animate-spin" strokeWidth={2} />
          nick is picking today&apos;s outreach…
        </div>
      </section>
    );
  }

  if (visible.length === 0) return null;

  return (
    <section aria-label="today's picks" className="space-y-2">
      <div className="flex items-center gap-2 px-1 text-[10px] font-mono uppercase tracking-[0.18em] text-[var(--gold)]/80">
        <span>🎯 reach out today</span>
        <span className="text-[var(--text-tertiary)]/60">·</span>
        <span className="text-[var(--text-tertiary)] tabular-nums">
          {visible.length} {visible.length === 1 ? "pick" : "picks"}
        </span>
      </div>

      <div className="space-y-2">
        {visible.map((pick) => (
          <PickCard
            key={pick.personId}
            pick={pick}
            onDismiss={() =>
              setDismissed((prev) => {
                const next = new Set(prev);
                next.add(pick.personId);
                return next;
              })
            }
            onLogged={onLogged}
          />
        ))}
      </div>
    </section>
  );
}

interface PickCardProps {
  pick: Pick;
  onDismiss: () => void;
  onLogged?: () => void;
}

function PickCard({ pick, onDismiss, onLogged }: PickCardProps) {
  const [draft, setDraft] = useState(pick.draft ?? "");
  const [draftLoading, setDraftLoading] = useState(false);
  const [sending, setSending] = useState(false);

  // Lazy-fetch the draft if the pick endpoint didn't pre-compute it.
  useEffect(() => {
    if (pick.draft || draft) return;
    let cancelled = false;
    void (async () => {
      setDraftLoading(true);
      try {
        const res = await fetch("/api/ai/draft-outreach", {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            personId: pick.personId,
            rationale: pick.rationale,
          }),
        });
        if (!res.ok) throw new Error("draft_failed");
        const data = (await res.json()) as { draft: string };
        if (!cancelled) setDraft(data.draft || "");
      } catch {
        if (!cancelled) setDraft("");
      } finally {
        if (!cancelled) setDraftLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pick.personId]);

  const handleRegen = useCallback(async () => {
    setDraftLoading(true);
    try {
      const res = await fetch("/api/ai/draft-outreach", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          personId: pick.personId,
          rationale: pick.rationale,
          regenerate: true,
        }),
      });
      if (!res.ok) throw new Error("draft_failed");
      const data = (await res.json()) as { draft: string };
      setDraft(data.draft || "");
    } catch {
      toast.error("Couldn't regenerate. Edit manually instead.");
    } finally {
      setDraftLoading(false);
    }
  }, [pick.personId, pick.rationale]);

  const handleSend = useCallback(async () => {
    const trimmed = draft.trim();
    if (!trimmed) return;
    setSending(true);
    try {
      const res = await fetch("/api/relationships/log-outreach", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          personId: pick.personId,
          message: trimmed,
          rationale: pick.rationale,
        }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      toast.success(`Logged outreach to ${pick.personName}.`);
      onLogged?.();
      onDismiss();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      toast.error(`Couldn't log: ${msg}`);
    } finally {
      setSending(false);
    }
  }, [pick.personId, pick.personName, pick.rationale, draft, onDismiss, onLogged]);

  return (
    <article className="rounded-lg border border-[var(--gold)]/25 bg-[var(--bg-base)] p-3 space-y-2">
      <header className="flex items-start gap-2">
        <div className="flex-1 min-w-0">
          <h3 className="text-[13px] font-bold uppercase tracking-[0.08em] text-[var(--text-primary)] truncate">
            {pick.personName}
          </h3>
          <p className="text-[11px] text-[var(--text-secondary)] leading-snug mt-0.5">
            {pick.rationale}
          </p>
        </div>
        <button
          type="button"
          onClick={onDismiss}
          aria-label="skip pick"
          className="shrink-0 inline-flex h-11 w-11 items-center justify-center rounded text-[var(--text-tertiary)] hover:text-[var(--text-secondary)] hover:bg-[var(--bg-raised)]/15 active:scale-95 transition-transform"
        >
          <X size={14} strokeWidth={2} />
        </button>
      </header>

      <div className="rounded-md border border-[var(--border-default)]/60 bg-[var(--bg-raised)]/[0.04]">
        <div className="px-2 py-1 border-b border-[var(--border-default)]/40 flex items-center gap-2">
          <span className="text-[9px] font-mono uppercase tracking-[0.18em] text-[var(--gold)]/70">
            nick&apos;s draft
          </span>
          {draftLoading && (
            <Loader2
              size={9}
              className="animate-spin text-[var(--text-tertiary)]"
              strokeWidth={2}
            />
          )}
          <button
            type="button"
            onClick={handleRegen}
            disabled={draftLoading || sending}
            aria-label="regenerate draft"
            className="ml-auto inline-flex min-h-[36px] items-center gap-1 px-2 py-1.5 -my-1 text-[10px] font-mono uppercase tracking-[0.15em] text-[var(--text-tertiary)] hover:text-[var(--gold)] active:scale-95 transition-transform disabled:opacity-50"
          >
            <RefreshCw size={11} strokeWidth={1.75} />
            different angle
          </button>
        </div>
        <textarea
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          disabled={draftLoading || sending}
          rows={3}
          placeholder={
            draftLoading
              ? "drafting…"
              : "type the outreach yourself or hit ‘different angle’ above"
          }
          className={cn(
            // wave-AB.d-mobile · 16px font prevents iOS zoom-on-focus
            // when the operator taps to edit the draft.
            "w-full bg-transparent px-2.5 py-2 text-[16px] text-[var(--text-primary)] placeholder:text-[var(--text-tertiary)]/70 resize-none",
            "focus:outline-none disabled:opacity-50",
          )}
        />
      </div>

      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={handleSend}
          disabled={!draft.trim() || sending || draftLoading}
          className="inline-flex min-h-[44px] items-center gap-1.5 rounded-md border border-[var(--gold)]/50 bg-[var(--gold)]/10 px-3.5 py-2 text-[13px] font-medium text-[var(--gold)] hover:bg-[var(--gold)]/15 active:scale-95 transition-transform disabled:opacity-50"
        >
          {sending ? (
            <Loader2 size={12} className="animate-spin" strokeWidth={2} />
          ) : (
            <Send size={12} strokeWidth={2} />
          )}
          log outreach
        </button>
        <span className="text-[10px] font-mono text-[var(--text-tertiary)]/70 leading-tight">
          logs +1 deposit to {pick.personName.split(" ")[0]}&apos;s ledger
        </span>
      </div>
    </article>
  );
}
