/**
 * Selective repair — async, durable, attempt-accounted (closes #820's three
 * unresolved review findings):
 *
 * P1 (repair blocked the request path): the endpoint now VALIDATES,
 * authorizes, invalidates stale outputs, and QUEUES a durable repair request
 * — provider generation happens in the pipeline worker on the next pulse,
 * reusing the existing claim/retry/stuck-recovery machinery.
 *
 * P2 (stale MP4 survived): queueing a repair immediately moves the current
 * mp4 into payload.mp4History and NULLs mp4Url — the stale render can no
 * longer be previewed, approved, or published; the QA verdict and contact
 * sheet are flagged stale.
 *
 * P2 (failed reservation reused): every PROVIDER ATTEMPT gets a fresh,
 * immutable reservation (`<logicalRepairId>_p<n>`); failed attempts stay on
 * the ledger as failed spend and are never settled or reused.
 *
 * State model (unambiguous):
 *   job.status: repair_queued -> repair_rendering -> assets_ready (existing
 *   assembly takes over) | repair_failed
 *   entry.state: queued -> rendering -> ready_for_assembly | failed
 */
import { randomUUID } from "crypto";
import { createLogger } from "../lib/logger";
import { queueStateForReelStatus } from "../../shared/reelQueue";
import { beatGenerationRoute, type ShotSource } from "../../shared/shotRouter";
import type { BoundaryActorContext } from "./autonomyControl";

const log = createLogger("services:selective-repair");

const MAX_PROVIDER_ATTEMPTS = 2;

export interface RepairInstruction {
  code?: string;
  description?: string;
  preserve: string[];
  change: string[];
}

/** Deterministic: the original generation prompt stays the base truth; the
 *  repair block narrows what may differ. */
export function buildRepairPrompt(originalPrompt: string, instruction: RepairInstruction): string {
  const preserve = instruction.preserve.length ? instruction.preserve.join("; ") : "everything not named below";
  const change = instruction.change.length ? instruction.change.join("; ") : instruction.description ?? "fix the flagged defect";
  return [
    originalPrompt,
    ``,
    `REPAIR INSTRUCTION (this is a regeneration of a rejected take):`,
    `KEEP IDENTICAL: ${preserve}.`,
    `CHANGE ONLY: ${change}.`,
    `Everything else must match the original prompt exactly.`,
  ].join("\n");
}

export interface ProviderAttempt {
  providerAttemptId: string;
  reservationId: string;
  startedAt: string;
  outcome: "succeeded" | "failed";
  error?: string;
}

export interface RepairQueueEntry {
  logicalRepairId: string;
  beatNumber: number;
  instruction: RepairInstruction;
  state: "queued" | "rendering" | "ready_for_assembly" | "failed";
  requestedAt: string;
  attempts: ProviderAttempt[];
  previousClipUrl: string | null;
  newClipUrl?: string;
  /**
   * self_hosted only: the Video Forge key/job for THIS logical repair. Lives on
   * the entry (persisted in payload) so a local timeout resumes the same GPU
   * job on the next pulse instead of buying a second render.
   */
  selfHosted?: import("./videoForgeClient").SelfHostedBeatState;
}

export interface RepairRequestResult {
  jobId: number;
  beatNumber: number;
  logicalRepairId: string;
  state: "queued";
}

/**
 * Why a provider would refuse to regenerate this beat, read from the job
 * payload alone; null when it would accept. ONE rule for requestBeatRepair and
 * for the daily-reel cron's choice of what to repair (2026-10-09, PR #2940
 * review): a target the executor refuses holds the Reel instead of repairing
 * a beat that could have been fixed.
 */
export function beatRepairRefusal(payload: unknown, beatNumber: number, jobId: number): string | null {
  const p = (payload && typeof payload === "object" ? payload : {}) as {
    storyboardBeats?: unknown;
    promptPack?: unknown;
    higgsfieldPromptPack?: unknown;
  };
  const beats = (Array.isArray(p.storyboardBeats) ? p.storyboardBeats : []) as Array<{
    beatNumber: number;
    visual?: string | null;
    source?: ShotSource | null;
  }>;
  const beat = beats.find((b) => b && b.beatNumber === beatNumber);
  if (!beat) return `beat ${beatNumber} not in job ${jobId}`;
  // A beat declared real or deterministic is never regenerated by a provider
  // (2026-10-08): a synthetic replacement of real footage is the one thing the
  // production doctrine forbids. Nor is a beat whose visual names no object: a
  // second paid clip of "the physical subject" shows the topic no better than
  // the first.
  const declaredRoute = beatGenerationRoute(beat);
  if (declaredRoute !== "generate") {
    const why = declaredRoute === "needs_real_footage"
      ? "is declared real"
      : declaredRoute === "needs_deterministic_render"
        ? "is declared deterministic"
        : "names no object (a placeholder visual)";
    return `beat ${beatNumber} of job ${jobId} ${why} — a provider never regenerates it`;
  }
  const pack = p.promptPack ?? p.higgsfieldPromptPack ?? [];
  const prompts = (Array.isArray(pack) ? pack : []) as Array<{ beatNumber: number }>;
  if (!prompts.find((x) => x && x.beatNumber === beatNumber)) return `no prompt for beat ${beatNumber} in job ${jobId}`;
  return null;
}

/**
 * Operator-facing: validate + authorize + invalidate stale outputs + QUEUE.
 * Returns immediately — no provider call on the request path (P1).
 */
export async function requestBeatRepair(input: {
  jobId: number;
  beatNumber: number;
  instruction?: RepairInstruction;
  /**
   * WHO is asking. Load-bearing at the spend boundary, not decoration.
   *
   * enforceAtBoundary treats an operator's own tap as self-approval
   * (REQUIRE_APPROVAL -> APPROVED_BY_OPERATOR) and lets operator paths proceed
   * LOUD when the policy store is unreachable, while cron and autonomous actors
   * are BLOCKED and FAIL CLOSED. This function hardcoded "operator" for every
   * caller, so when the daily reel cron began requesting PAID repairs on its own
   * (2026-09-09, policy v11) it inherited a human's approval authority and a
   * human's break-glass posture at the exact moment money is spent.
   *
   * A caller that is not a person MUST pass its real actor. The default stays
   * "operator" because the admin button is the original caller and genuinely is
   * one.
   */
  actor?: BoundaryActorContext;
}): Promise<RepairRequestResult> {
  const { getDb } = await import("../db");
  const d = await getDb();
  if (!d) throw new Error("DB not available");
  const { reelJobs } = await import("../../drizzle/schema");
  const { eq } = await import("drizzle-orm");

  const [job] = await d.select().from(reelJobs).where(eq(reelJobs.id, input.jobId)).limit(1);
  if (!job) throw new Error(`job ${input.jobId} not found`);
  if (!["assembled", "assets_ready", "repair_failed"].includes(job.status)) {
    throw new Error(`job ${input.jobId} is ${job.status} — repair needs assembled, assets_ready, or repair_failed`);
  }
  const payload = JSON.parse(job.payload ?? "{}");
  const beats: Array<{ beatNumber: number; visual?: string | null; source?: ShotSource | null }> = payload.storyboardBeats ?? [];
  // Per-beat eligibility (beat exists, declared route is "generate", a prompt
  // exists) is beatRepairRefusal, shared with the cron's target choice.
  // Refused before any spend check or queue write; the daily-reel drain reads a
  // refusal to queue as a plain hold.
  const refusal = beatRepairRefusal(payload, input.beatNumber, input.jobId);
  if (refusal) throw new Error(refusal);
  const beatIndex = beats.findIndex((b) => b.beatNumber === input.beatNumber);
  const clipUrls: string[] = job.clipUrlsJson ? JSON.parse(job.clipUrlsJson) : [];
  if (clipUrls.length !== beats.length) {
    throw new Error(`job ${input.jobId} has ${clipUrls.length} clips for ${beats.length} beats — repair needs a complete clip set`);
  }
  const queue: RepairQueueEntry[] = payload.repairQueue ?? [];
  if (queue.some((e) => e.state === "queued" || e.state === "rendering")) {
    throw new Error(`job ${input.jobId} already has a repair in flight — one at a time`);
  }

  const verdictFinding = (payload.renderedQa?.findings ?? []).find(
    (f: { beatNumber: number | null }) => f.beatNumber === input.beatNumber,
  );
  const instruction: RepairInstruction = input.instruction ?? {
    code: verdictFinding?.code,
    description: verdictFinding?.description,
    preserve: verdictFinding?.preserve ?? [],
    change: verdictFinding?.change ?? [],
  };

  // Repair cap counts LOGICAL repairs on this job — provider retries within
  // a repair do not consume the cap, failed repair requests do.
  const { enforceAtBoundary } = await import("./autonomyControl");
  const { reelClipCostUsd, dailySpendUsd } = await import("./generationLedger");
  // Price the request at the lane that will actually render it. Hardcoding the
  // Seedance figure here meant the policy gate could REFUSE a template_stock
  // repair — one that costs nothing — on the grounds of a budget it would not
  // touch, and under-price a Veo repair by whatever the per-second rate makes
  // it. The gate is only as good as the number it is handed.
  const { selectReelVideoProvider } = await import("./reelPipeline");
  const spend = await dailySpendUsd();
  await enforceAtBoundary(
    {
      type: "enqueue_render",
      format: "reel",
      estimatedCostUsd: reelClipCostUsd(await selectReelVideoProvider()),
      today: {
        repairAttemptsForAsset: queue.length,
        ...(spend !== null ? { generationCostUsd: spend } : {}),
      },
    },
    input.actor ?? { type: "operator", id: `repair_request_job_${input.jobId}` },
    payload.genomeId ?? null,
  );

  const logicalRepairId = `rep_${randomUUID().slice(0, 12)}`;
  const entry: RepairQueueEntry = {
    logicalRepairId,
    beatNumber: input.beatNumber,
    instruction,
    state: "queued",
    requestedAt: new Date().toISOString(),
    attempts: [],
    previousClipUrl: clipUrls[beatIndex] ?? null,
  };
  payload.repairQueue = [...queue, entry];

  // P2: the current render is stale the moment a repair is accepted —
  // preserve it as history, remove it from every consumable surface.
  if (job.mp4Url) {
    payload.mp4History = [
      ...(payload.mp4History ?? []),
      { mp4Url: job.mp4Url, replacedAt: new Date().toISOString(), reason: `repair beat ${input.beatNumber} (${logicalRepairId})` },
    ];
  }
  if (payload.renderedQa) payload.renderedQa = { ...payload.renderedQa, staleAfterRepair: true };

  await d
    .update(reelJobs)
    .set({
      payload: JSON.stringify(payload),
      mp4Url: null,
      status: "repair_queued",
      queueState: queueStateForReelStatus("repair_queued"),
      attempts: 0,
      error: null,
    })
    .where(eq(reelJobs.id, input.jobId));

  // P1 (gated assessment, confirmed): the job's mp4 was cleared but the
  // LINKED INVENTORY row still carried the stale render in assetPaths at
  // review_ready — the rejected mp4 stayed one Approve tap from publishing
  // while its repair was queued. Demote the row alongside the job.
  if (job.briefId && job.briefId !== "unknown") {
    const { socialContentInventory } = await import("../../drizzle/schema");
    await d
      .update(socialContentInventory)
      .set({ status: "pending", assetPaths: [], errorMessage: `render superseded: repair queued for beat ${input.beatNumber}`, updatedAt: new Date() })
      .where(eq(socialContentInventory.id, job.briefId))
      .catch((e: unknown) => log.error("failed to demote inventory row for repair-queued job", { jobId: input.jobId, briefId: job.briefId, e: e instanceof Error ? e.message : String(e) }));
  }

  log.info("beat repair QUEUED (no provider call on request path)", {
    jobId: input.jobId,
    beat: input.beatNumber,
    logicalRepairId,
  });
  return { jobId: input.jobId, beatNumber: input.beatNumber, logicalRepairId, state: "queued" };
}

/**
 * Pipeline worker stage: claim one repair_queued job, run ONE provider
 * attempt with a FRESH per-attempt reservation, and either hand the job to
 * the existing assembly stage or park it as repair_failed at the attempt cap.
 * Kill switches are re-checked FRESH here — an operator's emergency stop
 * between request and execution wins.
 */
export async function processNextRepairJob(): Promise<{ processed: boolean; jobId?: number; status?: string; error?: string }> {
  const { getDb } = await import("../db");
  const d = await getDb();
  if (!d) return { processed: false };
  const { reelJobs } = await import("../../drizzle/schema");
  const { eq, and } = await import("drizzle-orm");

  const [job] = await d.select().from(reelJobs).where(eq(reelJobs.status, "repair_queued")).limit(1);
  if (!job) return { processed: false };

  // Claim via conditional update — and gate on the AFFECTED-ROW COUNT, not a
  // re-select (gated assessment P2, confirmed: the loser's zero-row update
  // followed by a re-select ALSO saw status=repair_rendering, so two workers
  // could both proceed and double-spend the same repair).
  const { affectedRowCount } = await import("../lib/db-affected");
  const claimRes = await d.update(reelJobs).set({ status: "repair_rendering", queueState: queueStateForReelStatus("repair_rendering"), updatedAt: new Date() }).where(and(eq(reelJobs.id, job.id), eq(reelJobs.status, "repair_queued")));
  if (affectedRowCount(claimRes) !== 1) return { processed: false };
  const [claimed] = await d.select().from(reelJobs).where(eq(reelJobs.id, job.id)).limit(1);
  if (!claimed) return { processed: false };

  const payload = JSON.parse(claimed.payload ?? "{}");
  const queue: RepairQueueEntry[] = payload.repairQueue ?? [];
  const entry = queue.find((e) => e.state === "queued" || e.state === "rendering");
  if (!entry) {
    await d.update(reelJobs).set({ status: "repair_failed", queueState: queueStateForReelStatus("repair_failed"), error: "repair_queued with no queue entry" }).where(eq(reelJobs.id, job.id));
    return { processed: true, jobId: job.id, status: "repair_failed", error: "no queue entry" };
  }
  entry.state = "rendering";

  // Fresh emergency check — leave the job queued (not failed) under a switch.
  const { getEmergencyControlsFresh } = await import("./autonomyControl");
  const emergency = await getEmergencyControlsFresh();
  if (emergency.controls.globalKillSwitch || emergency.controls.generationKillSwitch) {
    entry.state = "queued";
    await d.update(reelJobs).set({ status: "repair_queued", queueState: queueStateForReelStatus("repair_queued"), payload: JSON.stringify(payload) }).where(eq(reelJobs.id, job.id));
    log.warn("repair deferred — kill switch armed", { jobId: job.id });
    return { processed: true, jobId: job.id, status: "repair_queued", error: "kill switch armed" };
  }

  const attemptNumber = entry.attempts.length + 1;
  if (attemptNumber > MAX_PROVIDER_ATTEMPTS) {
    entry.state = "failed";
    await d.update(reelJobs).set({ status: "repair_failed", queueState: queueStateForReelStatus("repair_failed"), payload: JSON.stringify(payload), error: `repair ${entry.logicalRepairId} exhausted ${MAX_PROVIDER_ATTEMPTS} provider attempts` }).where(eq(reelJobs.id, job.id));
    return { processed: true, jobId: job.id, status: "repair_failed" };
  }

  // WHICH LANE IS THIS JOB ACTUALLY ON?
  //
  // Both the provider and the price below were hardcoded to Higgsfield, on a
  // path that runs for EVERY reel regardless of which provider generated it.
  // Two separate consequences, and the second is the expensive one:
  //
  //   1. The ledger mislabelled the spend. A repair on a Veo job was filed as
  //      Higgsfield/seedance1_5 at the Seedance price, so every provider
  //      comparison and the daily budget both counted the wrong number — and a
  //      repair on a template_stock job, which costs nothing at all, consumed
  //      real budget and could push maxGenerationCostPerDayUsd over for renders
  //      that are free.
  //   2. It actually CALLED Higgsfield. A shop pinned to the free local lane
  //      got a real paid API render the moment any beat needed repair — the
  //      provider pin is a deliberate cost decision and the repair path was
  //      quietly overriding it.
  //
  // The generation pipeline already selects per run and already fails loudly on
  // a provider it has no branch for (reelPipeline.ts). Repair now does both.
  const { selectReelVideoProvider, reelLedgerModel } = await import("./reelPipeline");
  // A self-hosted repair already holding a Forge job STAYS on that lane: switching the
  // pin mid-render would orphan a GPU job that keeps running (and, rented, billing).
  const repairProvider = entry.selfHosted?.selfHostedJobId ? "self_hosted" : await selectReelVideoProvider();

  // P2: fresh, immutable, per-attempt reservation — failed attempts remain
  // failed spend on the ledger and are never reused.
  const { reserve, settle, fail: failReservation, reelClipCostUsd } = await import("./generationLedger");
  const { getActivePolicy } = await import("./autonomyControl");
  const policy = await getActivePolicy();
  const repairCostUsd = reelClipCostUsd(repairProvider);
  const reservationId = `${entry.logicalRepairId}_p${attemptNumber}`;
  try {
    await reserve({
      actionId: reservationId,
      campaignId: payload.genomeId ?? null,
      provider: repairProvider,
      model: reelLedgerModel(repairProvider),
      operation: "beat_repair",
      estimatedCostUsd: repairCostUsd,
      dailyBudgetUsd: policy.limits.maxGenerationCostPerDayUsd,
    });
  } catch (err) {
    // Budget breach at attempt time: leave queued for tomorrow's window.
    entry.state = "queued";
    await d.update(reelJobs).set({ status: "repair_queued", queueState: queueStateForReelStatus("repair_queued"), payload: JSON.stringify(payload) }).where(eq(reelJobs.id, job.id));
    return { processed: true, jobId: job.id, status: "repair_queued", error: err instanceof Error ? err.message : "reservation failed" };
  }

  const pack: Array<{ beatNumber: number; prompt: string; negativePrompt?: string }> = payload.promptPack ?? payload.higgsfieldPromptPack ?? [];
  const beatPrompt = pack.find((p) => p.beatNumber === entry.beatNumber)!;
  const attempt: ProviderAttempt = {
    providerAttemptId: `${entry.logicalRepairId}_a${attemptNumber}`,
    reservationId,
    startedAt: new Date().toISOString(),
    outcome: "failed",
  };

  let settleUsd = repairCostUsd;
  try {
    let newClipUrl: string;
    if (repairProvider === "self_hosted") {
      const { assertDurableStorageForGeneration } = await import("../storage");
      assertDurableStorageForGeneration(`reel job ${job.id} self_hosted beat repair`);
      const { renderSelfHostedBeat } = await import("./videoForgeClient");
      entry.selfHosted ??= { beatNumber: entry.beatNumber };
      const persist = async () => {
        await d.update(reelJobs).set({ payload: JSON.stringify(payload), updatedAt: new Date() }).where(eq(reelJobs.id, job.id));
      };
      const hero = payload.visualWorld?.heroFrameUrl as string | undefined;
      const r = await renderSelfHostedBeat({
        beat: entry.selfHosted,
        idempotencyBase: `nickstire-repair-${entry.logicalRepairId}`,
        prompt: buildRepairPrompt(beatPrompt.prompt, entry.instruction),
        negativePrompt: beatPrompt.negativePrompt,
        startImageUrl:
          process.env.REEL_IMAGE_CONDITIONING === "true" && hero && /\.(jpe?g|png|webp)([?#]|$)/i.test(hero) ? hero : undefined,
        persist,
        heartbeat: async () => {
          await d.update(reelJobs).set({ updatedAt: new Date() }).where(eq(reelJobs.id, job.id));
        },
        metadata: { reel_job_id: job.id, beat_number: entry.beatNumber, repair: entry.logicalRepairId },
      });
      newClipUrl = r.url;
      settleUsd = r.receipt.computeUsd; // measured, not the estimate
    } else if (repairProvider === "template_stock") {
      // Local ffmpeg re-render. It writes to disk first and re-hosts through
      // storagePut, exactly like the generation path — so it carries the same
      // durable-storage precondition. Without it the repaired clip lands on
      // ephemeral disk and the next deploy destroys it, which on a repair is
      // worse than on a first render: the ORIGINAL clip has already been
      // invalidated by the time we get here.
      //
      // The repair PROMPT is deliberately not passed. This lane takes no text
      // — it renders a gradient sweep and assembly burns the beat's
      // onScreenText over the stitched clips. Sending a prompt here would put
      // internal instructions on screen, which is the exact defect the free
      // lane shipped with and had removed.
      const { assertDurableStorageForGeneration } = await import("../storage");
      assertDurableStorageForGeneration(`reel job ${job.id} template_stock beat repair`);
      const { generateTemplateStockClip } = await import("./templateStockStudio");
      newClipUrl = await generateTemplateStockClip({ beatNumber: entry.beatNumber });
    } else if (repairProvider === "higgsfield") {
      const { generateReelClipVideo } = await import("./higgsfieldStudio");
      newClipUrl = await generateReelClipVideo({
        prompt: buildRepairPrompt(beatPrompt.prompt, entry.instruction),
        negativePrompt: beatPrompt.negativePrompt,
      });
    } else {
      // Veo has never had a repair branch. It was not "unsupported" — it
      // silently ran Higgsfield and billed it as Seedance, which is spending
      // real money under another provider's name. Same failure the generation
      // path already refuses by name; refuse it here too rather than inherit a
      // default that costs money.
      throw new Error(
        `beat repair has no branch for REEL_VIDEO_PROVIDER "${repairProvider}" — it must not fall through to another provider`,
      );
    }
    await settle(reservationId, settleUsd);
    attempt.outcome = "succeeded";
    entry.attempts.push(attempt);

    const beats: Array<{ beatNumber: number }> = payload.storyboardBeats ?? [];
    const beatIndex = beats.findIndex((b) => b.beatNumber === entry.beatNumber);
    const clipUrls: string[] = claimed.clipUrlsJson ? JSON.parse(claimed.clipUrlsJson) : [];
    clipUrls[beatIndex] = newClipUrl;
    entry.newClipUrl = newClipUrl;
    entry.state = "ready_for_assembly";
    payload.repairs = [
      ...(payload.repairs ?? []),
      { beatNumber: entry.beatNumber, attempt: attemptNumber, findingCode: entry.instruction.code ?? null, previousClipUrl: entry.previousClipUrl, newClipUrl, repairedAt: new Date().toISOString(), logicalRepairId: entry.logicalRepairId },
    ];

    await d
      .update(reelJobs)
      .set({ clipUrlsJson: JSON.stringify(clipUrls), payload: JSON.stringify(payload), status: "assets_ready", queueState: queueStateForReelStatus("assets_ready"), productionReadyAt: new Date(), attempts: 0, error: null })
      .where(eq(reelJobs.id, job.id));
    log.info("beat repair rendered — job handed to assembly", { jobId: job.id, beat: entry.beatNumber, attempt: attemptNumber });
    return { processed: true, jobId: job.id, status: "assets_ready" };
  } catch (err) {
    // A LOCAL timeout on a self-hosted render is not a failed attempt: the GPU
    // job is alive and its key/id are on the entry. Keep the reservation open
    // (the compute IS being spent), do not consume an attempt, and let the
    // next pulse resume the SAME job. Failing it here and retrying under a new
    // attempt number is exactly how a timeout buys a duplicate render.
    if (repairProvider === "self_hosted" && (err as { isLocalTimeout?: boolean })?.isLocalTimeout === true) {
      entry.state = "queued";
      await d
        .update(reelJobs)
        .set({ status: "repair_queued", queueState: queueStateForReelStatus("repair_queued"), payload: JSON.stringify(payload), updatedAt: new Date() })
        .where(eq(reelJobs.id, job.id));
      log.info("self-hosted repair still rendering — resume same Video Forge job next pulse", { jobId: job.id, beat: entry.beatNumber });
      return { processed: true, jobId: job.id, status: "repair_queued" };
    }
    await failReservation(reservationId);
    attempt.error = err instanceof Error ? err.message.slice(0, 300) : String(err);
    entry.attempts.push(attempt);
    const exhausted = attemptNumber >= MAX_PROVIDER_ATTEMPTS;
    entry.state = exhausted ? "failed" : "queued";
    await d
      .update(reelJobs)
      .set({ status: exhausted ? "repair_failed" : "repair_queued", queueState: queueStateForReelStatus(exhausted ? "repair_failed" : "repair_queued"), payload: JSON.stringify(payload), error: attempt.error })
      .where(eq(reelJobs.id, job.id));
    log.warn("repair provider attempt failed", { jobId: job.id, attempt: attemptNumber, exhausted });
    return { processed: true, jobId: job.id, status: exhausted ? "repair_failed" : "repair_queued", error: attempt.error };
  }
}
