/**
 * NickGPT corpus export · operator SMS reply pairs → JSONL for fine-tuning
 *
 * Walks sms_messages chronologically and pairs each INBOUND with its
 * next-OUTBOUND-within-2h within the same conversation. The result is a
 * training dataset of "customer → operator-style reply" pairs.
 *
 * Heuristic filters applied:
 * - Drop outbound messages with automation hallmarks (campaign-template
 *   length, automation footers, drip-style sign-offs).
 * - Drop messages with PII (names, addresses, links) per rough patterns;
 *   conservative filter — better to lose a row than train on PII.
 * - Drop very short replies (<20 chars) — likely "ok"/"thanks"/"yes" that
 *   teach nothing about operator voice.
 * - Drop very long replies (>800 chars) — likely policy text or auto-form.
 *
 * Output: `data/training/nickgpt-corpus-YYYYMMDD.jsonl` · one JSON object
 * per line · format compatible with HuggingFace TRL SFTTrainer + most
 * LoRA frameworks:
 *
 *   { "messages": [
 *       { "role": "system", "content": "You are Nick, owner of..." },
 *       { "role": "user", "content": "<customer inbound>" },
 *       { "role": "assistant", "content": "<operator reply>" }
 *     ] }
 *
 * Usage:
 *   pnpm tsx scripts/export-sms-corpus.ts                       # default · last 365d
 *   pnpm tsx scripts/export-sms-corpus.ts --days 180             # custom window
 *   pnpm tsx scripts/export-sms-corpus.ts --min-pairs 500        # bail out if too few
 *   pnpm tsx scripts/export-sms-corpus.ts --output custom.jsonl  # custom output path
 *   pnpm tsx scripts/export-sms-corpus.ts --redact-aggressive    # also redact first names
 *
 * Companion · docs/runbooks/nickgpt-finetune.md (the full LoRA pipeline).
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { NICK_SMS_SYSTEM_PROMPT as SYSTEM_PROMPT } from "../server/services/nickSmsPersona";

interface CliArgs {
  days: number;
  minPairs: number;
  output: string;
  redactAggressive: boolean;
  pairWindowMs: number;
  dryRun: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const args: CliArgs = {
    days: 365,
    minPairs: 200,
    output: `data/training/nickgpt-corpus-${today}.jsonl`,
    redactAggressive: false,
    pairWindowMs: 2 * 60 * 60 * 1000, // 2h
    dryRun: false,
  };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--days") args.days = Number(argv[++i]);
    else if (a === "--min-pairs") args.minPairs = Number(argv[++i]);
    else if (a === "--output") args.output = argv[++i];
    else if (a === "--redact-aggressive") args.redactAggressive = true;
    else if (a === "--pair-window-hours") args.pairWindowMs = Number(argv[++i]) * 60 * 60 * 1000;
    else if (a === "--dry-run") args.dryRun = true;
    else if (a === "--help" || a === "-h") {
      console.log(`usage: pnpm tsx scripts/export-sms-corpus.ts [options]
  --days N                last N days of conversations (default 365)
  --min-pairs N           bail if fewer than N pairs survive (default 200)
  --output PATH           output JSONL path (default data/training/...)
  --redact-aggressive     also redact first-name patterns
  --pair-window-hours N   max gap between inbound and reply (default 2)
  --dry-run               compute stats, don't write file`);
      process.exit(0);
    }
  }
  return args;
}

// ─── PII redaction (conservative) ──────────────────────
const PHONE_RE = /\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b/g;
const EMAIL_RE = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi;
const URL_RE = /\bhttps?:\/\/\S+\b/gi;
// US street addresses (rough): "123 Main St" or "456 Oak Ave"
const ADDR_RE = /\b\d{1,5}\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3}\s+(?:St|Street|Ave|Avenue|Rd|Road|Dr|Drive|Blvd|Ln|Lane|Ct|Way)\b/g;
// Common first-name pattern — capitalized + followed by " has", " is", " was"
const FIRST_NAME_AGGRESSIVE_RE = /\b[A-Z][a-z]{2,12}\b/g;
// Plates: 7 chars alphanumeric is too false-positive · skip
// SSN/CC pattern bans · per scripts/lint-pii.mjs · we apply same patterns
const CC_RE = /\b(?:\d[ -]*?){13,19}\b/g;
const SSN_RE = /\b\d{3}-\d{2}-\d{4}\b/g;

function redact(body: string, aggressive: boolean): string {
  let out = body;
  out = out.replace(PHONE_RE, "<PHONE>");
  out = out.replace(EMAIL_RE, "<EMAIL>");
  out = out.replace(URL_RE, "<URL>");
  out = out.replace(ADDR_RE, "<ADDRESS>");
  out = out.replace(CC_RE, "<CC>");
  out = out.replace(SSN_RE, "<SSN>");
  if (aggressive) out = out.replace(FIRST_NAME_AGGRESSIVE_RE, "<NAME>");
  return out;
}

// ─── Automation reply detectors ────────────────────────
// Outbound messages with any of these markers were generated by a
// campaign / drip / template — not by operator hand. We drop them.
const AUTOMATION_MARKERS = [
  /reply STOP to opt out/i,
  /to unsubscribe/i,
  /this is an automated/i,
  /\bnick'?s tire & auto\b.*\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b.*\bhttp/i, // full footer signature
  /We're excited to see you on/i, // booking confirmation template
  /quick reminder.*appointment/i, // 24h/2h reminder template
  /thank you for choosing nick'?s/i, // thank-you template
  /how was your visit/i, // review-request template
  /it's been (?:60|90|180|365|45) days/i, // retention template
  /your tires are due/i, // predictive maintenance
  /book now:/i, // CTA template
];

function looksAutomated(body: string): boolean {
  return AUTOMATION_MARKERS.some((re) => re.test(body));
}

// ─── System prompt for fine-tuning ─────────────────────
// SYSTEM_PROMPT is imported at the top from the shared SSOT (nickSmsPersona) so
// training data matches serving — the used-tire price and wording can no longer
// drift (this file previously hardcoded "used tires from $60", contradicting the
// BUSINESS SSOT the live drafter uses).

interface SmsRow {
  id: number;
  conversationId: number;
  direction: "inbound" | "outbound";
  body: string;
  createdAt: Date;
}

interface TrainingPair {
  inbound: string;
  reply: string;
  conversationId: number;
  inboundAt: string;
  replyAt: string;
}

async function fetchMessages(days: number): Promise<SmsRow[]> {
  // Lazy DB import so the script can `--help` without DB env vars set
  const { getDb } = await import("../server/db");
  const { smsMessages } = await import("../drizzle/schema");
  const { gte, sql } = await import("drizzle-orm");
  const db = await getDb();
  if (!db) throw new Error("Database connection not available");

  const cutoff = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const rows = await db
    .select({
      id: smsMessages.id,
      conversationId: smsMessages.conversationId,
      direction: smsMessages.direction,
      body: smsMessages.body,
      createdAt: smsMessages.createdAt,
    })
    .from(smsMessages)
    .where(gte(smsMessages.createdAt, cutoff))
    .orderBy(sql`${smsMessages.conversationId} ASC, ${smsMessages.createdAt} ASC`);

  return rows as SmsRow[];
}

function pairMessages(rows: SmsRow[], windowMs: number): TrainingPair[] {
  const pairs: TrainingPair[] = [];
  // Group by conversation, then walk chronologically
  const byConvo = new Map<number, SmsRow[]>();
  for (const r of rows) {
    if (!byConvo.has(r.conversationId)) byConvo.set(r.conversationId, []);
    byConvo.get(r.conversationId)!.push(r);
  }
  for (const convoRows of byConvo.values()) {
    for (let i = 0; i < convoRows.length; i++) {
      const cur = convoRows[i];
      if (cur.direction !== "inbound") continue;
      // Find next outbound within window
      const next = convoRows
        .slice(i + 1)
        .find((r) => r.direction === "outbound" && r.createdAt.getTime() - cur.createdAt.getTime() <= windowMs);
      if (!next) continue;
      pairs.push({
        inbound: cur.body,
        reply: next.body,
        conversationId: cur.conversationId,
        inboundAt: cur.createdAt.toISOString(),
        replyAt: next.createdAt.toISOString(),
      });
    }
  }
  return pairs;
}

function filterAndRedact(pairs: TrainingPair[], aggressive: boolean): TrainingPair[] {
  return pairs
    .filter((p) => p.reply.length >= 20 && p.reply.length <= 800)
    .filter((p) => p.inbound.length >= 3 && p.inbound.length <= 800)
    .filter((p) => !looksAutomated(p.reply))
    .map((p) => ({
      ...p,
      inbound: redact(p.inbound, aggressive),
      reply: redact(p.reply, aggressive),
    }));
}

function toJsonl(pairs: TrainingPair[]): string {
  const lines: string[] = [];
  for (const p of pairs) {
    const obj = {
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: p.inbound },
        { role: "assistant", content: p.reply },
      ],
      // Provenance · helpful for spot-checking during eval
      _meta: {
        conversationId: p.conversationId,
        inboundAt: p.inboundAt,
        replyAt: p.replyAt,
      },
    };
    lines.push(JSON.stringify(obj));
  }
  return lines.join("\n") + "\n";
}

async function main() {
  const args = parseArgs(process.argv);
  console.log(`[export-sms-corpus] window=${args.days}d · pair-window=${args.pairWindowMs / 1000 / 60}min · output=${args.output}`);

  const rows = await fetchMessages(args.days);
  console.log(`[export-sms-corpus] fetched ${rows.length} messages`);

  const rawPairs = pairMessages(rows, args.pairWindowMs);
  console.log(`[export-sms-corpus] raw pairs: ${rawPairs.length}`);

  const filtered = filterAndRedact(rawPairs, args.redactAggressive);
  console.log(`[export-sms-corpus] after filter + redact: ${filtered.length}`);
  console.log(`[export-sms-corpus] drop reasons: too-short/long, automation footers, PII redacted in body`);

  if (filtered.length < args.minPairs) {
    console.error(`[export-sms-corpus] ERROR · only ${filtered.length} pairs survived (min ${args.minPairs}). Aborting · widen --days or lower --min-pairs.`);
    process.exit(1);
  }

  // Histogram of reply length for sanity-check
  const lengths = filtered.map((p) => p.reply.length).sort((a, b) => a - b);
  const p50 = lengths[Math.floor(lengths.length * 0.5)];
  const p95 = lengths[Math.floor(lengths.length * 0.95)];
  console.log(`[export-sms-corpus] reply length p50=${p50} chars · p95=${p95} chars`);

  if (args.dryRun) {
    console.log(`[export-sms-corpus] --dry-run · skipping write`);
    return;
  }

  const outPath = resolve(args.output);
  const outDir = dirname(outPath);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, toJsonl(filtered), "utf8");

  console.log(`[export-sms-corpus] ✓ wrote ${filtered.length} pairs to ${outPath}`);
  console.log(`[export-sms-corpus] next step · docs/runbooks/nickgpt-finetune.md (LoRA on Modal/Replicate)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
