-- 2026-09-15 · action_attempts: the durable delegation contract (NICK-TRUST-ARCHITECTURE-V2 §6.5).
-- Additive only: one new table + three indexes. Generated by `prisma migrate diff` between the
-- pre-change schema and this one; hand-applied to prod Neon with scripts/apply-pending-migration.ts
-- and recorded with `prisma migrate resolve --applied`.

-- CreateTable
-- CreateTable
CREATE TABLE "action_attempts" (
    "id" TEXT NOT NULL,
    "operation_key" VARCHAR(190) NOT NULL,
    "tool" VARCHAR(80) NOT NULL,
    "effect_class" VARCHAR(16) NOT NULL DEFAULT 'unknown',
    "arguments_hash" VARCHAR(64) NOT NULL,
    "state" VARCHAR(24) NOT NULL,
    "attempt_no" INTEGER NOT NULL DEFAULT 1,
    "authority_grant_id" VARCHAR(120),
    "input_evidence_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "external_reference" VARCHAR(200),
    "receipt_id" VARCHAR(120),
    "reason" VARCHAR(500),
    "hold_until" TIMESTAMP(3),
    "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "settled_at" TIMESTAMP(3),
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "action_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "action_attempts_operation_key_key" ON "action_attempts"("operation_key");

-- CreateIndex
CREATE INDEX "action_attempts_tool_state_idx" ON "action_attempts"("tool", "state");

-- CreateIndex
CREATE INDEX "action_attempts_started_at_idx" ON "action_attempts"("started_at");

