-- 20260806120000_drop_duplicate_indexes
--
-- Drops 42 duplicate indexes across 24 tables (~18.7 MB). Every statement is
-- idempotent (IF EXISTS) and safe to re-run.
--
-- ── WHY THESE EXIST ──────────────────────────────────────────────────────
--
-- Two migrations created the same indexes under two different naming
-- conventions:
--
--   20260429170000_chat_message_batch_a  · hand-written · snake_case names
--                                          (matching the DB column names)
--   20260507103256_add_missing_indexes_v10_0_381
--                                        · "Generated by
--                                          scripts/emit-index-migration.ts"
--                                        · camelCase names (Prisma FIELD names)
--
-- The generator built the index NAME from Prisma field names while building
-- the index BODY from the @map'd DB column names, so it emitted e.g.
--
--     CREATE INDEX IF NOT EXISTS "Mission_deletedAt_idx" ON "Mission" ("deleted_at");
--
-- against an existing "Mission_deleted_at_idx". `IF NOT EXISTS` matches on
-- NAME, so the guard could not see the twin and created a SECOND, byte-
-- identical index instead of no-opping. Same story 42 times.
--
-- The generator bug is fixed in the same PR as this migration
-- (scripts/emit-index-migration.ts · indexNameOf now maps columns), so
-- re-running it against the post-cleanup DB is genuinely idempotent and will
-- NOT recreate these.
--
-- ── WHY THIS IS SAFE ─────────────────────────────────────────────────────
--
-- Each dropped index has a byte-identical twin that remains: same table, same
-- column list, same order, non-unique, no partial predicate (verified via
-- pg_index — the duplicate set was computed by grouping on
-- (table, column-list) with indisprimary=false, indisunique=false and
-- indpred IS NULL, so no constraint-backing or partial index is touched).
--
-- Several of the dropped names carry HIGH scan counts — e.g.
-- brain_memories_category_deletedAt_idx at 221,640 scans. That is not
-- evidence they are needed: with two identical indexes the planner picks one
-- arbitrarily and the scans split between them. After the drop those scans
-- land on the surviving twin and the plan is unchanged.
--
-- Net effect: same query plans, half the B-tree maintenance on every INSERT
-- and UPDATE to these 24 tables, ~18.7 MB reclaimed.
--
-- ── ROLLBACK ─────────────────────────────────────────────────────────────
--
-- Fully reversible. To restore any dropped index, recreate it from its
-- surviving twin's definition:
--
--     SELECT indexdef FROM pg_indexes
--      WHERE schemaname='public' AND indexname='<the_snake_case_twin>';
--
-- then re-run that statement with the camelCase name substituted. No data is
-- touched by this migration — indexes only.
--
-- ── LOCKING ──────────────────────────────────────────────────────────────
--
-- Plain DROP INDEX takes a brief ACCESS EXCLUSIVE lock on the parent table.
-- On this dataset that is milliseconds per statement. If you would rather
-- take zero lock, run each statement as
-- `DROP INDEX CONCURRENTLY IF EXISTS ...` instead — but note CONCURRENTLY
-- cannot run inside a transaction block, so it must not go through a
-- transactional apply path.

-- ── brain_memories (5 duplicates · 8.9 MB) ──
DROP INDEX IF EXISTS "brain_memories_category_updatedAt_idx";
DROP INDEX IF EXISTS "brain_memories_category_createdAt_idx";
DROP INDEX IF EXISTS "brain_memories_category_deletedAt_idx";
DROP INDEX IF EXISTS "brain_memories_lastSeen_idx";
DROP INDEX IF EXISTS "brain_memories_expiresAt_idx";

-- ── api_request_logs (1 · 3.5 MB) ──
DROP INDEX IF EXISTS "api_request_logs_statusCode_createdAt_idx";

-- ── agent_traces (3 · 3.0 MB) ──
DROP INDEX IF EXISTS "agent_traces_errorClass_createdAt_idx";
DROP INDEX IF EXISTS "agent_traces_source_createdAt_idx";
DROP INDEX IF EXISTS "agent_traces_provider_createdAt_idx";

-- ── automation_policy_fires (1 · 1.1 MB) ──
DROP INDEX IF EXISTS "automation_policy_fires_firedAt_idx";

-- ── system_metrics (2 · 712 kB) ──
DROP INDEX IF EXISTS "system_metrics_source_createdAt_idx";
DROP INDEX IF EXISTS "system_metrics_createdAt_idx";

-- ── chat_messages (5 · 680 kB) ──
DROP INDEX IF EXISTS "chat_messages_parentMessageId_idx";
DROP INDEX IF EXISTS "chat_messages_conversationId_branchId_idx";
DROP INDEX IF EXISTS "chat_messages_streamingState_createdAt_idx";
DROP INDEX IF EXISTS "chat_messages_provider_createdAt_idx";
DROP INDEX IF EXISTS "chat_messages_feedbackScore_idx";

-- ── ai_generations (2 · 432 kB) ──
DROP INDEX IF EXISTS "ai_generations_model_createdAt_idx";
DROP INDEX IF EXISTS "ai_generations_status_createdAt_idx";

-- ── entity_audits (3 · 248 kB) ──
DROP INDEX IF EXISTS "entity_audits_actor_createdAt_idx";
DROP INDEX IF EXISTS "entity_audits_action_createdAt_idx";
DROP INDEX IF EXISTS "entity_audits_createdAt_idx";

-- ── brain_bus_events (1 · 136 kB) ──
DROP INDEX IF EXISTS "brain_bus_events_topic_createdAt_idx";

-- ── memory_edges (1 · 64 kB) ──
DROP INDEX IF EXISTS "memory_edges_targetType_targetId_idx";

-- ── brain_dumps (2 · 64 kB) ──
DROP INDEX IF EXISTS "brain_dumps_date_actionsTaken_idx";
DROP INDEX IF EXISTS "brain_dumps_deletedAt_idx";

-- ── task_events (1 · 40 kB) ──
DROP INDEX IF EXISTS "task_events_kind_createdAt_idx";

-- ── remaining single duplicates (16 kB each) ──
DROP INDEX IF EXISTS "Task_deletedAt_idx";
DROP INDEX IF EXISTS "Mission_deletedAt_idx";
DROP INDEX IF EXISTS "commitments_deletedAt_idx";
DROP INDEX IF EXISTS "goal_events_kind_createdAt_idx";
DROP INDEX IF EXISTS "identity_snapshots_deletedAt_idx";
DROP INDEX IF EXISTS "life_goals_deletedAt_idx";
DROP INDEX IF EXISTS "mastery_decisions_deletedAt_idx";
DROP INDEX IF EXISTS "mastery_decisions_reviewDate_idx";
DROP INDEX IF EXISTS "chat_conversations_starredAt_idx";
DROP INDEX IF EXISTS "chat_conversations_missionId_idx";
DROP INDEX IF EXISTS "person_profiles_trustScore_idx";
DROP INDEX IF EXISTS "reflections_deletedAt_idx";
DROP INDEX IF EXISTS "device_commands_status_createdAt_idx";
DROP INDEX IF EXISTS "schema_change_ledger_environment_appliedAt_idx";
DROP INDEX IF EXISTS "scheduled_actions_entityType_entityId_idx";

-- ── VERIFY AFTER APPLYING ────────────────────────────────────────────────
--
-- This must return ZERO rows:
--
--   WITH idx AS (
--     SELECT t.relname AS tbl, i.relname AS idx_name,
--            array_to_string(array_agg(a.attname ORDER BY k.ord), ',') AS cols
--       FROM pg_index ix
--       JOIN pg_class i ON i.oid = ix.indexrelid
--       JOIN pg_class t ON t.oid = ix.indrelid
--       JOIN pg_namespace n ON n.oid = t.relnamespace
--       JOIN LATERAL unnest(ix.indkey) WITH ORDINALITY AS k(attnum, ord) ON true
--       JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = k.attnum
--      WHERE n.nspname = 'public'
--        AND NOT ix.indisprimary AND NOT ix.indisunique AND ix.indpred IS NULL
--      GROUP BY t.relname, i.relname
--   )
--   SELECT tbl, cols, count(*) FROM idx GROUP BY tbl, cols HAVING count(*) > 1;
