/**
 * Intersection data for /near/[slug] SEO pages.
 * Each page targets "auto repair near [intersection]" queries.
 * 75+ pages covering Euclid, Cleveland, Wickliffe, South Euclid,
 * Richmond Heights, East Cleveland, Collinwood, Glenville, Slavic Village,
 * Tremont, Old Brooklyn, Beachwood, Solon, Eastlake, Chardon, and Painesville.
 */

export interface IntersectionData {
  slug: string;
  name: string;
  lat: number;
  lng: number;
  zip: string;
  driveMinutes: number;
  neighborhood?: string;
  landmark?: string;
  localContent: string;
}

export const INTERSECTIONS: IntersectionData[] = [
  // ─── EUCLID (closest) ───────────────────────────
  { slug: "euclid-ave-e-222nd", name: "Euclid Ave & E 222nd St", lat: 41.5834, lng: -81.5168, zip: "44123", driveMinutes: 2, neighborhood: "Euclid", localContent: "Just two minutes from our shop on Euclid Avenue. If you're near the E 222nd corridor — whether heading to Shore Cultural Centre or grabbing lunch — we're the closest full-service auto shop. Pull in for a flat repair ($25) or schedule your next oil change." },
  { slug: "euclid-ave-e-200th", name: "Euclid Ave & E 200th St", lat: 41.5856, lng: -81.5335, zip: "44119", driveMinutes: 5, neighborhood: "Euclid", localContent: "Five minutes east on Euclid Avenue puts you right at our door. The E 200th St intersection sees heavy traffic, and Cleveland's potholes don't help. If your alignment feels off or you're hearing grinding when you brake, don't wait — drive straight to us at 17625 Euclid Ave." },
  { slug: "euclid-ave-chardon-rd", name: "Euclid Ave & Chardon Rd", lat: 41.5815, lng: -81.5094, zip: "44117", driveMinutes: 4, neighborhood: "Euclid", localContent: "The Euclid Ave and Chardon Road intersection is one of the busiest in Euclid. If your check engine light came on while driving through, we're less than 4 minutes away. Our OBD-II diagnostics start at $49 — we find the real problem, not guess." },
  { slug: "lakeshore-blvd-e-222nd", name: "Lakeshore Blvd & E 222nd St", lat: 41.5903, lng: -81.5165, zip: "44123", driveMinutes: 3, neighborhood: "Shore area", landmark: "Near Sims Park", localContent: "Coming from the Lakeshore Boulevard area near Sims Park? We're just 3 minutes south. The lake-effect salt destroys undercarriages and brake lines — get a free inspection before winter damage becomes a safety issue." },
  { slug: "babbitt-rd-euclid-ave", name: "Babbitt Rd & Euclid Ave", lat: 41.5842, lng: -81.5255, zip: "44123", driveMinutes: 2, neighborhood: "Euclid", localContent: "The Babbitt Road corridor in Euclid is home turf. Our shop at 17625 Euclid Ave is literally around the corner. Walk-ins welcome 7 days a week for tire repairs, oil changes, and brake checks." },

  // ─── I-90 / HIGHWAY ACCESS ──────────────────────
  { slug: "i-90-euclid-ave", name: "I-90 & Euclid Ave Exit", lat: 41.5790, lng: -81.5200, zip: "44123", driveMinutes: 3, neighborhood: "Euclid", localContent: "Just got off I-90 at the Euclid Ave exit? We're 3 minutes east. If you blew a tire on the highway or your car is overheating, pull off and head to 17625 Euclid Ave. We handle emergency repairs same-day." },
  { slug: "i-90-e-185th", name: "I-90 & E 185th St Exit", lat: 41.5811, lng: -81.5489, zip: "44119", driveMinutes: 8, neighborhood: "Collinwood", localContent: "Taking the E 185th St exit off I-90? Head east on Euclid Avenue for about 8 minutes. Worth the drive — our 4.9-star rating and 1,700+ reviews aren't an accident. Honest diagnostics, fair prices, no surprises." },
  { slug: "i-271-euclid-ave", name: "I-271 & Euclid Ave", lat: 41.5760, lng: -81.4880, zip: "44117", driveMinutes: 7, neighborhood: "Wickliffe", localContent: "Coming off I-271 near Wickliffe? Take Euclid Ave west for 7 minutes to reach Nick's Tire & Auto. We serve drivers from all over the East Side — Wickliffe, Willoughby, Mentor. Used tires from $60, brakes from $89." },

  // ─── WICKLIFFE / WILLOUGHBY ─────────────────────
  { slug: "euclid-ave-lloyd-rd", name: "Euclid Ave & Lloyd Rd", lat: 41.5848, lng: -81.4727, zip: "44092", driveMinutes: 10, neighborhood: "Wickliffe", localContent: "Wickliffe drivers at the Lloyd Road intersection are just 10 minutes from honest auto repair. We've been the go-to shop for Wickliffe families since 2018. Free estimates on all repairs — call (216) 862-0005 or just pull in." },
  { slug: "vine-st-euclid-ave-wickliffe", name: "Vine St & Euclid Ave (Wickliffe)", lat: 41.5860, lng: -81.4800, zip: "44092", driveMinutes: 9, neighborhood: "Wickliffe", localContent: "Near Vine St in Wickliffe? Nick's Tire & Auto is a quick 9-minute drive west on Euclid. Our customers from Wickliffe say the drive is worth it for the pricing and honesty. Flat repair $25, oil change from $39." },

  // ─── SOUTH EUCLID / LYNDHURST ───────────────────
  { slug: "mayfield-rd-green-rd", name: "Mayfield Rd & Green Rd", lat: 41.5190, lng: -81.5270, zip: "44121", driveMinutes: 12, neighborhood: "South Euclid", localContent: "South Euclid drivers near the Mayfield and Green Road intersection — we're 12 minutes north on surface streets. Nick's Tire & Auto has been serving South Euclid residents who want transparent auto repair without dealership prices." },
  { slug: "cedar-rd-green-rd", name: "Cedar Rd & Green Rd", lat: 41.5000, lng: -81.5270, zip: "44121", driveMinutes: 15, neighborhood: "South Euclid", landmark: "Near Notre Dame College", localContent: "Near Notre Dame College at Cedar and Green? Our shop is 15 minutes north. College students and South Euclid families trust us for affordable tire replacements and brake work. We offer $10 down financing on all services." },

  // ─── EAST CLEVELAND ─────────────────────────────
  { slug: "euclid-ave-e-105th", name: "Euclid Ave & E 105th St", lat: 41.5148, lng: -81.6000, zip: "44106", driveMinutes: 15, neighborhood: "East Cleveland", landmark: "Near Cleveland Clinic", localContent: "Working near Cleveland Clinic at E 105th? Head east on Euclid Ave for 15 minutes to reach an honest auto shop. We show you the problem before we fix it — that's why we have 1,700+ five-star reviews." },
  { slug: "superior-ave-e-140th", name: "Superior Ave & E 140th St", lat: 41.5400, lng: -81.5800, zip: "44112", driveMinutes: 10, neighborhood: "East Cleveland", localContent: "From the Superior Ave corridor in East Cleveland, we're just 10 minutes east. Nick's Tire & Auto is the highest-rated independent shop on this side of town. Walk-ins welcome, no appointment needed for most services." },

  // ─── COLLINWOOD / NOTTINGHAM ────────────────────
  { slug: "lakeshore-blvd-e-185th", name: "Lakeshore Blvd & E 185th St", lat: 41.5911, lng: -81.5489, zip: "44119", driveMinutes: 8, neighborhood: "Collinwood", localContent: "The Collinwood neighborhood deserves a trustworthy mechanic. From the Lakeshore and E 185th area, we're 8 minutes east. We specialize in the kind of repairs Cleveland roads demand — suspension, alignment, and tire work." },
  { slug: "st-clair-ave-e-152nd", name: "St Clair Ave & E 152nd St", lat: 41.5712, lng: -81.5712, zip: "44110", driveMinutes: 12, neighborhood: "Collinwood", localContent: "Collinwood residents at St Clair and E 152nd — drive 12 minutes east on Euclid Ave for auto repair you can trust. Our technicians are ASE-certified and we back all labor with a 36-month warranty." },
  { slug: "nottingham-rd-st-clair", name: "Nottingham Rd & St Clair Ave", lat: 41.5650, lng: -81.5550, zip: "44110", driveMinutes: 13, neighborhood: "Nottingham", localContent: "The Nottingham neighborhood has limited auto repair options. Nick's Tire & Auto is 13 minutes east on Euclid Ave. Our used tire selection starts at $60, and we do flat repairs for $25. No appointment needed." },

  // ─── RICHMOND HEIGHTS ───────────────────────────
  { slug: "richmond-rd-wilson-mills", name: "Richmond Rd & Wilson Mills Rd", lat: 41.5530, lng: -81.5050, zip: "44143", driveMinutes: 10, neighborhood: "Richmond Heights", localContent: "Richmond Heights residents at Richmond and Wilson Mills — we're 10 minutes west. Our customers from Richmond Heights appreciate that we explain every repair before we start. Free estimates, no pressure, 4.9-star service." },
  { slug: "chardon-rd-richmond-rd", name: "Chardon Rd & Richmond Rd", lat: 41.5500, lng: -81.5000, zip: "44143", driveMinutes: 12, neighborhood: "Richmond Heights", localContent: "Near the Chardon and Richmond Road intersection? Nick's Tire & Auto is your closest top-rated independent shop. We beat dealer pricing on brakes, tires, and diagnostics — and we actually show you what's wrong." },

  // ─── GARFIELD HEIGHTS / MAPLE HEIGHTS ───────────
  { slug: "turney-rd-granger-rd", name: "Turney Rd & Granger Rd", lat: 41.4160, lng: -81.6060, zip: "44125", driveMinutes: 22, neighborhood: "Garfield Heights", localContent: "Garfield Heights drivers make the 22-minute drive to Nick's because the savings and honesty are worth it. We've had customers switch from big chains after one visit. Used tires from $60, brakes from $89, oil changes from $39." },
  { slug: "broadway-ave-union-ave", name: "Broadway Ave & Union Ave", lat: 41.4290, lng: -81.6300, zip: "44105", driveMinutes: 20, neighborhood: "Slavic Village", localContent: "From the Broadway and Union area in Slavic Village, head east on I-490 to I-90, then take the Euclid Ave exit. About 20 minutes. Our 1,700+ Google reviews speak for themselves — honest, affordable, reliable." },
  { slug: "lee-rd-harvard-rd", name: "Lee Rd & Harvard Rd", lat: 41.4250, lng: -81.5610, zip: "44128", driveMinutes: 18, neighborhood: "Maple Heights", localContent: "Maple Heights drivers trust Nick's Tire & Auto for everything from flat repairs to full brake jobs. We're 18 minutes north on Lee Road to Euclid Ave. Walk-ins welcome 7 days a week, and we offer $10 down financing." },

  // ─── CLEVELAND HEIGHTS / UNIVERSITY HEIGHTS ─────
  { slug: "cedar-rd-lee-rd", name: "Cedar Rd & Lee Rd", lat: 41.4945, lng: -81.5610, zip: "44118", driveMinutes: 15, neighborhood: "Cleveland Heights", landmark: "Near Cedar Lee district", localContent: "Drivers from the Cedar Lee district in Cleveland Heights are 15 minutes from honest auto repair at Nick's. Our transparent diagnostics and upfront pricing have earned us the trust of Heights residents who are tired of dealer markups." },
  { slug: "mayfield-rd-coventry", name: "Mayfield Rd & Coventry Rd", lat: 41.5080, lng: -81.5800, zip: "44118", driveMinutes: 14, neighborhood: "Cleveland Heights", landmark: "Near Coventry Village", localContent: "Near Coventry Village? Head east on Mayfield to Euclid Ave — 14 minutes to Nick's Tire & Auto. We're the independent alternative to overpriced dealership service. Same quality, fair prices, 36-month labor warranty." },

  // ─── ADDITIONAL EUCLID INTERSECTIONS ────────────
  { slug: "e-260th-euclid-ave", name: "E 260th St & Euclid Ave", lat: 41.5875, lng: -81.4970, zip: "44132", driveMinutes: 5, neighborhood: "Euclid", localContent: "Near the eastern edge of Euclid at E 260th? We're 5 minutes west on Euclid Ave. The E 260th corridor near the Euclid Square Mall area is part of our backyard. Quick tire repairs, oil changes, and brake inspections — no wait." },
  { slug: "lakeland-blvd-e-222nd", name: "Lakeland Blvd & E 222nd St", lat: 41.5870, lng: -81.5170, zip: "44123", driveMinutes: 3, neighborhood: "Euclid", localContent: "The Lakeland Blvd area in Euclid is minutes from our shop. If you hit a pothole on Lakeland and need alignment or tire work, Nick's Tire & Auto is the fastest, most affordable option in the neighborhood." },
  { slug: "shore-center-dr", name: "Shore Center Dr & E 222nd", lat: 41.5890, lng: -81.5160, zip: "44123", driveMinutes: 2, neighborhood: "Euclid", landmark: "Near Shore Cultural Centre", localContent: "Visiting Shore Cultural Centre or the Euclid Public Library? We're literally 2 minutes away at 17625 Euclid Ave. Drop your car off for service while you handle errands — we'll text you when it's ready." },

  // ─── WICKLIFFE & WILLOUGHBY ──────────────────────
  { slug: "euclid-ave-e-300th", name: "Euclid Ave & E 300th St", lat: 41.5940, lng: -81.4750, zip: "44092", driveMinutes: 8, neighborhood: "Wickliffe", localContent: "Wickliffe drivers at the Euclid Ave and E 300th corridor — Nick's Tire & Auto is just 8 minutes west. We serve the entire Lake County border area with honest auto repair and used tires from $60." },
  { slug: "lakeland-blvd-lloyd-rd", name: "Lakeland Blvd & Lloyd Rd", lat: 41.5910, lng: -81.4670, zip: "44092", driveMinutes: 9, neighborhood: "Wickliffe", localContent: "Near the Wickliffe shopping district on Lakeland? We're a quick drive west on Lakeland to Euclid Ave. Bring your vehicle for brakes, tires, or oil — we'll beat any competitor's quote." },
  { slug: "vine-st-erie-st-willoughby", name: "Vine St & Erie St", lat: 41.6395, lng: -81.4067, zip: "44094", driveMinutes: 15, neighborhood: "Willoughby", localContent: "Downtown Willoughby residents choose Nick's Tire & Auto for the same reason 1,700+ reviewers gave us 4.9 stars: honest work, fair prices, and techs who actually explain what your car needs." },

  // ─── SOUTH EUCLID & LYNDHURST ────────────────────
  { slug: "mayfield-rd-green-rd", name: "Mayfield Rd & Green Rd", lat: 41.5081, lng: -81.5267, zip: "44121", driveMinutes: 12, neighborhood: "South Euclid", localContent: "South Euclid drivers near Mayfield and Green — take Green Rd north to I-271, then Euclid Ave. 12 minutes to Nick's, where we handle everything from flat repairs to engine diagnostics." },
  { slug: "cedar-rd-brainard-rd", name: "Cedar Rd & Brainard Rd", lat: 41.4933, lng: -81.4940, zip: "44124", driveMinutes: 14, neighborhood: "Lyndhurst", localContent: "Lyndhurst residents near Legacy Village — Nick's Tire & Auto is 14 minutes north. Skip the dealer, get the same quality at half the price. We warranty our labor for 36 months." },
  { slug: "monticello-blvd-warrensville", name: "Monticello Blvd & Warrensville Center Rd", lat: 41.5100, lng: -81.5340, zip: "44121", driveMinutes: 13, neighborhood: "South Euclid", localContent: "The Monticello corridor in South Euclid is 13 minutes from Nick's. We see a lot of vehicles from this area — especially for tire replacement and brake work after harsh Cleveland winters." },

  // ─── BEDFORD & MAPLE HEIGHTS ─────────────────────
  { slug: "broadway-ave-northfield-rd", name: "Broadway Ave & Northfield Rd", lat: 41.3930, lng: -81.5340, zip: "44146", driveMinutes: 20, neighborhood: "Bedford", localContent: "Bedford drivers make the trip to Nick's Tire & Auto because our prices and reviews speak for themselves. 4.9 stars, 1,700+ reviews, and used tires from $60 that are safety-inspected." },
  { slug: "lee-rd-libby-rd", name: "Lee Rd & Libby Rd", lat: 41.4150, lng: -81.5610, zip: "44137", driveMinutes: 18, neighborhood: "Maple Heights", localContent: "Maple Heights to Nick's is 18 minutes on I-480 to I-90. Worth the drive — especially for tire deals and brake work. We've been the go-to shop for Maple Heights families who want honest service." },

  // ─── GARFIELD HEIGHTS & WARRENSVILLE ─────────────
  { slug: "turney-rd-granger-rd", name: "Turney Rd & Granger Rd", lat: 41.4200, lng: -81.6060, zip: "44125", driveMinutes: 20, neighborhood: "Garfield Heights", localContent: "Garfield Heights residents drive to Nick's for one reason: trust. Our 4.9-star rating and 1,700+ reviews mean you're getting honest work at fair prices. No pressure, no upselling." },
  { slug: "warrensville-center-miles", name: "Warrensville Center Rd & Miles Ave", lat: 41.4330, lng: -81.5340, zip: "44128", driveMinutes: 17, neighborhood: "Warrensville Heights", localContent: "From Warrensville Heights, take I-480 to I-90 east — 17 minutes to Nick's Tire & Auto. We serve dozens of customers from the Warrensville area weekly, especially for tires and diagnostics." },

  // ─── RICHMOND HEIGHTS & HIGHLAND HILLS ───────────
  { slug: "richmond-rd-wilson-mills", name: "Richmond Rd & Wilson Mills Rd", lat: 41.5500, lng: -81.5060, zip: "44143", driveMinutes: 10, neighborhood: "Richmond Heights", localContent: "Richmond Heights drivers — we're just 10 minutes west on Euclid Ave. Whether you need an oil change, tire rotation, or check engine diagnostic, Nick's has you covered with same-day service." },
  { slug: "highland-rd-bishop-rd", name: "Highland Rd & Bishop Rd", lat: 41.4480, lng: -81.5250, zip: "44122", driveMinutes: 16, neighborhood: "Highland Hills", localContent: "Highland Hills to Nick's is a straight shot north. We're the neighborhood shop that treats every car like our own — because your mechanic should be someone you trust, not someone you dread visiting." },

  // ─── MENTOR & EASTLAKE ──────────────────────────
  { slug: "mentor-ave-center-st", name: "Mentor Ave & Center St", lat: 41.6660, lng: -81.3420, zip: "44060", driveMinutes: 22, neighborhood: "Mentor", localContent: "Mentor residents who've found us know: the 22-minute drive to Nick's Tire & Auto is worth it. Lower prices than lakeside chains, better work, and a 36-month warranty on labor." },
  { slug: "vine-st-lake-shore-eastlake", name: "Vine St & Lake Shore Blvd", lat: 41.6530, lng: -81.4330, zip: "44095", driveMinutes: 16, neighborhood: "Eastlake", localContent: "Eastlake drivers head south to Nick's for quality tires and brake work. We carry all major tire brands plus quality used tires starting at $60 — inspected and guaranteed." },

  // ─── UNIVERSITY HEIGHTS & SHAKER ─────────────────
  { slug: "cedar-rd-warrensville", name: "Cedar Rd & Warrensville Center Rd", lat: 41.4940, lng: -81.5340, zip: "44122", driveMinutes: 15, neighborhood: "University Heights", localContent: "University Heights and Shaker Heights residents make the drive to Nick's because dealership prices are brutal. We do the same work, same quality parts, at half the price. 36-month labor warranty." },
  { slug: "chagrin-blvd-lee-rd", name: "Chagrin Blvd & Lee Rd", lat: 41.4750, lng: -81.5610, zip: "44120", driveMinutes: 17, neighborhood: "Shaker Heights", localContent: "Shaker Heights drivers near Chagrin Blvd — Nick's Tire & Auto is 17 minutes north. Our transparent pricing and 4.9-star reputation have earned loyal customers from every Cleveland neighborhood." },

  // ─── ADDITIONAL CLEVELAND NEIGHBORHOODS ──────────
  { slug: "superior-ave-e-55th", name: "Superior Ave & E 55th St", lat: 41.5190, lng: -81.6440, zip: "44103", driveMinutes: 18, neighborhood: "Cleveland", landmark: "Near St. Clair-Superior", localContent: "From the St. Clair-Superior neighborhood, take Superior east to Euclid Ave. 18 minutes to a shop that treats you right. Walk-ins welcome, no appointment needed." },
  { slug: "detroit-ave-w-65th", name: "Detroit Ave & W 65th St", lat: 41.4840, lng: -81.7080, zip: "44102", driveMinutes: 22, neighborhood: "Cleveland", landmark: "Near Gordon Square", localContent: "West siders from Gordon Square and Detroit Shoreway — yes, it's a drive across town. But 1,700+ Google reviews at 4.9 stars don't lie. Nick's Tire & Auto is worth the trip." },
  { slug: "miles-ave-e-131st", name: "Miles Ave & E 131st St", lat: 41.4380, lng: -81.5870, zip: "44105", driveMinutes: 15, neighborhood: "Cleveland", landmark: "Near Mt. Pleasant", localContent: "Mt. Pleasant and Miles Ave residents — we're 15 minutes north on I-77 to I-90. Fast service, honest pricing, and we specialize in the tire and brake work Cleveland roads demand." },
  { slug: "kinsman-rd-e-116th", name: "Kinsman Rd & E 116th St", lat: 41.4630, lng: -81.6020, zip: "44104", driveMinutes: 16, neighborhood: "Cleveland", localContent: "The Kinsman neighborhood to Nick's is a quick hop north. We believe every Cleveland neighborhood deserves access to honest, affordable auto repair. That's our mission." },
  { slug: "lorain-ave-w-117th", name: "Lorain Ave & W 117th St", lat: 41.4720, lng: -81.7530, zip: "44111", driveMinutes: 25, neighborhood: "Cleveland", landmark: "Near West Park", localContent: "West Park residents — yes, we're on the east side. But our prices, quality, and 4.9-star reputation draw customers from every corner of Greater Cleveland. Try us once." },

  // ─── COLLINWOOD (EXPANDED) ─────────────────────
  { slug: "waterloo-rd-e-156th", name: "Waterloo Rd & E 156th St", lat: 41.5745, lng: -81.5680, zip: "44110", driveMinutes: 10, neighborhood: "Collinwood", landmark: "Waterloo Arts District", localContent: "Right in the heart of the Waterloo Arts District — if you're grabbing coffee on Waterloo Road or hitting up one of the galleries, our shop is a straight 10-minute shot east on Euclid Ave. Collinwood's older vehicles take a beating on these streets, and we specialize in the suspension and brake work they need." },
  { slug: "e-152nd-st-clair-collinwood", name: "E 152nd St & St Clair Ave", lat: 41.5720, lng: -81.5700, zip: "44110", driveMinutes: 10, neighborhood: "Collinwood", localContent: "The E 152nd corridor in Collinwood is blue-collar territory — we get it, because that's who we are too. Lots of older trucks and work vehicles rolling through here that need honest maintenance, not upsells. Ten minutes east on Euclid Ave and you're at our door." },
  { slug: "e-152nd-ivanhoe-rd", name: "E 152nd St & Ivanhoe Rd", lat: 41.5680, lng: -81.5700, zip: "44110", driveMinutes: 11, neighborhood: "Collinwood", localContent: "Collinwood residents near Ivanhoe — the potholes on these side streets eat tires and destroy alignment. We fix both, fast and affordable. Nick's Tire & Auto is 11 minutes east, and we carry used tires from $60 so you're not broke after one bad pothole." },

  // ─── GLENVILLE ─────────────────────────────────
  { slug: "e-105th-superior-glenville", name: "E 105th St & Superior Ave", lat: 41.5280, lng: -81.6100, zip: "44106", driveMinutes: 15, neighborhood: "Glenville", landmark: "Near University Circle", localContent: "Glenville residents near E 105th and Superior — you're close to University Circle but far from affordable auto repair options. Nick's Tire & Auto is 15 minutes east on Euclid Ave. We do honest work at honest prices, and our 4.9-star rating proves it." },
  { slug: "e-105th-st-clair-glenville", name: "E 105th St & St Clair Ave", lat: 41.5350, lng: -81.6100, zip: "44108", driveMinutes: 15, neighborhood: "Glenville", localContent: "From the St Clair corridor in Glenville, head east on St Clair to Euclid Ave — about 15 minutes to a mechanic who treats you right. Cleveland's freeze-thaw cycle destroys brake lines and rusts out exhaust systems. Catch it early before it becomes a safety issue." },
  { slug: "parkwood-dr-e-105th", name: "Parkwood Dr & E 105th St", lat: 41.5310, lng: -81.6070, zip: "44108", driveMinutes: 16, neighborhood: "Glenville", localContent: "Glenville families near Parkwood and E 105th — we know reliable transportation isn't optional, it's everything. That's why we offer $10 down financing on all repairs. Drive 16 minutes east to Nick's and let us keep your car safe on the road." },

  // ─── SLAVIC VILLAGE (EXPANDED) ─────────────────
  { slug: "fleet-ave-e-55th", name: "Fleet Ave & E 55th St", lat: 41.4550, lng: -81.6380, zip: "44105", driveMinutes: 20, neighborhood: "Slavic Village", localContent: "Slavic Village is a neighborhood built by working families — and working families need a mechanic who won't rip them off. From Fleet Ave and E 55th, take I-77 north to I-90 east. Twenty minutes to Nick's, where used tires start at $60 and brake jobs at $89." },
  { slug: "broadway-fleet-ave", name: "Broadway Ave & Fleet Ave", lat: 41.4510, lng: -81.6340, zip: "44105", driveMinutes: 20, neighborhood: "Slavic Village", localContent: "The Broadway and Fleet intersection is the heart of Slavic Village. If your car is shaking on the highway or your brakes are grinding, don't ignore it — head east to Nick's Tire & Auto. We show you the problem on the lift before we touch a wrench." },
  { slug: "e-65th-broadway-slavic", name: "E 65th St & Broadway Ave", lat: 41.4480, lng: -81.6280, zip: "44105", driveMinutes: 21, neighborhood: "Slavic Village", localContent: "Slavic Village drivers near E 65th and Broadway — salt and potholes are a way of life in this part of Cleveland. Your suspension and tires take the worst of it. Nick's is 21 minutes east, and we've built our reputation on fixing exactly these problems at prices that respect your budget." },

  // ─── TREMONT ───────────────────────────────────
  { slug: "professor-ave-w-14th", name: "Professor Ave & W 14th St", lat: 41.4750, lng: -81.6880, zip: "44113", driveMinutes: 22, neighborhood: "Tremont", landmark: "Near Lincoln Park", localContent: "Tremont has gotten trendy, but cars still break down. From Professor Ave near Lincoln Park, take I-90 east for about 22 minutes to Nick's Tire & Auto. We're the opposite of trendy — just honest mechanics doing solid work at fair prices since 2018." },
  { slug: "w-25th-abbey-ave", name: "W 25th St & Abbey Ave", lat: 41.4720, lng: -81.6920, zip: "44113", driveMinutes: 22, neighborhood: "Tremont", localContent: "Near the W 25th corridor in Tremont? The restaurants are great but the parking lots and side streets are brutal on tires and suspension. When you hear that clunk or feel the pull, head east on I-90 to Nick's. We diagnose free before we recommend anything." },

  // ─── OLD BROOKLYN ──────────────────────────────
  { slug: "pearl-rd-memphis-ave", name: "Pearl Rd & Memphis Ave", lat: 41.4380, lng: -81.7030, zip: "44109", driveMinutes: 25, neighborhood: "Old Brooklyn", localContent: "Old Brooklyn is full of value shoppers who know where their money goes — and that's exactly why they drive 25 minutes to Nick's Tire & Auto. We don't upsell. Oil changes from $39, brake pads from $89, and we show you the old parts so you know the work was needed." },
  { slug: "broadview-rd-schaaf-rd", name: "Broadview Rd & Schaaf Rd", lat: 41.4420, lng: -81.6970, zip: "44109", driveMinutes: 24, neighborhood: "Old Brooklyn", localContent: "Old Brooklyn drivers on the Broadview corridor — if you're tired of chain shops that find a new problem every visit, make the trip east to Nick's. Our 1,700+ five-star reviews are from real people who got tired of getting played. Working class deserves a working-class mechanic." },
  { slug: "state-rd-ridge-rd", name: "State Rd & Ridge Rd", lat: 41.4350, lng: -81.7100, zip: "44109", driveMinutes: 25, neighborhood: "Old Brooklyn", localContent: "From State and Ridge in Old Brooklyn, hop on I-480 east to I-77 north to I-90 east — 25 minutes to the most honest shop on Cleveland's east side. We carry all major tire brands plus quality used tires, and we'll never sell you something you don't need." },

  // ─── BEACHWOOD ─────────────────────────────────
  { slug: "chagrin-blvd-richmond-rd", name: "Chagrin Blvd & Richmond Rd", lat: 41.4640, lng: -81.5080, zip: "44122", driveMinutes: 15, neighborhood: "Beachwood", landmark: "Near Beachwood Place", localContent: "Beachwood residents near Beachwood Place mall — you don't have to pay dealer prices for quality auto repair. Nick's Tire & Auto is 15 minutes north, and we do the same work your dealer does at a fraction of the cost. ASE-certified techs, 36-month labor warranty." },
  { slug: "cedar-rd-i-271-beachwood", name: "Cedar Rd & I-271", lat: 41.4600, lng: -81.4950, zip: "44122", driveMinutes: 15, neighborhood: "Beachwood", localContent: "Just off I-271 in Beachwood? Take I-271 north to I-90, exit Euclid Ave — 15 minutes to Nick's. We service BMWs, Audis, and Lexuses alongside Hondas and Chevys. Every car gets the same honest treatment and transparent pricing." },

  // ─── SOLON ─────────────────────────────────────
  { slug: "som-center-rd-aurora-rd", name: "SOM Center Rd & Aurora Rd", lat: 41.3890, lng: -81.4410, zip: "44139", driveMinutes: 20, neighborhood: "Solon", localContent: "Solon families with multiple vehicles in the driveway — we get it, maintenance adds up fast. That's why Nick's Tire & Auto offers pricing that makes sense for families. Twenty minutes north on SOM Center to I-271 to I-90. Used tires from $60, oil changes from $39." },
  { slug: "som-center-rd-solon-rd", name: "SOM Center Rd & Solon Rd", lat: 41.3950, lng: -81.4410, zip: "44139", driveMinutes: 20, neighborhood: "Solon", localContent: "Solon residents at SOM Center and Solon Rd — the suburban drive to Nick's is worth it. We've become the go-to shop for Solon families who want honest diagnostics without the dealer markup. $10 down financing available on all services." },
  { slug: "harper-rd-cochran-rd-solon", name: "Harper Rd & Cochran Rd", lat: 41.3870, lng: -81.4500, zip: "44139", driveMinutes: 21, neighborhood: "Solon", localContent: "From the Harper and Cochran area in Solon, take 422 west to I-271 north — about 21 minutes to Nick's. Suburban roads might be smoother than Cleveland's, but Ohio winters still eat brake pads and rust out undercarriages. Get ahead of it with a free inspection." },

  // ─── EASTLAKE (EXPANDED) ───────────────────────
  { slug: "vine-st-stevens-blvd-eastlake", name: "Vine St & Stevens Blvd", lat: 41.6540, lng: -81.4370, zip: "44095", driveMinutes: 12, neighborhood: "Eastlake", localContent: "Eastlake is Lake County but practically in our backyard — 12 minutes south on Vine St to Euclid Ave. If you're near Stevens Blvd and your check engine light just popped on, don't panic. Drive to Nick's for a $49 diagnostic that actually finds the problem." },
  { slug: "lakeshore-blvd-e-305th-eastlake", name: "Lakeshore Blvd & E 305th St", lat: 41.6630, lng: -81.4420, zip: "44095", driveMinutes: 13, neighborhood: "Eastlake", localContent: "Eastlake drivers along Lakeshore Blvd — the lake-effect moisture accelerates rust and corrosion on brake lines, exhaust, and undercarriage. Catch it early at Nick's Tire & Auto, 13 minutes south. We do free undercarriage inspections and we'll show you exactly what needs attention." },

  // ─── CHARDON ───────────────────────────────────
  { slug: "chardon-square-main-st", name: "Chardon Square & Main St", lat: 41.2130, lng: -81.2050, zip: "44024", driveMinutes: 25, neighborhood: "Chardon", landmark: "Near Chardon Square", localContent: "Chardon residents know Geauga County's rural roads are tough on vehicles — gravel, frost heaves, and deer crossings take their toll on tires and suspension. Nick's Tire & Auto is 25 minutes west on Route 6, and we specialize in the heavy-duty tire and alignment work rural driving demands." },
  { slug: "chardon-center-st-water-st", name: "Center St & Water St", lat: 41.2120, lng: -81.2070, zip: "44024", driveMinutes: 25, neighborhood: "Chardon", localContent: "From downtown Chardon near Center and Water, head west on 6 to Route 2 to I-90 — about 25 minutes to Nick's. Geauga County drivers come to us because we stock the heavier-duty tires that handle country roads, and our used tire selection means you're not paying premium prices for practical needs." },

  // ─── PAINESVILLE ───────────────────────────────
  { slug: "state-st-main-st-painesville", name: "State St & Main St", lat: 41.7244, lng: -81.2458, zip: "44077", driveMinutes: 20, neighborhood: "Painesville", localContent: "Painesville is growing fast and so is traffic on State Street. More miles means more wear on tires and brakes. Nick's Tire & Auto is 20 minutes west on Route 2 — worth the drive for honest work and prices that respect your paycheck. Walk-ins welcome 7 days a week." },
  { slug: "mentor-ave-richmond-st-painesville", name: "Mentor Ave & Richmond St", lat: 41.7200, lng: -81.2500, zip: "44077", driveMinutes: 20, neighborhood: "Painesville", localContent: "Lake County's county seat deserves better auto repair options, and that's exactly what you get at Nick's. From the Mentor Ave corridor in Painesville, head west on Route 2 for 20 minutes. We've earned 1,700+ five-star reviews by treating every customer like a neighbor, not a number." },
  { slug: "fairport-nursery-rd-painesville", name: "Fairport Nursery Rd & SR 535", lat: 41.7320, lng: -81.2700, zip: "44077", driveMinutes: 22, neighborhood: "Painesville", localContent: "North Painesville and Fairport Harbor residents — Route 2 west gets you to Nick's in about 22 minutes. Lake County's salt and lake-effect weather are murder on brake rotors and wheel bearings. Our ASE-certified techs catch problems early so you're not stranded on 2 in January." },
];

export function getIntersectionBySlug(slug: string): IntersectionData | undefined {
  return INTERSECTIONS.find(i => i.slug === slug);
}
