export interface Neighborhood {
  slug: string;
  name: string;
  type: "street" | "landmark" | "neighborhood";
  headline: string;
  description: string;
  driveTime: string;
  driveMiles: string;
  directionsFrom: string;
  nearbyLandmarks: string[];
  localContent: string;
  lat: number;
  lng: number;
}

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    slug: "east-185th-street-auto-repair",
    name: "East 185th Street",
    type: "street",
    headline: "Auto Repair Near East 185th Street, Cleveland",
    description: "Fast, reliable auto repair on East 185th Street in Cleveland. Expert technicians serving the East 185th corridor with same-day service.",
    driveTime: "5 min",
    driveMiles: "1.5 mi",
    directionsFrom: "Head south on Euclid Ave to East 185th Street, approximately 1.5 miles.",
    nearbyLandmarks: ["Five Points", "Euclid Square Mall"],
    localContent: "East 185th Street is a major commercial corridor serving Cleveland's east side. Our shop is centrally located to serve commuters and local businesses along this busy street, offering quick turnaround on routine maintenance and repairs.",
    lat: 41.5185,
    lng: -81.6158,
  },
  {
    slug: "euclid-square-mall-area",
    name: "Euclid Square Mall",
    type: "landmark",
    headline: "Auto Repair Near Euclid Square Mall",
    description: "Professional auto service minutes from Euclid Square Mall shopping area. Convenient location for quick repairs while you shop.",
    driveTime: "3 min",
    driveMiles: "0.8 mi",
    directionsFrom: "Euclid Square Mall is just north of our location on Euclid Avenue, about 0.8 miles away.",
    nearbyLandmarks: ["East 185th Street", "Five Points"],
    localContent: "Located near Euclid Square Mall, our shop is perfectly positioned for shoppers needing quick vehicle maintenance or unexpected repairs. Get your car serviced while you visit the mall's diverse retail shops and restaurants.",
    lat: 41.5315,
    lng: -81.6185,
  },
  {
    slug: "richmond-heights-mechanic",
    name: "Richmond Heights",
    headline: "Auto Repair in Richmond Heights, Cleveland",
    description: "Expert auto repair serving Richmond Heights residents. Quality service for all makes and models with fast turnaround times.",
    type: "neighborhood",
    driveTime: "8 min",
    driveMiles: "3.2 mi",
    directionsFrom: "From Richmond Heights, take Euclid Avenue southwest toward our location near East 185th Street. Drive time is approximately 8 minutes.",
    nearbyLandmarks: ["South Euclid", "Lyndhurst", "Mayfield Heights"],
    localContent: "Richmond Heights is a well-established residential community with families and professionals who depend on reliable vehicle maintenance. We serve Richmond Heights residents with the same quality and care they expect from a neighborhood shop.",
    lat: 41.4485,
    lng: -81.5055,
  },
  {
    slug: "collinwood",
    name: "Collinwood",
    type: "neighborhood",
    headline: "Auto Repair Near Collinwood, Cleveland",
    description: "Trusted auto repair for Collinwood residents. Fast service, fair pricing, and expert technicians you can count on.",
    driveTime: "7 min",
    driveMiles: "2.5 mi",
    directionsFrom: "From Collinwood, head south on Euclid Avenue for approximately 2.5 miles to reach our shop on East 185th Street.",
    nearbyLandmarks: ["Five Points", "Shore Cultural Centre"],
    localContent: "Collinwood is a vibrant neighborhood with a strong community spirit. Our shop has served Collinwood families for years, providing reliable auto repair that keeps your vehicle running smoothly through Cleveland's tough winters.",
    lat: 41.5505,
    lng: -81.6045,
  },
  {
    slug: "nottingham",
    name: "Nottingham",
    type: "neighborhood",
    headline: "Auto Repair Near Nottingham, Cleveland",
    description: "Professional vehicle maintenance and repair for Nottingham. Same-day service available for most repairs.",
    driveTime: "6 min",
    driveMiles: "2.0 mi",
    directionsFrom: "From Nottingham, take Euclid Avenue south approximately 2 miles to our location near East 185th Street.",
    nearbyLandmarks: ["Five Points", "Collinwood"],
    localContent: "Nottingham residents enjoy quick access to our shop with just a 6-minute drive. We specialize in keeping neighborhood vehicles running reliably, from routine maintenance to complex engine diagnostics.",
    lat: 41.5395,
    lng: -81.6125,
  },
  {
    slug: "five-points",
    name: "Five Points",
    type: "neighborhood",
    headline: "Auto Repair at Five Points, Cleveland",
    description: "Convenient auto repair right at Five Points. Expert service with quick turnaround for all vehicle types.",
    driveTime: "4 min",
    driveMiles: "1.2 mi",
    directionsFrom: "Five Points is just 1.2 miles north on Euclid Avenue from our shop, about a 4-minute drive.",
    nearbyLandmarks: ["Collinwood", "Euclid Square Mall", "Shore Cultural Centre"],
    localContent: "Five Points is a bustling neighborhood intersection where Euclid Avenue meets East 185th Street. Our convenient location makes us the go-to choice for Five Points residents needing quick, reliable auto service without driving far.",
    lat: 41.5275,
    lng: -81.6170,
  },
  {
    slug: "waterloo-arts-district",
    name: "Waterloo Arts District",
    type: "landmark",
    headline: "Auto Repair Near Waterloo Arts District",
    description: "Quality auto service for Waterloo Arts District visitors and residents. Professional technicians ready to help.",
    driveTime: "10 min",
    driveMiles: "3.5 mi",
    directionsFrom: "From Waterloo Arts District, head south on Euclid Avenue for about 3.5 miles to reach our shop.",
    nearbyLandmarks: ["University Circle", "Severance Town Center"],
    localContent: "The Waterloo Arts District's thriving creative community benefits from our shop's proximity. Whether you're heading to galleries or studio spaces, we keep your vehicle ready for the drive.",
    lat: 41.4885,
    lng: -81.6125,
  },
  {
    slug: "shore-cultural-centre",
    name: "Shore Cultural Centre",
    type: "landmark",
    headline: "Auto Repair Near Shore Cultural Centre",
    description: "Convenient auto repair near Shore Cultural Centre. Fast service so you can get back to enjoying the arts.",
    driveTime: "4 min",
    driveMiles: "1.0 mi",
    directionsFrom: "Shore Cultural Centre is just 1 mile north of our location, easily accessible via Euclid Avenue, about 4 minutes away.",
    nearbyLandmarks: ["Five Points", "Collinwood"],
    localContent: "Shore Cultural Centre visitors and staff appreciate having reliable auto service minutes away. We understand the importance of keeping your vehicle ready for weekend cultural events.",
    lat: 41.5350,
    lng: -81.6190,
  },
  {
    slug: "severance-town-center",
    name: "Severance Town Center",
    type: "landmark",
    headline: "Auto Repair Near Severance Town Center",
    description: "Professional auto service convenient to Severance Town Center. Expert technicians for all your vehicle needs.",
    driveTime: "12 min",
    driveMiles: "4.5 mi",
    directionsFrom: "From Severance Town Center, take Euclid Avenue south approximately 4.5 miles to our shop location.",
    nearbyLandmarks: ["University Circle", "South Euclid"],
    localContent: "Severance Town Center shoppers can trust our shop to handle vehicle maintenance while they enjoy dining and retail. We're close enough to fit a repair into your shopping trip.",
    lat: 41.4180,
    lng: -81.5225,
  },
  {
    slug: "university-circle",
    name: "University Circle",
    type: "neighborhood",
    headline: "Auto Repair Near University Circle, Cleveland",
    description: "Reliable auto repair serving University Circle. Quick service for students, faculty, and residents.",
    driveTime: "15 min",
    driveMiles: "5.5 mi",
    directionsFrom: "From University Circle, take Euclid Avenue north approximately 5.5 miles to reach our shop near East 185th Street.",
    nearbyLandmarks: ["Severance Town Center", "South Euclid"],
    localContent: "University Circle's students, faculty, and residents appreciate our accessible pricing and expert service. We keep Cleveland's knowledge community mobile with reliable, affordable vehicle maintenance.",
    lat: 41.3945,
    lng: -81.5085,
  },
  {
    slug: "wickliffe",
    name: "Wickliffe",
    type: "neighborhood",
    headline: "Auto Repair Near Wickliffe, Cleveland",
    description: "Professional auto repair for Wickliffe residents. Full service shop with convenient location.",
    driveTime: "10 min",
    driveMiles: "4.0 mi",
    directionsFrom: "From Wickliffe, take Euclid Avenue southwest approximately 4 miles to our location.",
    nearbyLandmarks: ["Eastlake", "Willowick"],
    localContent: "Wickliffe families trust our shop for their vehicle maintenance needs. We provide the personalized service and fair pricing that Wickliffe residents expect.",
    lat: 41.4635,
    lng: -81.4955,
  },
  {
    slug: "willowick",
    name: "Willowick",
    type: "neighborhood",
    headline: "Auto Repair Near Willowick, Cleveland",
    description: "Expert auto service for Willowick area. Experienced technicians, same-day service available.",
    driveTime: "12 min",
    driveMiles: "5.0 mi",
    directionsFrom: "From Willowick, head toward Euclid Avenue and travel southwest about 5 miles to reach our shop.",
    nearbyLandmarks: ["Wickliffe", "Eastlake"],
    localContent: "Willowick residents and commuters benefit from our convenient location and quick turnaround on common repairs. We're your neighborhood shop for reliable vehicle maintenance.",
    lat: 41.4515,
    lng: -81.4725,
  },
  {
    slug: "eastlake",
    name: "Eastlake",
    type: "neighborhood",
    headline: "Auto Repair Near Eastlake, Cleveland",
    description: "Quality auto repair serving Eastlake. Fast, reliable service from experienced technicians.",
    driveTime: "14 min",
    driveMiles: "6.0 mi",
    directionsFrom: "From Eastlake, take Euclid Avenue west approximately 6 miles to our location near East 185th Street.",
    nearbyLandmarks: ["Wickliffe", "Willowick"],
    localContent: "Eastlake residents appreciate our shop's expertise in maintaining and repairing vehicles for both city and highway driving. We keep Eastlake families safe and mobile.",
    lat: 41.4585,
    lng: -81.4395,
  },
  {
    slug: "south-euclid-mechanic",
    name: "South Euclid",
    type: "neighborhood",
    headline: "Auto Repair in South Euclid, Cleveland",
    description: "Trusted auto repair for South Euclid residents. Full-service shop with expert technicians.",
    driveTime: "10 min",
    driveMiles: "3.8 mi",
    directionsFrom: "From South Euclid, take Euclid Avenue north approximately 3.8 miles to reach our shop.",
    nearbyLandmarks: ["Severance Town Center", "University Circle"],
    localContent: "South Euclid families have depended on quality auto repair for decades. Our shop continues that tradition with reliable service and transparent pricing.",
    lat: 41.4315,
    lng: -81.5215,
  },
  {
    slug: "lyndhurst-mechanic",
    name: "Lyndhurst",
    type: "neighborhood",
    headline: "Auto Repair Near Lyndhurst, Cleveland",
    description: "Professional vehicle service for Lyndhurst area. Same-day repairs and quick turnaround.",
    driveTime: "12 min",
    driveMiles: "4.5 mi",
    directionsFrom: "From Lyndhurst, take Euclid Avenue north approximately 4.5 miles to our location.",
    nearbyLandmarks: ["Richmond Heights", "Mayfield Heights"],
    localContent: "Lyndhurst residents enjoy convenient access to our full-service shop. We handle everything from routine maintenance to major repairs with the quality Lyndhurst families expect.",
    lat: 41.4235,
    lng: -81.5645,
  },
  {
    slug: "mayfield-heights",
    name: "Mayfield Heights",
    type: "neighborhood",
    headline: "Auto Repair Near Mayfield Heights, Cleveland",
    description: "Expert auto service for Mayfield Heights. Quick turnaround and fair pricing.",
    driveTime: "14 min",
    driveMiles: "5.5 mi",
    directionsFrom: "From Mayfield Heights, take Euclid Avenue north approximately 5.5 miles to reach our shop.",
    nearbyLandmarks: ["Richmond Heights", "Highland Heights"],
    localContent: "Mayfield Heights residents trust our shop for reliable vehicle maintenance and repair. We're committed to keeping your car running smoothly year-round.",
    lat: 41.4105,
    lng: -81.5485,
  },
  {
    slug: "highland-heights",
    name: "Highland Heights",
    type: "neighborhood",
    headline: "Auto Repair Near Highland Heights, Cleveland",
    description: "Quality auto repair for Highland Heights. Professional service at fair prices.",
    driveTime: "12 min",
    driveMiles: "5.0 mi",
    directionsFrom: "From Highland Heights, take Euclid Avenue north approximately 5 miles to our location.",
    nearbyLandmarks: ["Mayfield Heights", "Beachwood"],
    localContent: "Highland Heights families appreciate our convenient shop location and expert technicians. We provide the reliable vehicle maintenance that keeps Highland Heights residents safe and mobile.",
    lat: 41.4245,
    lng: -81.5315,
  },
  {
    slug: "beachwood",
    name: "Beachwood",
    type: "neighborhood",
    headline: "Auto Repair Near Beachwood, Cleveland",
    description: "Professional auto repair serving Beachwood area. Expert technicians, convenient location.",
    driveTime: "15 min",
    driveMiles: "6.5 mi",
    directionsFrom: "From Beachwood, take Euclid Avenue west approximately 6.5 miles to reach our shop near East 185th Street.",
    nearbyLandmarks: ["Highland Heights", "University Circle"],
    localContent: "Beachwood residents access our shop for reliable vehicle maintenance and repairs. Whether you're heading to Beachwood Place or just need routine service, we're your trusted local shop.",
    lat: 41.4125,
    lng: -81.4895,
  },
  {
    slug: "mentor-on-the-lake",
    name: "Mentor-on-the-Lake",
    type: "neighborhood",
    headline: "Auto Repair Serving Mentor-on-the-Lake Drivers",
    description: "Trusted auto repair for Mentor-on-the-Lake residents. Quality service, honest pricing, all makes and models.",
    driveTime: "20 min",
    driveMiles: "12 mi",
    directionsFrom: "From Mentor-on-the-Lake, take Route 2 west to I-90 west, exit at East 185th Street.",
    nearbyLandmarks: ["Eastlake", "Willoughby"],
    localContent: "Mentor-on-the-Lake drivers facing lake-effect weather need vehicles in top condition. Our shop provides the preventive maintenance and expert repairs that keep lakefront residents safe through every season.",
    lat: 41.7042,
    lng: -81.3596,
  },
  {
    slug: "willoughby-hills",
    name: "Willoughby Hills",
    type: "neighborhood",
    headline: "Auto Repair Near Willoughby Hills",
    description: "Expert auto repair for Willoughby Hills residents. Brakes, tires, diagnostics, and general repair.",
    driveTime: "18 min",
    driveMiles: "10 mi",
    directionsFrom: "From Willoughby Hills, take I-90 west to East 185th Street exit, then south to Euclid Avenue.",
    nearbyLandmarks: ["Wickliffe", "Willoughby"],
    localContent: "Willoughby Hills is a growing community east of Cleveland where residents value reliable transportation. Our shop is a short drive on I-90 and provides full-service auto repair at honest prices.",
    lat: 41.5855,
    lng: -81.4325,
  },
  {
    slug: "euclid-ohio",
    name: "Euclid",
    type: "neighborhood",
    headline: "Auto Repair in Euclid, Ohio",
    description: "Your neighborhood auto repair shop in Euclid. Located right on Euclid Avenue serving the entire community.",
    driveTime: "3 min",
    driveMiles: "0.5 mi",
    directionsFrom: "We are located directly on Euclid Avenue at 17625 Euclid Ave — right in the heart of Euclid.",
    nearbyLandmarks: ["East 185th Street", "Euclid Square Mall", "Shore Cultural Centre"],
    localContent: "Nick's Tire & Auto is a Euclid institution. Located right on Euclid Avenue, we are embedded in this community. From daily commuters to local business vehicles, we keep Euclid moving.",
    lat: 41.5232,
    lng: -81.5267,
  },
  {
    slug: "east-cleveland",
    name: "East Cleveland",
    type: "neighborhood",
    headline: "Auto Repair Serving East Cleveland",
    description: "Affordable, honest auto repair for East Cleveland residents. Expert mechanics, fair prices, walk-ins welcome.",
    driveTime: "10 min",
    driveMiles: "4 mi",
    directionsFrom: "From East Cleveland, head east on Euclid Avenue approximately 4 miles to our shop.",
    nearbyLandmarks: ["University Circle", "Cleveland Heights"],
    localContent: "East Cleveland residents deserve a mechanic they can trust. We provide transparent pricing, thorough diagnostics, and quality repairs. No upselling, no pressure — just honest work.",
    lat: 41.5328,
    lng: -81.5794,
  },
  {
    slug: "cleveland-heights-mechanic",
    name: "Cleveland Heights",
    type: "neighborhood",
    headline: "Auto Repair Near Cleveland Heights",
    description: "Quality auto repair serving Cleveland Heights. Experienced mechanics handling everything from oil changes to engine repair.",
    driveTime: "12 min",
    driveMiles: "5 mi",
    directionsFrom: "From Cleveland Heights, take Mayfield Road or Cedar Road east to Euclid Avenue.",
    nearbyLandmarks: ["University Circle", "South Euclid", "East Cleveland"],
    localContent: "Cleveland Heights is known for its walkable neighborhoods, historic homes, and engaged community. When Heights residents need auto repair, they trust a shop with the same values — honest, thorough, and community-focused.",
    lat: 41.5198,
    lng: -81.5563,
  },
  {
    slug: "garfield-heights",
    name: "Garfield Heights",
    type: "neighborhood",
    headline: "Auto Repair for Garfield Heights Residents",
    description: "Reliable auto repair serving Garfield Heights. Tires, brakes, diagnostics, and more. Walk-ins welcome.",
    driveTime: "20 min",
    driveMiles: "9 mi",
    directionsFrom: "From Garfield Heights, take I-480 east to I-271 north, then Route 2 west to Euclid Avenue.",
    nearbyLandmarks: ["Maple Heights", "Bedford"],
    localContent: "Garfield Heights residents making the drive to our shop find it worthwhile for the quality and honesty they get. We treat every vehicle like our own and every customer like a neighbor.",
    lat: 41.4170,
    lng: -81.6059,
  },
  {
    slug: "maple-heights",
    name: "Maple Heights",
    type: "neighborhood",
    headline: "Auto Repair Serving Maple Heights Drivers",
    description: "Expert mechanics serving Maple Heights. Full-service auto repair with transparent pricing.",
    driveTime: "22 min",
    driveMiles: "10 mi",
    directionsFrom: "From Maple Heights, take Broadway Avenue north to I-77, then I-90 east to East 185th.",
    nearbyLandmarks: ["Garfield Heights", "Bedford"],
    localContent: "Maple Heights is a hardworking community that values straightforward service. That is exactly what we provide — clear diagnosis, fair pricing, quality parts, and repairs done right the first time.",
    lat: 41.4081,
    lng: -81.5656,
  },
  {
    slug: "parma-heights",
    name: "Parma Heights",
    type: "neighborhood",
    headline: "Auto Repair for Parma Heights Residents",
    description: "Trusted auto repair serving Parma Heights. All makes and models, honest work at fair prices.",
    driveTime: "25 min",
    driveMiles: "14 mi",
    directionsFrom: "From Parma Heights, take I-480 east to I-77 north, then I-90 east to East 185th Street.",
    nearbyLandmarks: ["Parma", "Brook Park"],
    localContent: "Parma Heights drivers who make the trip to Nick's become loyal customers because of the difference in service quality. We earn trust through transparency, not advertising.",
    lat: 41.3879,
    lng: -81.7631,
  },
  {
    slug: "shaker-heights",
    name: "Shaker Heights",
    type: "neighborhood",
    headline: "Auto Repair Near Shaker Heights",
    description: "Professional auto repair serving Shaker Heights. Expert diagnostics, quality parts, honest pricing.",
    driveTime: "15 min",
    driveMiles: "7 mi",
    directionsFrom: "From Shaker Heights, take Van Aken Blvd to Chagrin Blvd east, then north on I-271 to Route 2 west.",
    nearbyLandmarks: ["Cleveland Heights", "Beachwood", "University Circle"],
    localContent: "Shaker Heights residents expect quality in everything — including auto repair. We match that standard with thorough inspections, premium parts when requested, and detailed explanations of every repair.",
    lat: 41.4739,
    lng: -81.5371,
  },
  {
    slug: "warrensville-heights",
    name: "Warrensville Heights",
    type: "neighborhood",
    headline: "Auto Repair Serving Warrensville Heights",
    description: "Reliable auto repair for Warrensville Heights. Affordable service, experienced mechanics.",
    driveTime: "18 min",
    driveMiles: "8 mi",
    directionsFrom: "From Warrensville Heights, take Warrensville Center Road north to I-271 north, then Route 2 west.",
    nearbyLandmarks: ["South Euclid", "Beachwood"],
    localContent: "Warrensville Heights drivers find our shop is worth the drive for honest pricing and quality work. We serve this community with the same integrity we bring to every customer.",
    lat: 41.4350,
    lng: -81.5228,
  },
  {
    slug: "lakewood-auto-repair",
    name: "Lakewood",
    type: "neighborhood",
    headline: "Auto Repair for Lakewood Drivers",
    description: "Quality auto repair serving Lakewood residents. Expert mechanics, fair pricing, all makes and models.",
    driveTime: "25 min",
    driveMiles: "15 mi",
    directionsFrom: "From Lakewood, take I-90 east approximately 15 miles to the East 185th Street exit.",
    nearbyLandmarks: ["Rocky River", "Cleveland West Side"],
    localContent: "Lakewood drivers who prefer honest, independent shops over chain stores find our reputation worth the drive. We specialize in the kind of transparent service that builds lifelong customer relationships.",
    lat: 41.4828,
    lng: -81.7979,
  },
  {
    slug: "willoughby-ohio",
    name: "Willoughby",
    type: "neighborhood",
    headline: "Auto Repair Near Willoughby, Ohio",
    description: "Expert auto repair serving Willoughby and Lake County. Tires, brakes, diagnostics, and full-service repair.",
    driveTime: "18 min",
    driveMiles: "11 mi",
    directionsFrom: "From Willoughby, take I-90 west to East 185th Street exit, south to Euclid Avenue.",
    nearbyLandmarks: ["Willoughby Hills", "Eastlake", "Wickliffe"],
    localContent: "Willoughby is the gateway to Lake County, and many residents pass through our area on their daily commute. We make it easy to drop off your vehicle and pick it up the same day.",
    lat: 41.6394,
    lng: -81.4064,
  },
  {
    slug: "bedford-ohio",
    name: "Bedford",
    type: "neighborhood",
    headline: "Auto Repair Serving Bedford, Ohio",
    description: "Trusted mechanics serving Bedford drivers. Honest diagnostics, quality repairs, competitive prices.",
    driveTime: "22 min",
    driveMiles: "11 mi",
    directionsFrom: "From Bedford, take I-480 east to I-271 north, then Route 2 west to Euclid Avenue.",
    nearbyLandmarks: ["Maple Heights", "Garfield Heights"],
    localContent: "Bedford residents who have been burned by chain shops appreciate our approach: diagnose thoroughly, explain clearly, price fairly, and fix it right. That is the Nick's Tire standard.",
    lat: 41.3931,
    lng: -81.5348,
  },
  {
    slug: "north-collinwood",
    name: "North Collinwood",
    type: "neighborhood",
    headline: "Auto Repair in North Collinwood, Cleveland",
    description: "Your local auto repair shop serving North Collinwood. Quick turnaround, honest service, walk-ins welcome.",
    driveTime: "7 min",
    driveMiles: "2.5 mi",
    directionsFrom: "From North Collinwood, head east on Lakeshore Blvd to East 185th Street, then south to Euclid Avenue.",
    nearbyLandmarks: ["Collinwood", "Euclid Beach"],
    localContent: "North Collinwood is one of Cleveland's most vibrant lakefront neighborhoods. Our shop is minutes away, making us the go-to for quick oil changes, brake jobs, and seasonal tire swaps.",
    lat: 41.5725,
    lng: -81.5725,
  },
  {
    slug: "downtown-cleveland",
    name: "Downtown Cleveland",
    type: "neighborhood",
    headline: "Auto Repair for Downtown Cleveland Workers",
    description: "Convenient auto repair for downtown Cleveland commuters. Drop off on your way to work, pick up after.",
    driveTime: "15 min",
    driveMiles: "8 mi",
    directionsFrom: "From Downtown Cleveland, take I-90 east to East 185th Street exit, south to Euclid Avenue.",
    nearbyLandmarks: ["University Circle", "Playhouse Square"],
    localContent: "Downtown Cleveland professionals trust us because we respect their time. Drop your car off in the morning, and we will have it ready by end of day. Text updates keep you informed throughout.",
    lat: 41.4994,
    lng: -81.6944,
  },
  {
    slug: "tremont-cleveland",
    name: "Tremont",
    type: "neighborhood",
    headline: "Auto Repair Serving Tremont, Cleveland",
    description: "Quality auto repair for Tremont residents. Independent, honest mechanics you can trust.",
    driveTime: "20 min",
    driveMiles: "10 mi",
    directionsFrom: "From Tremont, take I-90 east approximately 10 miles to the East 185th Street exit.",
    nearbyLandmarks: ["Ohio City", "Downtown Cleveland"],
    localContent: "Tremont is known for its independent spirit and support of local businesses. We are that local business — owner-operated, community-focused, and dedicated to honest auto repair.",
    lat: 41.4776,
    lng: -81.6883,
  },
  {
    slug: "ohio-city",
    name: "Ohio City",
    type: "neighborhood",
    headline: "Auto Repair for Ohio City Residents",
    description: "Expert auto repair serving Ohio City. All makes, all models, honest pricing.",
    driveTime: "22 min",
    driveMiles: "12 mi",
    directionsFrom: "From Ohio City, take I-90 east approximately 12 miles to the East 185th Street exit.",
    nearbyLandmarks: ["Tremont", "Lakewood", "Downtown Cleveland"],
    localContent: "Ohio City residents appreciate local, independent businesses. Nick's Tire & Auto is exactly that — a family-run shop where the owner works on the cars and knows every customer by name.",
    lat: 41.4849,
    lng: -81.7087,
  },
  {
    slug: "rocky-river",
    name: "Rocky River",
    type: "neighborhood",
    headline: "Auto Repair for Rocky River Drivers",
    description: "Professional auto repair serving Rocky River. Expert diagnostics, honest service, fair prices.",
    driveTime: "28 min",
    driveMiles: "17 mi",
    directionsFrom: "From Rocky River, take I-90 east approximately 17 miles to the East 185th Street exit.",
    nearbyLandmarks: ["Lakewood", "Bay Village"],
    localContent: "Rocky River drivers who have discovered Nick's Tire & Auto keep coming back. The quality of work and transparency of pricing make the drive worthwhile every time.",
    lat: 41.4756,
    lng: -81.8389,
  },
  {
    slug: "solon-ohio",
    name: "Solon",
    type: "neighborhood",
    headline: "Auto Repair Serving Solon, Ohio",
    description: "Trusted auto repair for Solon residents. Expert mechanics, quality parts, honest work.",
    driveTime: "25 min",
    driveMiles: "15 mi",
    directionsFrom: "From Solon, take I-271 north to I-90 east, then exit at East 185th Street.",
    nearbyLandmarks: ["Beachwood", "Chagrin Falls"],
    localContent: "Solon is a thriving suburb with families who expect quality. Our shop delivers the same quality you find in premium dealership service departments — at independent shop prices.",
    lat: 41.3895,
    lng: -81.4412,
  },
  {
    slug: "broadview-heights",
    name: "Broadview Heights",
    type: "neighborhood",
    headline: "Auto Repair for Broadview Heights Drivers",
    description: "Quality auto repair serving Broadview Heights. Tires, brakes, engine repair, and more.",
    driveTime: "30 min",
    driveMiles: "18 mi",
    directionsFrom: "From Broadview Heights, take I-77 north to I-480 east to I-271 north, then Route 2 west.",
    nearbyLandmarks: ["Parma Heights", "North Royalton"],
    localContent: "Broadview Heights drivers who prioritize quality over convenience choose Nick's Tire & Auto. Our reputation for honest work and expert repairs has earned loyal customers from across Greater Cleveland.",
    lat: 41.3137,
    lng: -81.6812,
  },
  {
    slug: "chagrin-falls",
    name: "Chagrin Falls",
    type: "neighborhood",
    headline: "Auto Repair Serving Chagrin Falls",
    description: "Expert auto repair for Chagrin Falls residents. Honest diagnostics, premium service, fair pricing.",
    driveTime: "28 min",
    driveMiles: "16 mi",
    directionsFrom: "From Chagrin Falls, take Route 422 west to I-271 north, then I-90 east to East 185th Street.",
    nearbyLandmarks: ["Solon", "Beachwood"],
    localContent: "Chagrin Falls is a charming village where residents value quality and authenticity. We provide auto repair with those same values — genuine parts, thorough workmanship, and honest communication.",
    lat: 41.4315,
    lng: -81.3920,
  },
];
