/**
 * ROUTE REGISTRY — Single Source of Truth for all public routes.
 * Used by: prerender script, sitemap generator, robots.txt, navigation.
 *
 * IMPORTANT: When adding a new route, add it here first, then in App.tsx.
 * The sitemap and prerender script both read from this file.
 */

export interface RouteEntry {
  path: string;
  /** Sitemap priority (0.0–1.0) */
  priority: number;
  /** Sitemap change frequency */
  changefreq: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  /** SEO title tag — max 60 chars */
  title: string;
  /** SEO meta description — max 160 chars */
  description: string;
  /** Group for organizational purposes */
  group: "core" | "service" | "city" | "neighborhood" | "seo-service" | "vehicle" | "problem" | "seasonal" | "utility" | "legal" | "landing" | "blog" | "tire-size" | "vehicle-service";
  /** Whether to include in sitemap (false for auth-gated, landing pages, etc.) */
  sitemap: boolean;
  /** Whether to prerender this page */
  prerender: boolean;
}

// ─── CORE PAGES ──────────────────────────────────────────
const CORE_PAGES: RouteEntry[] = [
  {
    path: "/",
    priority: 1.0,
    changefreq: "weekly",
    title: "Nick's Tire & Auto — Cleveland's #1 Tire Shop & Auto Repair",
    description: "Cleveland's top-rated new & used tire specialist + full-service auto repair. 1,700+ reviews, 4.9 stars. Free installation package ($289 value). Walk-ins 7 days. Financing.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/services",
    priority: 0.9,
    changefreq: "weekly",
    title: "Auto Repair Services — Nick's Tire & Auto",
    description: "Full-service auto repair in Cleveland. Tires, brakes, diagnostics, emissions, oil changes, suspension, alignment. Walk-ins welcome. Financing available.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/about",
    priority: 0.7,
    changefreq: "monthly",
    title: "About Nick's Tire & Auto — Cleveland Auto Shop",
    description: "Family-owned auto repair in Cleveland since 2018. Honest service, transparent pricing, 4.9-star reviews. Meet the team behind Northeast Ohio's top-rated shop.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/contact",
    priority: 0.8,
    changefreq: "monthly",
    title: "Contact Nick's Tire & Auto — Cleveland OH",
    description: "Visit Nick's Tire & Auto at 17625 Euclid Ave, Cleveland, OH 44112. Call (216) 862-0005. Open Mon-Sat 8AM-6PM, Sun 9AM-4PM. Walk-ins welcome.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/reviews",
    priority: 0.7,
    changefreq: "weekly",
    title: "Reviews — Nick's Tire & Auto Cleveland",
    description: "Read 1,700+ Google reviews for Nick's Tire & Auto. 4.9-star rating. See why Cleveland trusts us for tires, brakes, diagnostics, and auto repair.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/faq",
    priority: 0.7,
    changefreq: "monthly",
    title: "FAQ — Nick's Tire & Auto Cleveland",
    description: "Common questions about auto repair at Nick's Tire & Auto. Pricing, walk-in policy, financing, tire installation, diagnostics, and more. Cleveland, OH.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/blog",
    priority: 0.7,
    changefreq: "weekly",
    title: "Auto Care Blog — Nick's Tire & Auto Cleveland",
    description: "Car care tips, maintenance guides, and auto repair advice from Nick's Tire & Auto. Expert insights for Cleveland drivers.",
    group: "blog",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/areas-served",
    priority: 0.8,
    changefreq: "monthly",
    title: "Areas Served — Nick's Tire & Auto | Cleveland & Northeast Ohio",
    description: "Nick's Tire & Auto serves 150+ locations across Cleveland, Euclid, Parma, Lakewood, Mentor, and all of Northeast Ohio. Find your neighborhood auto repair page.",
    group: "core",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/pay",
    priority: 0.3,
    changefreq: "yearly",
    title: "Pay Invoice — Nick's Tire & Auto",
    description: "Pay your Nick's Tire & Auto invoice online. Enter your invoice number and phone to look up your bill and pay securely with credit or debit card.",
    group: "utility",
    sitemap: false,
    prerender: false,
  },
];

// ─── SERVICE PAGES ───────────────────────────────────────
const SERVICE_PAGES: RouteEntry[] = [
  {
    path: "/tires",
    priority: 1.0,
    changefreq: "weekly",
    title: "Tire Shop Cleveland OH — New & Used Tires | Nick's Tire",
    description: "Cleveland's #1 new & used tire shop. Buy tires online — free premium installation ($289 value). Flat repair $15. Every tire inspected. Walk-ins 7 days. $10 down financing.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/brakes",
    priority: 0.9,
    changefreq: "monthly",
    title: "Brake Repair Cleveland OH — Nick's Tire & Auto",
    description: "Expert brake repair in Cleveland. Pads, rotors, calipers, ABS diagnostics. Honest diagnosis before any repair. 4.9 stars. Financing available.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/diagnostics",
    priority: 0.9,
    changefreq: "monthly",
    title: "Engine Diagnostics Cleveland — Nick's Tire & Auto",
    description: "Check engine light on? Expert OBD-II diagnostics in Cleveland. We pinpoint the exact cause. 4.9 stars, 1,700+ reviews. Walk-ins welcome.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/emissions",
    priority: 0.9,
    changefreq: "monthly",
    title: "Emissions Testing Cleveland OH — Nick's Tire & Auto",
    description: "Ohio E-Check and emissions repair in Cleveland. O2 sensors, catalytic converters, EVAP systems. We get you passing. Walk-ins welcome.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/oil-change",
    priority: 0.8,
    changefreq: "monthly",
    title: "Oil Change Cleveland OH — Nick's Tire & Auto",
    description: "Quick, affordable oil changes in Cleveland. Conventional and synthetic. Filter replacement included. No appointment needed. Walk-ins welcome.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/general-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "General Auto Repair Services — Nick's Tire & Auto Cleveland",
    description: "Full-service auto repair in Cleveland. Engine, transmission, electrical, cooling, exhaust, belts, hoses. Honest diagnosis. Financing available.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/alignment",
    priority: 0.8,
    changefreq: "monthly",
    title: "Wheel Alignment Cleveland OH — Nick's Tire & Auto",
    description: "Professional wheel alignment in Cleveland. Fix pulling, uneven tire wear, and steering issues. State-of-the-art equipment. Walk-ins welcome.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/tires/info",
    priority: 0.8,
    changefreq: "monthly",
    title: "Tire Services Cleveland — New & Used | Nick's Tire & Auto",
    description: "Cleveland's largest new & used tire selection. Free mounting, balancing, TPMS reset, alignment check with every tire. Flat repair from $15. Walk-ins welcome 7 days.",
    group: "service",
    sitemap: true,
    prerender: true,
  },
  { path: "/ac-repair", priority: 0.8, changefreq: "monthly", title: "AC Repair Cleveland OH — Nick's Tire & Auto", description: "Auto AC and heating repair in Cleveland. Recharge, compressor, condenser, evaporator, heater core. Same-day service. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/transmission", priority: 0.8, changefreq: "monthly", title: "Transmission Repair Cleveland OH — Nick's Tire & Auto", description: "Transmission repair and service in Cleveland. Fluid changes, diagnostics, solenoid repair, rebuilds. Honest diagnosis. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/electrical", priority: 0.8, changefreq: "monthly", title: "Auto Electrical Repair Cleveland — Nick's Tire & Auto", description: "Auto electrical repair in Cleveland. Battery, alternator, starter, wiring, power windows. Expert diagnostics. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/battery", priority: 0.8, changefreq: "monthly", title: "Battery Testing & Replacement Cleveland — Nick's Tire", description: "Free car battery testing in Cleveland. Same-day replacement. Charging system check included. All makes and models. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/exhaust", priority: 0.8, changefreq: "monthly", title: "Exhaust & Muffler Repair Cleveland — Nick's Tire & Auto", description: "Exhaust and muffler repair in Cleveland. Catalytic converter, exhaust pipe, manifold. Pass Ohio E-Check. Same-day service.", group: "service", sitemap: true, prerender: true },
  { path: "/cooling", priority: 0.8, changefreq: "monthly", title: "Cooling System Repair Cleveland — Nick's Tire & Auto", description: "Cooling system and radiator repair in Cleveland. Water pump, thermostat, coolant flush, hoses. Don't risk overheating. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/pre-purchase-inspection", priority: 0.8, changefreq: "monthly", title: "Pre-Purchase Car Inspection Cleveland — Nick's Tire", description: "Used car inspection in Cleveland before you buy. 150+ point check with written report and photos. Know exactly what you're buying. Walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/belts-hoses", priority: 0.7, changefreq: "monthly", title: "Belt & Hose Replacement Cleveland — Nick's Tire & Auto", description: "Serpentine belt, timing belt, and hose replacement in Cleveland, OH. Prevent breakdowns with expert service. Fair prices, walk-ins welcome.", group: "service", sitemap: true, prerender: true },
  { path: "/starter-alternator", priority: 0.8, changefreq: "monthly", title: "Starter & Alternator Repair Cleveland — Nick's Tire", description: "Starter and alternator repair in Cleveland, OH. Free charging system test. Same-day replacement for all makes and models. 4.9 stars, walk-ins welcome.", group: "service", sitemap: true, prerender: true },
];

// ─── CITY/AREA PAGES ─────────────────────────────────────
const CITY_PAGES: RouteEntry[] = [
  {
    path: "/cleveland-auto-repair",
    priority: 0.9,
    changefreq: "weekly",
    title: "Auto Repair Cleveland OH — Nick's Tire & Auto",
    description: "Cleveland's #1 auto repair shop and tire specialist. 1,700+ reviews, 4.9 stars. Tires, brakes, diagnostics, emissions. Walk-ins 7 days. $10 down financing.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/euclid-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Euclid OH — Nick's Tire & Auto",
    description: "Best auto repair in Euclid, OH. Nick's Tire & Auto on Euclid Ave — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics, emissions. Walk-ins welcome 7 days.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/lakewood-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Lakewood OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Lakewood, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 15 min from Lakewood.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/parma-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Parma OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Parma, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 20 min from Parma.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/east-cleveland-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair East Cleveland OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near East Cleveland, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 5 min from East Cleveland.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/shaker-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Shaker Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Shaker Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 10 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/cleveland-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Cleveland Heights — Nick's Tire & Auto",
    description: "Top-rated auto repair near Cleveland Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 10 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/mentor-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Mentor OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Mentor, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 25 min from Mentor.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/strongsville-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Strongsville OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Strongsville, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes. 30 min from Strongsville.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/south-euclid-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair South Euclid OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near South Euclid, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 10 min from South Euclid.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/garfield-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Garfield Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Garfield Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/richmond-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Richmond Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Richmond Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. Minutes away.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/lyndhurst-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Lyndhurst OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Lyndhurst, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 10 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/willoughby-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Willoughby OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Willoughby, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. 20 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/maple-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Maple Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Maple Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min via Dunham Rd.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/bedford-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Bedford OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Bedford, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 18 min via Rockside Rd & I-480.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/warrensville-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Warrensville Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Warrensville Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 12 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/beachwood-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Beachwood OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Beachwood, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min via Cedar Rd.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/mayfield-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Near Mayfield Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near Mayfield Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 14 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/university-heights-auto-repair",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair University Heights OH — Nick's Tire & Auto",
    description: "Top-rated auto repair near University Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 14 min drive.",
    group: "city",
    sitemap: true,
    prerender: true,
  },
];

// ─── NEIGHBORHOOD MICRO-PAGES ────────────────────────────
const NEIGHBORHOOD_PAGES: RouteEntry[] = [
  { path: "/east-185th-street-auto-repair", priority: 0.7, changefreq: "monthly", title: "Auto Repair East 185th St — Nick's Tire & Auto", description: "Auto repair near East 185th Street, Cleveland. Nick's Tire & Auto — minutes away. Tires, brakes, diagnostics, emissions. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/euclid-square-mall-area", priority: 0.7, changefreq: "monthly", title: "Auto Repair Euclid Square Mall Area — Nick's Tire", description: "Auto repair near Euclid Square Mall. Nick's Tire & Auto on Euclid Ave. Tires, brakes, diagnostics. Walk-ins welcome 7 days.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/richmond-heights-mechanic", priority: 0.7, changefreq: "monthly", title: "Mechanic Richmond Heights OH — Nick's Tire & Auto", description: "Trusted mechanic near Richmond Heights, OH. Nick's Tire & Auto — 4.9 stars. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/collinwood", priority: 0.7, changefreq: "monthly", title: "Auto Repair Collinwood Cleveland — Nick's Tire & Auto", description: "Auto repair in Collinwood, Cleveland. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/nottingham", priority: 0.7, changefreq: "monthly", title: "Auto Repair Nottingham Cleveland — Nick's Tire & Auto", description: "Auto repair in Nottingham, Cleveland. Nick's Tire & Auto — 4.9 stars. Tires, brakes, oil changes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/five-points", priority: 0.7, changefreq: "monthly", title: "Auto Repair Five Points Cleveland — Nick's Tire & Auto", description: "Auto repair near Five Points, Cleveland. Nick's Tire & Auto — 4.9 stars. Tires, brakes, diagnostics, emissions. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/waterloo-arts-district", priority: 0.7, changefreq: "monthly", title: "Auto Repair Waterloo Arts District — Nick's Tire", description: "Auto repair near Waterloo Arts District, Cleveland. Nick's Tire & Auto — 4.9 stars. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/shore-cultural-centre", priority: 0.7, changefreq: "monthly", title: "Auto Repair Shore Cultural Centre Area — Nick's Tire", description: "Auto repair near Shore Cultural Centre, Euclid. Nick's Tire & Auto — 4.9 stars. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/severance-town-center", priority: 0.7, changefreq: "monthly", title: "Auto Repair Severance Town Center — Nick's Tire", description: "Auto repair near Severance Town Center, Cleveland Heights. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics, oil changes.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/university-circle", priority: 0.7, changefreq: "monthly", title: "Auto Repair University Circle Cleveland — Nick's Tire", description: "Auto repair near University Circle, Cleveland. Nick's Tire & Auto — 4.9 stars. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/wickliffe", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Wickliffe OH — Nick's Tire & Auto", description: "Auto repair near Wickliffe, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min drive.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/willowick", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Willowick OH — Nick's Tire & Auto", description: "Auto repair near Willowick, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min drive.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/eastlake", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Eastlake OH — Nick's Tire & Auto", description: "Auto repair near Eastlake, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. 15 min drive.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/south-euclid-mechanic", priority: 0.7, changefreq: "monthly", title: "Mechanic South Euclid OH — Nick's Tire & Auto", description: "Trusted mechanic near South Euclid, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/lyndhurst-mechanic", priority: 0.7, changefreq: "monthly", title: "Mechanic Lyndhurst OH — Nick's Tire & Auto", description: "Trusted mechanic near Lyndhurst, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/mayfield-heights", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Mayfield Heights OH — Nick's Tire", description: "Auto repair near Mayfield Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/highland-heights", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Highland Heights OH — Nick's Tire", description: "Auto repair near Highland Heights, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, oil changes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/beachwood", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Beachwood OH — Nick's Tire & Auto", description: "Auto repair near Beachwood, OH. Nick's Tire & Auto — 4.9 stars, 1,700+ reviews. Tires, brakes, diagnostics. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/mentor-on-the-lake", priority: 0.6, changefreq: "monthly", title: "Auto Repair Mentor-on-the-Lake — Nick's Tire & Auto", description: "Trusted auto repair serving Mentor-on-the-Lake, OH. Tires, brakes, diagnostics, oil changes, and emissions. Quality service, honest pricing.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/willoughby-hills", priority: 0.6, changefreq: "monthly", title: "Auto Repair Willoughby Hills OH — Nick's Tire & Auto", description: "Expert auto repair near Willoughby Hills, OH. Brakes, tires, engine diagnostics, oil changes, and emissions repair. 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/euclid-ohio", priority: 0.8, changefreq: "monthly", title: "Auto Repair Euclid Ohio — Nick's Tire & Auto", description: "Your neighborhood auto repair shop in Euclid, OH. Tires, brakes, diagnostics, emissions, oil changes. Located on Euclid Ave. Walk-ins welcome 7 days.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/east-cleveland", priority: 0.7, changefreq: "monthly", title: "East Cleveland Mechanic — Tires & Repair Near You", description: "Affordable auto repair serving East Cleveland, OH. Tires, brakes, engine diagnostics, oil changes, and emissions. Expert mechanics, fair prices.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/cleveland-heights-mechanic", priority: 0.7, changefreq: "monthly", title: "Mechanic Cleveland Heights — Nick's Tire & Auto", description: "Quality auto repair near Cleveland Heights, OH. Brakes, tires, oil changes, engine diagnostics, emissions, and general repair. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/garfield-heights", priority: 0.6, changefreq: "monthly", title: "Garfield Heights Auto Repair — Tires, Brakes & More", description: "Reliable auto repair serving Garfield Heights, OH. Tires, brakes, engine diagnostics, oil changes, and emissions repair. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/maple-heights", priority: 0.6, changefreq: "monthly", title: "Auto Repair Maple Heights OH — Nick's Tire & Auto", description: "Expert mechanics serving Maple Heights, OH. Brakes, tires, engine diagnostics, oil changes, emissions, and general repair. Transparent pricing.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/parma-heights", priority: 0.6, changefreq: "monthly", title: "Auto Repair Parma Heights — Nick's Tire & Auto", description: "Trusted auto repair for Parma Heights, OH. Brakes, tires, diagnostics, oil changes, and emissions. All makes and models. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/shaker-heights", priority: 0.7, changefreq: "monthly", title: "Auto Repair Near Shaker Heights — Nick's Tire & Auto", description: "Professional auto repair serving Shaker Heights, OH. Brakes, tires, engine diagnostics, oil changes, and emissions. Expert service, quality parts.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/warrensville-heights", priority: 0.6, changefreq: "monthly", title: "Auto Repair Warrensville Heights — Nick's Tire & Auto", description: "Reliable auto repair for Warrensville Heights, OH. Tires, brakes, diagnostics, oil changes, and emissions. Affordable service, experienced mechanics.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/lakewood-mechanic", priority: 0.7, changefreq: "monthly", title: "Lakewood OH Mechanic — Tires, Brakes & Repair", description: "Quality auto repair for Lakewood, OH drivers. Tires, brakes, engine diagnostics, oil changes, and emissions repair. Expert mechanics, fair pricing.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/willoughby-ohio", priority: 0.7, changefreq: "monthly", title: "Auto Repair Willoughby OH — Nick's Tire & Auto", description: "Expert auto repair serving Willoughby and Lake County, OH. Tires, brakes, diagnostics, oil changes, emissions. 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/bedford-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Bedford OH — Nick's Tire & Auto", description: "Trusted mechanics serving Bedford, OH. Brakes, tires, engine diagnostics, oil changes, and emissions repair. Honest diagnostics, quality repairs.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/north-collinwood", priority: 0.7, changefreq: "monthly", title: "Auto Repair North Collinwood — Nick's Tire & Auto", description: "Your local auto repair shop in North Collinwood, Cleveland. Tires, brakes, diagnostics, oil changes, and emissions. Quick turnaround, honest service.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/downtown-cleveland", priority: 0.7, changefreq: "monthly", title: "Auto Repair Downtown Cleveland — Nick's Tire & Auto", description: "Convenient auto repair for downtown Cleveland commuters. Tires, brakes, diagnostics, oil changes. Drop off and pick up service. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/tremont-cleveland", priority: 0.6, changefreq: "monthly", title: "Auto Repair Tremont Cleveland — Nick's Tire & Auto", description: "Quality auto repair for Tremont, Cleveland residents. Tires, brakes, diagnostics, oil changes, emissions. Independent, honest mechanics.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/ohio-city", priority: 0.6, changefreq: "monthly", title: "Auto Repair Ohio City Cleveland — Nick's Tire & Auto", description: "Expert auto repair serving Ohio City, Cleveland. All makes and models — tires, brakes, diagnostics, oil changes. Honest pricing, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/rocky-river", priority: 0.6, changefreq: "monthly", title: "Auto Repair Rocky River OH — Nick's Tire & Auto", description: "Professional auto repair serving Rocky River, OH. Expert engine diagnostics, brakes, tires, oil changes, and emissions. Fair prices, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/solon-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Solon OH — Nick's Tire & Auto", description: "Trusted auto repair for Solon, OH residents. Brakes, tires, engine diagnostics, oil changes, and emissions repair. Quality parts, honest work.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/broadview-heights", priority: 0.6, changefreq: "monthly", title: "Auto Repair Broadview Heights — Nick's Tire & Auto", description: "Quality auto repair serving Broadview Heights, OH. Tires, brakes, engine diagnostics, oil changes, emissions, and alignment. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/chagrin-falls", priority: 0.6, changefreq: "monthly", title: "Auto Repair Chagrin Falls OH — Nick's Tire & Auto", description: "Expert auto repair for Chagrin Falls, OH. Brakes, tires, engine diagnostics, oil changes, and emissions. Honest diagnostics, premium service.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/bainbridge-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Bainbridge OH — Nick's Tire & Auto", description: "Trusted auto repair for Bainbridge Township, OH. Brakes, tires, diagnostics, oil changes, and emissions. Honest pricing. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/pepper-pike", priority: 0.6, changefreq: "monthly", title: "Auto Repair Pepper Pike — Nick's Tire & Auto", description: "Professional auto repair near Pepper Pike, OH. Expert engine diagnostics, brakes, tires, oil changes, and emissions. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/gates-mills", priority: 0.5, changefreq: "monthly", title: "Auto Repair Gates Mills — Nick's Tire & Auto", description: "Expert auto repair for Gates Mills, OH. Brakes, tires, engine diagnostics, oil changes, and emissions. Quality OEM parts, honest work.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/independence-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Independence OH — Nick's Tire & Auto", description: "Reliable auto repair for Independence, OH. Same-day brake, tire, diagnostic, and oil change service. 4.9 stars, 1,700+ reviews. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/strongsville-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Strongsville OH — Nick's Tire & Auto", description: "Quality auto repair serving Strongsville, OH. Tires, brakes, engine diagnostics, oil changes, and emissions repair. 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/north-royalton", priority: 0.6, changefreq: "monthly", title: "Auto Repair North Royalton — Nick's Tire & Auto", description: "Trusted auto repair for North Royalton, OH. Brakes, tires, diagnostics, oil changes, and emissions. Honest pricing, 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/bay-village", priority: 0.5, changefreq: "monthly", title: "Auto Repair Bay Village OH — Nick's Tire & Auto", description: "Expert auto repair for Bay Village, OH. Tires, brakes, engine diagnostics, oil changes, and emissions repair. Professional service, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/westlake-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Westlake OH — Nick's Tire & Auto", description: "Professional auto repair serving Westlake, OH. Tires, brakes, diagnostics, oil changes, and emissions. Quality parts, honest pricing. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/north-olmsted", priority: 0.6, changefreq: "monthly", title: "Auto Repair North Olmsted — Nick's Tire & Auto", description: "Reliable auto repair for North Olmsted, OH. Brakes, tires, engine diagnostics, oil changes, and emissions repair. Walk-ins welcome 7 days a week.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/middleburg-heights", priority: 0.5, changefreq: "monthly", title: "Auto Repair Middleburg Heights — Nick's Tire & Auto", description: "Trusted auto repair for Middleburg Heights, OH. Tires, brakes, oil changes, diagnostics, and emissions repair. 4.9 stars, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/brook-park", priority: 0.5, changefreq: "monthly", title: "Auto Repair Brook Park — Nick's Tire & Auto", description: "Expert auto repair in Brook Park near Cleveland Hopkins Airport. Tires, brakes, diagnostics, oil changes. 4.9 stars. Walk-ins welcome 7 days.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/avon-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Avon OH — Nick's Tire & Auto", description: "Quality auto repair serving Avon, OH. Tires, brakes, engine diagnostics, oil changes, and emissions repair. Transparent pricing, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/avon-lake", priority: 0.5, changefreq: "monthly", title: "Auto Repair Avon Lake OH — Nick's Tire & Auto", description: "Trusted auto repair for Avon Lake, OH. Tires, brakes, engine diagnostics, emissions, and oil changes. Professional service, honest pricing.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/twinsburg-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Twinsburg OH — Nick's Tire & Auto", description: "Expert auto repair for Twinsburg, OH. Brakes, tires, engine diagnostics, oil changes, emissions repair, and alignment. Walk-ins welcome 7 days.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/aurora-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Aurora OH — Nick's Tire & Auto", description: "Trusted auto repair for Aurora, OH. Tires, brakes, engine diagnostics, oil changes, and emissions repair. Quality parts, expert mechanics.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/streetsboro", priority: 0.5, changefreq: "monthly", title: "Auto Repair Streetsboro OH — Nick's Tire & Auto", description: "Reliable auto repair serving Streetsboro, OH. Tires, brakes, diagnostics, oil changes, and emissions repair. Honest pricing, expert mechanics.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/chardon-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Chardon OH — Nick's Tire & Auto", description: "Expert auto repair for Chardon, OH. Snow belt tire specialists — winter tires, brakes, diagnostics, and emissions. Honest pricing, walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/painesville-ohio", priority: 0.5, changefreq: "monthly", title: "Auto Repair Painesville OH — Nick's Tire & Auto", description: "Trusted auto repair serving Painesville and Lake County, OH. Tires, brakes, diagnostics, emissions repair. 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/mentor-ohio", priority: 0.6, changefreq: "monthly", title: "Auto Repair Mentor OH — Nick's Tire & Auto", description: "Quality auto repair for Mentor, OH. Expert tire service, brake repair, engine diagnostics, oil changes, and emissions. Walk-ins welcome 7 days.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/university-heights", priority: 0.6, changefreq: "monthly", title: "Auto Repair University Heights — Nick's Tire & Auto", description: "Professional auto repair near University Heights, OH. Tires, brakes, diagnostics, emissions, and oil changes. 4.9 stars. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
  { path: "/parma-ohio", priority: 0.7, changefreq: "monthly", title: "Auto Repair Parma OH — Nick's Tire & Auto", description: "Trusted auto repair for Parma, OH. Brakes, tires, diagnostics, oil changes, emissions, and general repair. Honest work, fair prices. Walk-ins welcome.", group: "neighborhood", sitemap: true, prerender: true },
];

// ─── SEO SERVICE PAGES (long-tail keywords) ──────────────
const SEO_SERVICE_PAGES: RouteEntry[] = [
  { path: "/brake-repair-cleveland", priority: 0.8, changefreq: "monthly", title: "Brake Repair Cleveland OH | 36-Month Warranty | Nick's Tire", description: "Brake repair in Cleveland, OH. Pads, rotors, calipers, ABS. 36-month warranty, same-day service. 4.9 stars, 1,700+ reviews. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
  { path: "/check-engine-light-cleveland", priority: 0.8, changefreq: "monthly", title: "Check Engine Light Cleveland OH | Free Scan w/ Repair | Nick's", description: "Check engine light on in Cleveland? Free diagnostic scan with repair. We find the exact cause with OBD-II. Walk-ins 7 days. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
  { path: "/tire-repair-cleveland", priority: 0.9, changefreq: "monthly", title: "Tire Shop Cleveland OH | New & Used Tires | Walk-Ins | Nick's", description: "Cleveland's top tire shop. New and used tires, mounting, balancing, flat repair. All major brands, fair prices. Walk-ins 7 days. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
  { path: "/suspension-repair-cleveland", priority: 0.8, changefreq: "monthly", title: "Suspension Repair Cleveland OH | Struts & Shocks | Nick's Tire", description: "Suspension repair in Cleveland. Struts, shocks, ball joints, tie rods. Fix pothole damage. Same-day service, 4.9 stars. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
  { path: "/ac-repair-cleveland", priority: 0.8, changefreq: "monthly", title: "AC Repair Cleveland OH | Same Day Service | Nick's Tire", description: "Car AC not blowing cold in Cleveland? Recharge, compressor, leak repair. Same-day service, walk-ins welcome 7 days. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
  { path: "/diagnostics-cleveland", priority: 0.8, changefreq: "monthly", title: "Auto Diagnostics Cleveland OH | Walk-Ins Welcome | Nick's Tire", description: "Advanced auto diagnostics in Cleveland. OBD-II scanning, electrical testing, sensor diagnostics. Walk-ins 7 days. 4.9 stars. Call (216) 862-0005.", group: "seo-service", sitemap: true, prerender: true },
];

// ─── VEHICLE MAKE PAGES ──────────────────────────────────
const VEHICLE_PAGES: RouteEntry[] = [
  { path: "/toyota-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Toyota Repair Cleveland OH — Nick's Tire & Auto", description: "Toyota repair specialists in Cleveland. Camry, Corolla, RAV4, Highlander. Factory-level diagnostics. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/honda-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Honda Repair Cleveland OH — Nick's Tire & Auto", description: "Honda repair specialists in Cleveland. Civic, Accord, CR-V, Pilot. Expert diagnostics. 4.9 stars, 1,700+ reviews. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/ford-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Ford Repair Cleveland OH — Nick's Tire & Auto", description: "Ford repair specialists in Cleveland, OH. F-150, Explorer, Escape, Focus service, diagnostics, and maintenance. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/chevy-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Chevy Repair Cleveland OH — Nick's Tire & Auto", description: "Chevrolet repair specialists in Cleveland, OH. Silverado, Equinox, Malibu, Traverse service and diagnostics. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/nissan-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Nissan Repair Cleveland OH — Nick's Tire & Auto", description: "Nissan repair specialists in Cleveland. Altima, Rogue, Sentra, Pathfinder. Expert diagnostics. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/hyundai-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Hyundai Repair Cleveland OH — Nick's Tire & Auto", description: "Hyundai repair specialists in Cleveland. Elantra, Tucson, Sonata, Santa Fe. Expert diagnostics. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/kia-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Kia Repair Cleveland OH — Nick's Tire & Auto", description: "Kia repair specialists in Cleveland, OH. Forte, Sportage, Sorento, Soul service, diagnostics, and maintenance. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/jeep-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Jeep Repair Cleveland OH — Nick's Tire & Auto", description: "Jeep repair specialists in Cleveland, OH. Wrangler, Cherokee, Grand Cherokee, Compass service and diagnostics. 4.9 stars. Walk-ins welcome.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/bmw-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "BMW Repair Cleveland OH — Nick's Tire & Auto", description: "BMW repair specialists in Cleveland, OH. 3 Series, 5 Series, X3, X5 service and diagnostics. European car experts. 4.9 stars, 1,700+ reviews.", group: "vehicle", sitemap: true, prerender: true },
  { path: "/dodge-ram-repair-cleveland", priority: 0.7, changefreq: "monthly", title: "Dodge & Ram Repair Cleveland — Nick's Tire & Auto", description: "Dodge and Ram repair specialists in Cleveland, OH. Charger, Challenger, Ram 1500 service and diagnostics. 4.9 stars, 1,700+ reviews.", group: "vehicle", sitemap: true, prerender: true },
];

// ─── PROBLEM PAGES ───────────────────────────────────────
const PROBLEM_PAGES: RouteEntry[] = [
  { path: "/car-shaking-while-driving", priority: 0.7, changefreq: "monthly", title: "Car Shaking While Driving? — Nick's Tire & Auto", description: "Car shaking while driving? Common causes: tire balance, warped rotors, worn suspension. Expert diagnosis at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/brakes-grinding", priority: 0.7, changefreq: "monthly", title: "Brakes Grinding? — Nick's Tire & Auto Cleveland", description: "Brakes grinding or squealing? Don't wait — worn pads damage rotors. Expert brake repair at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/check-engine-light-flashing", priority: 0.7, changefreq: "monthly", title: "Check Engine Light Flashing? — Nick's Tire & Auto", description: "Flashing check engine light means stop driving. Could be misfire or catalytic converter damage. Expert diagnostics in Cleveland. Call (216) 862-0005.", group: "problem", sitemap: true, prerender: true },
  { path: "/car-overheating", priority: 0.7, changefreq: "monthly", title: "Car Overheating? — Nick's Tire & Auto Cleveland", description: "Car overheating? Pull over immediately. Radiator, thermostat, water pump, or head gasket. Expert cooling system repair in Cleveland.", group: "problem", sitemap: true, prerender: true },
  { path: "/car-wont-start", priority: 0.7, changefreq: "monthly", title: "Car Won't Start? — Nick's Tire & Auto Cleveland", description: "Car won't start? Battery, starter, alternator, or ignition. Expert diagnostics at Nick's Tire & Auto, Cleveland. Walk-ins welcome 7 days.", group: "problem", sitemap: true, prerender: true },
  { path: "/steering-wheel-shaking", priority: 0.7, changefreq: "monthly", title: "Steering Wheel Shaking? — Nick's Tire & Auto", description: "Steering wheel shaking? Tire balance, alignment, or suspension issue. Expert diagnosis at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/car-pulling-to-one-side", priority: 0.7, changefreq: "monthly", title: "Car Pulling to One Side? — Nick's Tire & Auto", description: "Car pulling left or right? Alignment, tire pressure, or brake issue. Expert diagnosis at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/transmission-slipping", priority: 0.7, changefreq: "monthly", title: "Transmission Slipping? — Nick's Tire & Auto", description: "Transmission slipping or jerking? Don't ignore it — early repair saves thousands. Expert diagnostics in Cleveland. Call (216) 862-0005.", group: "problem", sitemap: true, prerender: true },
  { path: "/ac-not-blowing-cold", priority: 0.7, changefreq: "monthly", title: "AC Not Blowing Cold? — Nick's Tire & Auto Cleveland", description: "AC not blowing cold? Refrigerant, compressor, or condenser issue. Auto AC repair at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/battery-keeps-dying", priority: 0.7, changefreq: "monthly", title: "Battery Keeps Dying? — Nick's Tire & Auto Cleveland", description: "Battery keeps dying? Alternator, parasitic drain, or old battery. Expert electrical diagnostics at Nick's Tire & Auto, Cleveland.", group: "problem", sitemap: true, prerender: true },
  { path: "/grinding-noise-when-braking", priority: 0.7, changefreq: "monthly", title: "Grinding Noise When Braking? — Nick's Tire & Auto", description: "Grinding noise when braking? Worn pads, damaged rotors, or debris. Expert brake diagnosis at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/oil-leak-under-car", priority: 0.7, changefreq: "monthly", title: "Oil Leak Under Car? — Nick's Tire & Auto Cleveland", description: "Oil leak under your car? Valve cover gasket, oil pan, or drain plug. Expert leak diagnosis at Nick's Tire & Auto, Cleveland. Walk-ins welcome.", group: "problem", sitemap: true, prerender: true },
  { path: "/check-engine-light-on", priority: 0.7, changefreq: "monthly", title: "Check Engine Light On? Top 5 Causes + What to Do Now", description: "Check engine light on? Most common causes: O2 sensor, catalytic converter, gas cap, ignition coils. Walk in for same-day diagnostics in Cleveland. (216) 862-0005.", group: "problem", sitemap: true, prerender: true },
];

// ─── SEASONAL PAGES ──────────────────────────────────────
const SEASONAL_PAGES: RouteEntry[] = [
  { path: "/winter-car-care-cleveland", priority: 0.7, changefreq: "monthly", title: "Winter Car Care Cleveland — Nick's Tire & Auto", description: "Prepare your car for Cleveland winter. Snow tires, battery testing, antifreeze, brakes. Winter car care at Nick's Tire & Auto.", group: "seasonal", sitemap: true, prerender: true },
  { path: "/summer-car-care-cleveland", priority: 0.7, changefreq: "monthly", title: "Summer Car Care Cleveland — Nick's Tire & Auto", description: "Summer car care in Cleveland. AC check, tire inspection, coolant, brakes. Keep your car running cool. Nick's Tire & Auto.", group: "seasonal", sitemap: true, prerender: true },
];

// ─── UTILITY PAGES ───────────────────────────────────────
const UTILITY_PAGES: RouteEntry[] = [
  {
    path: "/financing",
    priority: 0.8,
    changefreq: "weekly",
    title: "Auto Repair Financing Cleveland — Nick's Tire & Auto",
    description: "Auto repair financing in Cleveland. $10 down, drive today. Acima, Koalafi, Snap Finance, American First. All credit welcome. Apply in minutes.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/specials",
    priority: 0.8,
    changefreq: "weekly",
    title: "Deals & Specials — Nick's Tire & Auto Cleveland",
    description: "Current deals and coupons at Nick's Tire & Auto, Cleveland. Save on tires, brakes, oil changes, diagnostics. Updated weekly.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/diagnose",
    priority: 0.7,
    changefreq: "monthly",
    title: "AI Car Diagnostic Tool — Nick's Tire & Auto",
    description: "Describe your car problem and get an instant AI diagnosis. Free online tool from Nick's Tire & Auto, Cleveland. Know before you go.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/estimate",
    priority: 0.8,
    changefreq: "monthly",
    title: "Auto Repair Cost Estimator — Nick's Tire & Auto",
    description: "Get an instant repair cost estimate for your vehicle. Transparent pricing from Nick's Tire & Auto, Cleveland. No surprises.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/pricing",
    priority: 0.7,
    changefreq: "monthly",
    title: "Auto Repair Pricing — Nick's Tire & Auto Cleveland",
    description: "Transparent auto repair pricing at Nick's Tire & Auto, Cleveland. Get estimates for brakes, tires, oil changes, diagnostics, and more.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/fleet",
    priority: 0.7,
    changefreq: "monthly",
    title: "Fleet Auto Service Cleveland — Nick's Tire & Auto",
    description: "Fleet maintenance and repair in Cleveland. Volume discounts, priority scheduling, fleet reporting. Nick's Tire & Auto — 4.9 stars.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/rewards",
    priority: 0.6,
    changefreq: "monthly",
    title: "Rewards Program — Nick's Tire & Auto Cleveland",
    description: "Earn points on every service at Nick's Tire & Auto. Redeem for discounts on future repairs. Cleveland's best auto repair loyalty program.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/car-care-guide",
    priority: 0.6,
    changefreq: "monthly",
    title: "Car Care Guide — Nick's Tire & Auto Cleveland",
    description: "Complete car maintenance guide from Nick's Tire & Auto. When to change oil, check brakes, rotate tires, and more. Cleveland drivers' handbook.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/refer",
    priority: 0.5,
    changefreq: "monthly",
    title: "Referral Program — Nick's Tire & Auto Cleveland",
    description: "Refer a friend to Nick's Tire & Auto and you both save on auto repair. Earn rewards on tires, brakes, oil changes, and more. Cleveland's best referral program.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/ask",
    priority: 0.6,
    changefreq: "weekly",
    title: "Ask a Mechanic — Nick's Tire & Auto Cleveland",
    description: "Ask our mechanics a question online. Free expert advice from Nick's Tire & Auto, Cleveland. Get answers before you visit.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/cost-estimator",
    priority: 0.8,
    changefreq: "monthly",
    title: "Repair Cost Estimator — Nick's Tire & Auto",
    description: "Estimate your auto repair cost online. Transparent pricing from Nick's Tire & Auto, Cleveland. Know the cost before you visit.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/status",
    priority: 0.5,
    changefreq: "monthly",
    title: "Check Repair Status — Nick's Tire & Auto",
    description: "Track your vehicle repair status online. Real-time updates from Nick's Tire & Auto, Cleveland.",
    group: "utility",
    sitemap: false, // auth-gated
    prerender: true,
  },
  {
    path: "/my-garage",
    priority: 0.5,
    changefreq: "monthly",
    title: "My Garage — Nick's Tire & Auto Cleveland",
    description: "Manage your vehicles and service history at Nick's Tire & Auto, Cleveland. Track maintenance schedules and upcoming services.",
    group: "utility",
    sitemap: false, // user-specific
    prerender: true,
  },
  {
    path: "/review",
    priority: 0.5,
    changefreq: "monthly",
    title: "Leave a Review — Nick's Tire & Auto Cleveland",
    description: "Share your experience at Nick's Tire & Auto, Cleveland. Your feedback helps us serve you better.",
    group: "utility",
    sitemap: false, // review generation page
    prerender: true,
  },
  {
    path: "/careers",
    priority: 0.7,
    changefreq: "weekly",
    title: "Careers — Auto Tech Jobs Cleveland | Nick's Tire & Auto",
    description: "Now hiring mechanics, tire technicians, and apprentices at Nick's Tire & Auto. Competitive pay, growth opportunities, modern shop. Apply in 2 minutes.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/appointment",
    priority: 0.8,
    changefreq: "monthly",
    title: "Schedule Service — Nick's Tire & Auto Cleveland",
    description: "Book your auto repair appointment online at Nick's Tire & Auto. Tires, brakes, oil changes, diagnostics. Walk-ins also welcome 7 days a week.",
    group: "utility",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/booking",
    priority: 0.8,
    changefreq: "monthly",
    title: "Book Online — Nick's Tire & Auto Cleveland",
    description: "Book your auto repair appointment online at Nick's Tire & Auto. Tires, brakes, oil changes, diagnostics. Walk-ins also welcome 7 days a week.",
    group: "utility",
    sitemap: false,
    prerender: true,
  },
];

// ─── LEGAL PAGES ─────────────────────────────────────────
const LEGAL_PAGES: RouteEntry[] = [
  {
    path: "/privacy-policy",
    priority: 0.3,
    changefreq: "yearly",
    title: "Privacy Policy — Nick's Tire & Auto",
    description: "Privacy policy for nickstire.org. How we collect, use, and protect your information at Nick's Tire & Auto, Cleveland, OH.",
    group: "legal",
    sitemap: true,
    prerender: true,
  },
  {
    path: "/terms",
    priority: 0.3,
    changefreq: "yearly",
    title: "Terms of Service — Nick's Tire & Auto",
    description: "Terms of service for nickstire.org. Usage terms, privacy practices, and policies for Nick's Tire & Auto website and auto repair services in Cleveland, OH.",
    group: "legal",
    sitemap: true,
    prerender: true,
  },
];

// ─── NON-SITEMAP PAGES (landing pages, admin, etc.) ──────
const EXCLUDED_PAGES: RouteEntry[] = [
  { path: "/portal", priority: 0, changefreq: "monthly", title: "Customer Portal — Nick's Tire & Auto", description: "Nick's Tire & Auto customer portal. View invoices, service history, and manage your account.", group: "utility", sitemap: false, prerender: false },
  { path: "/admin", priority: 0, changefreq: "monthly", title: "Admin Dashboard", description: "", group: "utility", sitemap: false, prerender: false },
  { path: "/admin/content", priority: 0, changefreq: "monthly", title: "Content Manager", description: "", group: "utility", sitemap: false, prerender: false },
  { path: "/lp/brakes", priority: 0, changefreq: "monthly", title: "Brake Repair Special — Nick's Tire & Auto", description: "Limited time brake repair special at Nick's Tire & Auto, Cleveland.", group: "landing", sitemap: false, prerender: false },
  { path: "/lp/tires", priority: 0, changefreq: "monthly", title: "Tire Sale — Nick's Tire & Auto", description: "Limited time tire sale at Nick's Tire & Auto, Cleveland.", group: "landing", sitemap: false, prerender: false },
  { path: "/lp/diagnostics", priority: 0, changefreq: "monthly", title: "Diagnostics Special — Nick's Tire & Auto", description: "Limited time diagnostics special at Nick's Tire & Auto, Cleveland.", group: "landing", sitemap: false, prerender: false },
  { path: "/lp/emergency", priority: 0, changefreq: "monthly", title: "Emergency Auto Repair — Nick's Tire & Auto", description: "Emergency auto repair at Nick's Tire & Auto, Cleveland.", group: "landing", sitemap: false, prerender: false },
];

// ─── TIRE SIZE PAGES (30 programmatic SEO pages) ────────────
import { TIRE_SIZE_PAGES } from "./tireSizes";

const TIRE_SIZE_ROUTE_PAGES: RouteEntry[] = TIRE_SIZE_PAGES.map(t => ({
  path: `/tires/${t.slug}`,
  priority: 0.7,
  changefreq: "monthly" as const,
  title: t.metaTitle,
  description: t.metaDescription,
  group: "tire-size" as const,
  sitemap: true,
  prerender: true,
}));

// ─── VEHICLE + SERVICE COMBO PAGES (50 programmatic SEO pages) ──
import { VEHICLE_SERVICE_PAGES } from "./vehicleServicePages";

const VEHICLE_SERVICE_ROUTE_PAGES: RouteEntry[] = VEHICLE_SERVICE_PAGES.map(p => ({
  path: `/${p.slug}`,
  priority: 0.6,
  changefreq: "monthly" as const,
  title: p.metaTitle,
  description: p.metaDescription,
  group: "vehicle-service" as const,
  sitemap: true,
  prerender: true,
}));

// ─── COMBINED REGISTRY ───────────────────────────────────

export const ALL_ROUTES: RouteEntry[] = [
  ...CORE_PAGES,
  ...SERVICE_PAGES,
  ...CITY_PAGES,
  ...NEIGHBORHOOD_PAGES,
  ...SEO_SERVICE_PAGES,
  ...VEHICLE_PAGES,
  ...PROBLEM_PAGES,
  ...SEASONAL_PAGES,
  ...TIRE_SIZE_ROUTE_PAGES,
  ...VEHICLE_SERVICE_ROUTE_PAGES,
  ...UTILITY_PAGES,
  ...LEGAL_PAGES,
  ...EXCLUDED_PAGES,
];

/** Routes to include in sitemap.xml */
export const SITEMAP_ROUTES = ALL_ROUTES.filter(r => r.sitemap);

/** Routes to prerender at build time */
export const PRERENDER_ROUTES = ALL_ROUTES.filter(r => r.prerender);

/** Get route entry by path */
export function getRouteByPath(path: string): RouteEntry | undefined {
  return ALL_ROUTES.find(r => r.path === path);
}

/** Hardcoded blog slugs (always in sitemap) */
export const BLOG_SLUGS = [
  "5-signs-brakes-need-replacing",
  "check-engine-light-common-causes",
  "ohio-echeck-what-to-know",
  "when-to-replace-tires",
  "spring-car-maintenance-checklist",
  "synthetic-vs-conventional-oil",
  "echeck-emissions-guide-cleveland",
  "winter-tires-cleveland",
  "how-much-brake-repair-cost-cleveland",
  "used-tires-cleveland-guide",
  "transmission-problems-warning-signs",
  "car-wont-start-common-causes",
];
