"""Sync the NOURCITY graphify graph into the operator's Obsidian vault.

Regenerates the 'NOURCITY Codebase Graph' vault folder as community
digest notes: one .md per selected community with '> N nodes' and a
degree-ranked Key Concepts list. Deterministic selection rule so every
sync is reproducible (documented in the generated _ABOUT.md).

Run AFTER `graphify update .` so graph.json is fresh:
    python scripts/graphify-obsidian-sync.py

Overrides:
    GRAPHIFY_OBSIDIAN_DIR  target vault folder (default: OneDrive vault)
"""
import json
import os
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
GRAPH = REPO / "graphify-out" / "graph.json"
LABELS = REPO / "graphify-out" / ".graphify_labels.json"
VAULT_DIR = Path(
    os.environ.get("GRAPHIFY_OBSIDIAN_DIR")
    or r"C:\Users\nourd\OneDrive\Documents\Obsidian Vault\NOURCITY Codebase Graph"
)
BACKUP = REPO / "graphify-out" / f"obsidian-backup-{date.today().isoformat()}"

TOP_BY_SIZE = 50
TOP_BY_DOCS = 60
KEY_CONCEPTS_CAP = 30


def main() -> int:
    if not GRAPH.exists():
        print(f"ERROR: {GRAPH} not found - run `graphify update .` first", file=sys.stderr)
        return 1

    d = json.loads(GRAPH.read_text(encoding="utf-8"))
    labels = (
        json.loads(LABELS.read_text(encoding="utf-8")) if LABELS.exists() else {}
    )

    degree: dict[str, int] = defaultdict(int)
    for e in d["links"]:
        degree[e["source"]] += 1
        degree[e["target"]] += 1

    comm_nodes = defaultdict(list)
    for n in d["nodes"]:
        comm_nodes[n.get("community")].append(n)

    def is_doc(n) -> bool:
        return n.get("file_type") == "document" or str(n.get("source_file", "")).endswith(".md")

    by_size = sorted(comm_nodes, key=lambda c: len(comm_nodes[c]), reverse=True)[:TOP_BY_SIZE]
    by_docs = sorted(
        (c for c in comm_nodes if any(is_doc(n) for n in comm_nodes[c])),
        key=lambda c: sum(1 for n in comm_nodes[c] if is_doc(n)),
        reverse=True,
    )[:TOP_BY_DOCS]
    selected = list(dict.fromkeys(list(by_size) + list(by_docs)))

    def sanitize(name: str) -> str:
        name = re.sub(r'[\\/:*?"<>|]', "-", name)
        name = name.replace(" ", "_")
        return name[:120] or "untitled"

    # Back up the previous export OUTSIDE the vault before replacing it.
    if VAULT_DIR.exists():
        if BACKUP.exists():
            shutil.rmtree(BACKUP)
        shutil.copytree(VAULT_DIR, BACKUP)
        for f in VAULT_DIR.glob("*.md"):
            f.unlink()
    VAULT_DIR.mkdir(parents=True, exist_ok=True)

    commit = subprocess.run(
        ["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"],
        capture_output=True,
        text=True,
    ).stdout.strip()

    seen_names: dict[str, int] = {}
    written = 0
    for c in selected:
        ns = comm_nodes[c]
        label = labels.get(str(c), f"Community {c}")
        fname = sanitize(label)
        if fname in seen_names:
            seen_names[fname] += 1
            fname = f"{fname}_{seen_names[fname]}"
        else:
            seen_names[fname] = 1
        ranked = sorted(ns, key=lambda n: degree[n["id"]], reverse=True)[:KEY_CONCEPTS_CAP]
        lines = [f"# {label}", "", f"> {len(ns)} nodes", "", "## Key Concepts", ""]
        for n in ranked:
            src = n.get("source_file", "")
            lines.append(
                f"- **{n.get('label', n['id'])}** ({degree[n['id']]} connections) — `{src}`"
            )
        lines.append("")
        (VAULT_DIR / f"{fname}.md").write_text("\n".join(lines), encoding="utf-8")
        written += 1

    about = f"""# About this folder

Generated by `scripts/graphify-obsidian-sync.py` — do not hand-edit (regenerated on every sync).

- **Synced:** {date.today().isoformat()} · repo commit `{commit}`
- **Graph:** {len(d['nodes']):,} nodes · {len(d['links']):,} edges · {len(comm_nodes):,} communities
- **Selection rule:** top {TOP_BY_SIZE} communities by node count UNION top {TOP_BY_DOCS} by document-node count → {written} digest notes
- **Format:** one note per community · Key Concepts ranked by connection count (cap {KEY_CONCEPTS_CAP})
- **Source graph:** `NOURCITY/graphify-out/graph.json` · resync: `graphify update .` then rerun this script
"""
    (VAULT_DIR / "_ABOUT.md").write_text(about, encoding="utf-8")

    print(f"Backed up previous export -> {BACKUP}")
    print(f"Wrote {written} community digests + _ABOUT.md -> {VAULT_DIR}")
    print(f"Graph: {len(d['nodes']):,} nodes, {len(d['links']):,} edges, commit {commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
