/**
 * Agent runbook catalog — the typed index. Full prose in docs/runbooks/<id>.md.
 *
 * To add a runbook: append here + create docs/runbooks/<id>.md. Active runbooks
 * must keep current-truth deploy facts (no retired-deploy instructions) and a
 * recent `lastVerified`. `pnpm check:runbooks` enforces this.
 */

import type { Runbook } from "./types";

const VERIFIED = "2026-06-09";
const OWNER = "Nour";

export const RUNBOOKS: Runbook[] = [
  {
    id: "statenour-current-truth",
    title: "Current truth — where Statenour runs",
    domain: "orientation",
    status: "active",
    whenToUse: "First thing in any session, or whenever a doc seems to contradict reality.",
    sourceOfTruth: ["docs/CURRENT-TRUTH.md", "AGENTS.md", "docs/RECONCILIATION.md"],
    rules: [
      "Production deploys from main -> Railway -> bdnick.info. Nothing else is production.",
      "Vercel, codex/ollama-local, statenour-master, the standalone statenour-os repo, and C:\\Users\\nourd\\NOUR-OS are all retired.",
      "On any conflict, live code + RECONCILIATION beat older docs.",
    ],
    commands: ["pnpm check:stale-docs"],
    gotchas: ["Historical docs (docs/archive/**) read like instructions but are not — never paste them into an agent as current context."],
    verification: ["pnpm check:stale-docs reports 0 critical"],
    rollback: "n/a (read-only orientation).",
    relatedFiles: ["docs/CURRENT-TRUTH.md", "scripts/check-stale-docs.ts"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "low",
    docPath: "docs/runbooks/statenour-current-truth.md",
  },
  {
    id: "statenour-claude-code-session",
    title: "Running a Claude Code session safely",
    domain: "session",
    status: "active",
    whenToUse: "Starting any editing session in this repo.",
    sourceOfTruth: ["docs/CURRENT-TRUTH.md", "AGENTS.md", "CLAUDE.md"],
    rules: [
      "Read the current docs first (CURRENT-TRUTH, AGENTS).",
      "Inspect git status / branch / HEAD before editing.",
      "Work in an isolated branch or worktree; main is shared by concurrent sessions.",
      "Never overwrite owner changes; stage only your files by explicit path.",
      "Verify before claiming completion; never make false 'done' claims.",
    ],
    commands: ["git status", "git branch --show-current", "pnpm typecheck", "pnpm test", "pnpm check:stale-docs"],
    gotchas: [
      "Shell cwd resets to C:\\ between calls — prefix Bash with cd into apps/statenour.",
      "A fresh worktree needs `pnpm turbo build --filter=@statenour/lenses` from the WORKTREE ROOT or ~5 strategic-frameworks tests fail to import.",
    ],
    verification: ["typecheck 0", "targeted vitest green", "the change is observed working, not assumed"],
    rollback: "git restore / git checkout the touched paths; worktrees are disposable.",
    relatedFiles: ["AGENTS.md", "docs/CURRENT-TRUTH.md"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "low",
    docPath: "docs/runbooks/statenour-claude-code-session.md",
  },
  {
    id: "statenour-migrations-and-deploys",
    title: "Migrations + deploys",
    domain: "database",
    status: "active",
    whenToUse: "Any schema change, migration, or deploy question.",
    sourceOfTruth: ["docs/DB-MIGRATION-POLICY.md", "lib/db/schema-sentinel.ts", "docs/CURRENT-TRUTH.md"],
    rules: [
      "Column-first: add columns before code reads them; never read a column the migration hasn't safely added.",
      "Dry run first; have a rollback before any destructive move.",
      "Never claim a migration is applied to prod unless run via the guarded apply-pending-migration endpoint AND verified (prisma migrate status).",
      "Never --accept-data-loss — it silently drops pgvector/tsvector columns.",
      "Deploy is push to main -> Railway (no Vercel, no manual dashboard).",
    ],
    commands: ["pnpm exec prisma validate", "pnpm check:raw-sql", "pnpm tsx scripts/run-schema-sentinel.ts"],
    gotchas: ["pgvector/tsvector live outside Prisma's view as Unsupported(...) — db push without the guard drops them."],
    verification: ["prisma migrate status shows the migration applied", "schema sentinel green"],
    rollback: "Restore from the pre-migration backup; pgvector recovery scripts exist (scripts/recover-pgvector-*).",
    relatedFiles: ["docs/DB-MIGRATION-POLICY.md", "lib/db/schema-sentinel.ts", "app/api/system/apply-pending-migration/route.ts"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "high",
    docPath: "docs/runbooks/statenour-migrations-and-deploys.md",
  },
  {
    id: "task-classifier-domain-missions",
    title: "Task classifier — domains, missions, learning",
    domain: "ai-classification",
    status: "active",
    whenToUse: "Touching task creation/classification, mission/goal linkage, or the auto-learn loop.",
    sourceOfTruth: ["lib/ai/classify-task-linkage.ts", "lib/services/mission-helpers.ts"],
    rules: [
      "Do not learn classifier examples from BULK task-migration moves — bulk re-homing is mechanical, not a signal.",
      "Correction capture is fire-and-forget; a failed capture must never block the user action.",
      "GENERAL anchors are protected — never let learning drift the GENERAL bucket.",
      "A user manually re-filing a single task IS a legitimate learning example.",
    ],
    commands: ["pnpm test -- tests/lib/ai"],
    gotchas: ["Inbox missions != user projects — use isInboxMission() (lib/services/mission-helpers.ts); don't add a 4th filter."],
    verification: ["classifier + linkage unit suites green"],
    rollback: "Revert the classifier change; learning rows are additive and idempotent per sourceKey.",
    relatedFiles: ["lib/ai/classify-task-linkage.ts", "lib/services/mission-helpers.ts"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "medium",
    docPath: "docs/runbooks/task-classifier-domain-missions.md",
  },
  {
    id: "stale-doc-cleanup",
    title: "Stale-doc cleanup + the guard",
    domain: "docs",
    status: "active",
    whenToUse: "When a doc asserts a retired deploy/provider fact as current, or before adding a new doc.",
    sourceOfTruth: ["docs/CURRENT-TRUTH.md", "scripts/check-stale-docs.ts"],
    rules: [
      "Quarantine historical docs into docs/archive/** with a *-HISTORICAL filename + leave a pointer stub.",
      "Active docs must not state retired deploy facts as current (run the guard).",
      "Point provider/model claims at lib/ai/provider.ts; don't hardcode a model.",
    ],
    commands: ["pnpm check:stale-docs", "STALE_DOCS_STRICT=1 pnpm check:stale-docs"],
    gotchas: ["The guard exempts archive/, adr/, dated filenames, bannered files, and lines with a safe word within ±2 — mark history clearly so it's recognized."],
    verification: ["pnpm check:stale-docs reports 0 critical"],
    rollback: "git restore the doc; quarantines are git mv (reversible).",
    relatedFiles: ["scripts/check-stale-docs.ts", "docs/CURRENT-TRUTH.md"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "low",
    docPath: "docs/runbooks/stale-doc-cleanup.md",
  },
  {
    id: "action-honesty-and-receipts",
    title: "Action honesty — no false 'done' claims",
    domain: "ai-reliability",
    status: "active",
    whenToUse: "Touching chat finalization, tool results, or anything where Nick reports an action.",
    sourceOfTruth: ["lib/ai/system-prompt.ts", "lib/ai/chat/action-claim-detector.ts", "lib/ai/receipts/action-receipt.ts"],
    rules: [
      "Nick must not claim a past-tense action (created/sent/completed/updated) without a tool call that succeeded.",
      "A failed or missing tool result must surface as a visible failure, never be summarized as done.",
      "The fabrication-defense stack (L1-L5) is load-bearing — extend it, don't bypass it.",
    ],
    commands: ["pnpm test -- tests/ai/chat"],
    gotchas: ["The action-claim detector is regex-based; add new action verbs as they appear and re-run its test."],
    verification: ["action-claim-detector + receipts unit suites green"],
    rollback: "Revert; receipts are additive and not yet wired into the live finalize path.",
    relatedFiles: ["lib/ai/system-prompt.ts", "lib/ai/chat/action-claim-detector.ts", "lib/ai/chat/fabrication-rewriter.ts"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "medium",
    docPath: "docs/runbooks/action-honesty-and-receipts.md",
  },
  {
    id: "memory-evals",
    title: "Memory evals — the truth scoreboard",
    domain: "ai-evals",
    status: "active",
    whenToUse: "After changing a truth doc, or to check Statenour still knows its current truth.",
    sourceOfTruth: ["lib/evals/memory-evals.ts", "scripts/run-memory-evals.ts"],
    rules: [
      "Truth docs are graded for whether they TEACH expected facts (procedural knowledge); forbidden claims grade free-form answers, not docs.",
      "The runner is pure — it never mutates the DB and makes no external API call by default.",
      "Add an eval (with a groundingDoc) whenever a new current-truth fact must not regress.",
    ],
    commands: ["pnpm eval:memory", "pnpm test -- tests/lib/evals"],
    gotchas: ["Evals grounded against a runbook read as 'manual' until that runbook md exists on disk."],
    verification: ["pnpm eval:memory -> 0 critical fail", "tests/lib/evals green"],
    rollback: "Delete lib/evals/** + the eval:memory script line; nothing depends on it.",
    relatedFiles: ["lib/evals/memory-evals.ts", "lib/evals/memory-eval-runner.ts", "scripts/run-memory-evals.ts"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "low",
    docPath: "docs/runbooks/memory-evals.md",
  },
  {
    id: "nickstire-vs-statenour-boundary",
    title: "Nickstire vs Statenour boundary",
    domain: "monorepo",
    status: "active",
    whenToUse: "Working in the monorepo so you don't cross app boundaries or push the wrong gate.",
    sourceOfTruth: ["CLAUDE.md", "docs/REPO-MAP.md", "config/repos.ts"],
    rules: [
      "apps/statenour (-> bdnick.info) and apps/nickstire (-> nickstire.org) both deploy from main on Railway; keep changes scoped to one app.",
      "Stage only your app's files by explicit path; never git add -A on shared main.",
      "Both apps run as standalone iOS PWAs — window.confirm/alert/prompt are silently suppressed; use an in-DOM confirm.",
    ],
    commands: ["git add apps/statenour/<path>"],
    gotchas: ["The pre-push hook builds BOTH affected apps; the other session's broken tree can bounce your push — surface it, never --no-verify."],
    verification: ["only your app's files are staged", "pre-push turbo build green"],
    rollback: "Unstage foreign files; rebase on origin/main.",
    relatedFiles: ["config/repos.ts", "docs/REPO-MAP.md"],
    lastVerified: VERIFIED,
    owner: OWNER,
    riskLevel: "medium",
    docPath: "docs/runbooks/nickstire-vs-statenour-boundary.md",
  },
];
