import { z } from "zod";

export const CampaignInputSchema = z.object({
  offer: z.object({
    productOrServiceName: z.string(),
    niche: z.string(),
    primaryOutcome: z.string(),
    deliveryFormat: z.string(),
    whatsIncluded: z.string(),
    timeToConsumeOrFulfill: z.string(),
    commercialUseTerms: z.string().optional(),
    locationRequirement: z.string().optional(),
    serviceArea: z.string().optional(),
    appointmentRequired: z.boolean().optional(),
    emergencyOrUrgencyContext: z.string().optional(),
  }),
  priceStack: z.object({
    corePrice: z.string(),
    upsells: z.string().optional(),
    downsells: z.string().optional(),
    bundles: z.string().optional(),
    guaranteeOrRefundTerms: z.string(),
    bonuses: z.string().optional(),
    financingAvailable: z.boolean().optional(),
    depositRequired: z.string().optional(),
    paymentMethods: z.string().optional(),
  }),
  audience: z.object({
    whoItIsFor: z.string(),
    painPoints: z.string(),
    desires: z.string(),
    countries: z.array(z.string()),
    languages: z.array(z.string()),
    awarenessLevel: z.enum(["Unaware", "Problem Aware", "Solution Aware", "Product Aware", "Most Aware"]),
    dealBreakers: z.string().optional(),
    exclusions: z.string().optional(),
    localRadius: z.string().optional(),
    customerType: z.enum(["B2B", "B2C", "Both"]).optional(),
  }),
  assetsAndProof: z.object({
    testimonialsAvailable: z.boolean(),
    testimonialDetails: z.string().optional(),
    screenshotsAvailable: z.boolean(),
    caseStudiesAvailable: z.boolean(),
    beforeAfterAvailable: z.boolean(),
    founderFaceAvailable: z.boolean(),
    brandKitAvailable: z.boolean(),
    productVisuals: z.string().optional(),
    leadMagnetAvailable: z.boolean(),
    leadMagnetDescription: z.string().optional(),
    realReviewSources: z.string().optional(),
    allowedProofClaims: z.string().optional(),
    forbiddenProofClaims: z.string().optional(),
  }),
  constraints: z.object({
    dailyBudgetRange: z.string(),
    monthlyBudgetRange: z.string(),
    launchDate: z.string().optional(),
    brandVoice: z.string(),
    forbiddenWords: z.array(z.string()).optional(),
    forbiddenTopics: z.array(z.string()).optional(),
    trackingStack: z.array(z.string()).optional(),
    countriesToExclude: z.array(z.string()).optional(),
    timeCapacity: z.string().optional(),
    creativeProductionCapacity: z.string().optional(),
    complianceSensitivity: z.enum(["Low", "Medium", "High"]),
    approvalRequired: z.boolean().optional(),
    landingPageUrl: z.string().url().optional(),
    checkoutOrBookingUrl: z.string().url().optional(),
    phoneNumber: z.string().optional(),
    businessAddress: z.string().optional(),
  }),
  // Additional optional fields:
  businessProfile: z.string().optional(),
  serviceList: z.string().optional(),
  offerCategory: z.string().optional(),
  seasonality: z.string().optional(),
  competitors: z.string().optional(),
  existingCampaignNotes: z.string().optional(),
  previousCreativeResults: z.string().optional(),
  previousAdMetrics: z.string().optional(),
  pixelEventsAvailable: z.array(z.string()).optional(),
  capiAvailable: z.boolean().optional(),
  emailPlatform: z.string().optional(),
  crmIntegration: z.string().optional(),
  ga4Available: z.boolean().optional(),
  callTrackingAvailable: z.boolean().optional(),
});

export type CampaignInput = z.infer<typeof CampaignInputSchema>;
