import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import {
  bookingRouter,
  callbackRouter,
  leadRouter,
  chatRouter,
  contentRouter,
  contentAdminRouter,
  contentStudioRouter,
  adminDashboardRouter,
  analyticsRouter,
  followUpsRouter,
  weeklyReportRouter,
  weatherRouter,
  reviewsRouter,
  instagramRouter,
  searchRouter,
  diagnoseRouter,
  laborEstimateRouter,
  activityRouter,
  serviceReviewsRouter,
  couponsRouter,
  garageRouter,
  referralsRouter,
  qaRouter,
  customerNotificationsRouter,
  pricingRouter,
  inspectionRouter,
  loyaltyRouter,
  smsRouter,
  reviewRequestsRouter,
  remindersRouter,
  smsConversationsRouter,
  smsBotRouter,
  reviewRepliesRouter,
  localGrowthRouter,
  shareCardsRouter,
  galleryRouter,
  techniciansRouter,
  customersRouter,
  winbackRouter,
  shopdriverRouter,
  jobAssignmentsRouter,
  invoicesRouter,
  kpiRouter,
  portalRouter,
  gatewayTireRouter,
  autoLaborRouter,
  campaignsRouter,
  callTrackingRouter,
  customerEventsRouter,
  exportRouter,
  costEstimatorRouter,
  emergencyRouter,
  messengerBotRouter,
  financingRouter,
  nourOsBridgeRouter,
  workOrdersRouter,
  dispatchRouter,
  controlCenterRouter,
  estimatesRouter,
  nourOsQuoteRouter,
  segmentsRouter,
  serviceMatcherRouter,
  shopStatusRouter,
  specialsRouter,
  nickActionsRouter,
  paymentsRouter,
  featureFlagsRouter,
  intelligenceRouter,
  snapRouter,
  trafficFunnelRouter,
  seoToolsRouter,
  conversionRouter,
  smsPerformanceRouter,
  instagramAdminRouter,
  gbpRouter,
  smsOrchestratorRouter,
  socialPipelineRouter,
  metaAdsArchitectRouter,
} from "./routers/index";
import { voiceAgentRouter } from "./routers/voiceAgent";
import { vapiRouter } from "./routers/vapi";
import { revenueOpsRouter } from "./routers/revenueOps";
import { revenueAttributionRouter } from "./routers/revenueAttribution";
import { statenourMetricsRouter } from "./routers/statenourMetrics";
import { instagramStudioRouter } from "./routers/instagramStudio";
import { closedLoopRouter } from "./routers/closedLoop";
import { membershipsRouter } from "./routers/memberships";
import { adStudioRouter } from "./routers/adStudio";

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query((opts) => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),

  weather: weatherRouter,
  reviews: reviewsRouter,
  instagram: instagramRouter,
  instagramAdmin: instagramAdminRouter,
  instagramStudio: instagramStudioRouter,
  adStudio: adStudioRouter,
  search: searchRouter,
  diagnose: diagnoseRouter,
  laborEstimate: laborEstimateRouter,
  activity: activityRouter,
  serviceReviews: serviceReviewsRouter,
  voiceAgent: voiceAgentRouter,
  vapi: vapiRouter,
  revenueOps: revenueOpsRouter,
  revenueAttribution: revenueAttributionRouter,
  statenourMetrics: statenourMetricsRouter,
  costEstimator: costEstimatorRouter,
  content: contentRouter,

  booking: bookingRouter,
  callback: callbackRouter,
  lead: leadRouter,
  chat: chatRouter,
  coupons: couponsRouter,
  garage: garageRouter,
  referrals: referralsRouter,
  qa: qaRouter,
  pricing: pricingRouter,
  inspection: inspectionRouter,
  loyalty: loyaltyRouter,

  adminDashboard: adminDashboardRouter,
  contentAdmin: contentAdminRouter,
  contentStudio: contentStudioRouter,
  analytics: analyticsRouter,
  customerNotifications: customerNotificationsRouter,
  followUps: followUpsRouter,
  weeklyReport: weeklyReportRouter,
  sms: smsRouter,
  reviewRequests: reviewRequestsRouter,
  reminders: remindersRouter,
  smsConversations: smsConversationsRouter,
  smsBot: smsBotRouter,
  reviewReplies: reviewRepliesRouter,
  localGrowth: localGrowthRouter,
  gbp: gbpRouter,
  smsOrchestrator: smsOrchestratorRouter,
  shareCards: shareCardsRouter,
  gallery: galleryRouter,
  technicians: techniciansRouter,
  customers: customersRouter,
  winback: winbackRouter,
  shopdriver: shopdriverRouter,

  jobAssignments: jobAssignmentsRouter,
  invoices: invoicesRouter,
  kpi: kpiRouter,
  portal: portalRouter,

  callTracking: callTrackingRouter,
  customerEvents: customerEventsRouter,
  export: exportRouter,
  campaigns: campaignsRouter,
  gatewayTire: gatewayTireRouter,
  autoLabor: autoLaborRouter,
  emergency: emergencyRouter,
  messengerBot: messengerBotRouter,
  financing: financingRouter,
  nourOsBridge: nourOsBridgeRouter,
  workOrders: workOrdersRouter,
  dispatch: dispatchRouter,
  controlCenter: controlCenterRouter,
  estimates: estimatesRouter,
  segments: segmentsRouter,
  serviceMatcher: serviceMatcherRouter,
  shopStatus: shopStatusRouter,
  specials: specialsRouter,
  nourOsQuote: nourOsQuoteRouter,
  nickActions: nickActionsRouter,
  payments: paymentsRouter,
  featureFlags: featureFlagsRouter,
  memberships: membershipsRouter,
  intelligence: intelligenceRouter,
  snap: snapRouter,
  trafficFunnel: trafficFunnelRouter,
  conversion: conversionRouter,
  seoTools: seoToolsRouter,
  smsPerformance: smsPerformanceRouter,
  closedLoop: closedLoopRouter,
  socialPipeline: socialPipelineRouter,
  metaAdsArchitect: metaAdsArchitectRouter,
});

export type AppRouter = typeof appRouter;
