import type { PrismaClient } from "@prisma/client";

const laws = [
  {
    number: 1,
    title: "Never Outshine the Master",
    shortTitle: "Don't Outshine",
    essence: "Always make those above you feel comfortably superior. In your desire to please or impress, do not go too far in displaying your talents or you might accomplish the opposite — inspire fear and insecurity.",
    shopApplication: "At Nick's Tire & Auto, never make the shop owner look bad in front of customers. If a tech spots a diagnostic mistake by the lead, correct it privately. When Nour suggests a process change from afar, frame it as 'what do you think about trying X' rather than 'you're doing it wrong.' The moment a team member publicly corrects leadership in front of a customer, trust fractures and the shop culture degrades.",
    nourApplication: "When presenting NOUR OS to potential partners or investors, let them feel like their input shaped the product. Don't show up as the genius who built everything alone — frame collaborators as essential. In Cleveland business circles, the young owner who makes established players feel threatened gets frozen out. Make them feel like mentors, not competitors.",
    triggerPatterns: ["outshining_detected", "ego_display", "public_correction", "showing_off", "making_boss_look_bad"],
  },
  {
    number: 2,
    title: "Never Put Too Much Trust in Friends, Learn How to Use Enemies",
    shortTitle: "Use Enemies",
    essence: "Be wary of friends — they will betray you more quickly, for they are easily aroused to envy. Hire a former enemy and they will be more loyal than a friend, because they have more to prove.",
    shopApplication: "At Nick's Tire & Auto, the buddy you hired as a favor is often the one who steals parts, shows up late, or bad-mouths you to other techs. Meanwhile, the tech who came from a competitor's shop and has something to prove will outwork everyone. Don't staff based on friendship — staff based on hunger and accountability.",
    nourApplication: "In building NOUR OS, don't hand critical system access or partnerships to close friends just because they're friends. A developer or collaborator who once doubted the project and now sees its value will fight harder for it than a buddy doing you a favor. Channel rivalry into fuel — former doubters become your strongest advocates once converted.",
    triggerPatterns: ["blind_trust_friend", "loyalty_assumption", "enemy_opportunity", "friendship_bias", "trust_without_proof"],
  },
  {
    number: 3,
    title: "Conceal Your Intentions",
    shortTitle: "Hide Intent",
    essence: "Keep people off-balance and in the dark by never revealing the purpose behind your actions. If they have no clue what you are up to, they cannot prepare a defense. Guide them far enough down the wrong path before they realize your true aim.",
    shopApplication: "At Nick's Tire & Auto, if you're planning to drop a parts vendor for a better deal, don't announce it until the new contract is signed. If you're restructuring the tech team's workflow, introduce changes gradually rather than telegraphing a full overhaul that invites resistance. When a competitor asks about your pricing strategy at a trade event, smile and deflect — never reveal your margins or your next move.",
    nourApplication: "When building NOUR OS features that could disrupt competitors, don't announce roadmaps publicly. Let competitors discover your capabilities after launch, not before. In negotiations with potential partners or acquirers, reveal only what serves your position. The moment you show your full hand — your tech stack, your growth numbers, your expansion plans — you lose leverage. Keep your strategic cards face down until the moment of play.",
    triggerPatterns: ["premature_reveal", "showing_hand", "broadcasting_plans", "telegraphing_moves", "strategic_leak"],
  },
  {
    number: 4,
    title: "Always Say Less Than Necessary",
    shortTitle: "Say Less",
    essence: "When you are trying to impress people with words, the more you say, the more common you appear and the less in control. Even if you are saying something banal, it will seem original if you make it vague, open-ended, and sphinxlike. Powerful people impress and intimidate by saying less.",
    shopApplication: "At Nick's Tire & Auto, when a customer asks why a repair costs what it does, a concise confident answer builds more trust than a nervous over-explanation. 'The axle bearing is worn and the hub assembly needs replacement — here's the breakdown' beats a rambling five-minute monologue about every possible scenario. Train the front desk: fewer words, more authority. Over-explaining signals uncertainty.",
    nourApplication: "In meetings, pitches, and even text conversations, resist the urge to over-explain NOUR OS's architecture or your personal story. A short, confident statement about what the system does lands harder than a 20-minute technical deep-dive nobody asked for. On social media and in business circles, the person who posts less but with more weight commands more respect than the one who floods the feed. Let silence do the heavy lifting.",
    triggerPatterns: ["over_explaining", "excessive_talking", "verbal_diarrhea", "filling_silence", "nervous_rambling"],
  },
  {
    number: 5,
    title: "So Much Depends on Reputation — Guard It with Your Life",
    shortTitle: "Guard Reputation",
    essence: "Reputation is the cornerstone of power. Through reputation alone you can intimidate and win; once it slips, however, you are vulnerable and will be attacked on all sides. Make your reputation unassailable.",
    shopApplication: "At Nick's Tire & Auto, every Google review matters. One bad review left unanswered can cost dozens of customers. Respond to every review — positive or negative — professionally and quickly. Train techs to treat every car like it belongs to a reviewer, because it might. A shop's reputation in Cleveland spreads through word-of-mouth faster than any ad campaign.",
    nourApplication: "Guard the NOUR OS brand and your personal reputation in the Cleveland tech and business community obsessively. One public failure — a data breach, a broken promise, a botched demo — can undo years of credibility building. Be deliberate about what you attach your name to. Reputation compounds: protect it early and it becomes an asset that opens doors without you even knocking.",
    triggerPatterns: ["reputation_threat", "negative_review", "public_failure", "brand_damage", "credibility_risk"],
  },
  {
    number: 6,
    title: "Court Attention at All Costs",
    shortTitle: "Court Attention",
    essence: "Everything is judged by its appearance; what is unseen counts for nothing. Never let yourself get lost in the crowd or buried in obscurity. Stand out. Be conspicuous at all costs. Make yourself a magnet of attention by appearing larger, more colorful, more mysterious than the bland and timid masses.",
    shopApplication: "At Nick's Tire & Auto, the shop that blends in with every other tire shop on the block dies slowly. Create a distinct brand presence — bold signage, wrapped vehicles, social media content showing real work being done. Sponsor local events, host a car care clinic, partner with Cleveland car clubs. The shop that people talk about is the shop that stays booked. Attention is revenue.",
    nourApplication: "NOUR OS can't succeed in obscurity. Build in public when strategic — share wins, demo features, post behind-the-scenes content. In Cleveland's business scene, be the person people remember from every event, not because you were loud, but because you were distinct. Craft a personal brand that's impossible to ignore: the young owner building AI for auto shops. That story is magnetic — use it. The tech founder who hides gets zero inbound opportunities.",
    triggerPatterns: ["invisibility_risk", "blending_in", "obscurity_detected", "attention_deficit", "brand_silence"],
  },
  {
    number: 7,
    title: "Get Others to Do the Work for You, but Always Take the Credit",
    shortTitle: "Leverage Others",
    essence: "Use the wisdom, knowledge, and legwork of other people to further your own cause. Not only will such assistance save you valuable time and energy, it will give you a godlike aura of efficiency and speed.",
    shopApplication: "At Nick's Tire & Auto, delegate diagnostic write-ups to the service advisor, let techs handle the physical labor, and use NOUR OS to automate scheduling and follow-ups. The owner's job isn't to turn wrenches — it's to orchestrate the operation. When a customer praises the shop, accept it graciously as the business you built, even if tech #3 did the actual repair.",
    nourApplication: "Use open-source libraries, AI tools, and contract developers to accelerate NOUR OS development. You don't need to write every line of code — you need to architect the vision and ship the product. When presenting the system, own the vision and the outcome. Credit the team internally, but externally, you are the face and architect of NOUR OS.",
    triggerPatterns: ["doing_all_work", "no_delegation", "micromanaging", "credit_diffusion", "solo_grinding"],
  },
  {
    number: 8,
    title: "Make Other People Come to You — Use Bait if Necessary",
    shortTitle: "Draw Them In",
    essence: "When you force the other person to act, you are the one in control. It is always better to make your opponent come to you, abandoning his own plans in the process. Lure him with fabulous gains — then attack.",
    shopApplication: "At Nick's Tire & Auto, don't chase customers with desperate discounts. Instead, create irresistible offers that pull them in — free tire inspections before winter, seasonal check-up specials, loyalty programs that reward return visits. When a competitor tries to poach your techs, don't counter-offer immediately — let them come back when they realize the grass wasn't greener. Position the shop so people come to you.",
    nourApplication: "Don't cold-pitch NOUR OS to every shop owner you meet. Build something so compelling that shop owners hear about it and reach out. Create case studies, demo videos, and word-of-mouth buzz that makes inbound leads come to you. In negotiations, the party who initiates is usually the party with less leverage. Make partners, investors, and clients come to your table.",
    triggerPatterns: ["chasing_clients", "desperate_outreach", "begging_position", "no_inbound", "pursuing_too_hard"],
  },
  {
    number: 9,
    title: "Win Through Your Actions, Never Through Argument",
    shortTitle: "Actions Over Arguments",
    essence: "Any momentary triumph you think you have gained through argument is really a Pyrrhic victory. The resentment and ill will you stir up is stronger and lasts longer than any momentary change of opinion. It is much more powerful to get others to agree with you through your actions.",
    shopApplication: "At Nick's Tire & Auto, when a customer disputes a diagnosis, don't argue — show them. Walk them to the lift, point at the worn brake pad, let them see the metal-on-metal. When a tech disagrees with a process change, don't lecture — run both methods side by side and let the results speak. Arguments create enemies; demonstrations create believers.",
    nourApplication: "When someone doubts NOUR OS or questions your ability to run a business remotely, don't argue your case — show the dashboard, the metrics, the automated workflows humming along. Build the proof into the product itself. Every feature that works flawlessly is a stronger argument than any pitch deck. Let results silence skeptics.",
    triggerPatterns: ["arguing_detected", "verbal_conflict", "trying_to_convince", "debate_escalation", "proving_point_verbally"],
  },
  {
    number: 10,
    title: "Infection: Avoid the Unhappy and Unlucky",
    shortTitle: "Avoid Toxic People",
    essence: "You can die from someone else's misery — emotional states are as infectious as diseases. The perpetually miserable will drag you down with them. Associate with the happy and fortunate instead.",
    shopApplication: "At Nick's Tire & Auto, one chronically negative tech can poison the entire shop floor. The guy who complains about every job, every customer, every Monday — he's not just unhappy, he's contagious. Address it directly or remove him before the rot spreads. Hire for attitude first, skill second. A positive shop culture is a competitive advantage that toxic people destroy from the inside.",
    nourApplication: "In your personal and professional circles, ruthlessly audit who gets your time and energy. The friend who always has drama, the contact who only calls with problems, the online community drowning in negativity — these are infections. Surround yourself with builders, optimists, and people who are actively winning. Their energy compounds just like the negative energy does, but in your favor.",
    triggerPatterns: ["toxic_association", "negative_influence", "misery_contagion", "draining_relationship", "chronic_complainer"],
  },
  {
    number: 11,
    title: "Learn to Keep People Dependent on You",
    shortTitle: "Create Dependency",
    essence: "To maintain your independence you must always be needed and wanted. The more you are relied on, the more freedom you have. Make people depend on you for their happiness and prosperity, and you have nothing to fear.",
    shopApplication: "At Nick's Tire & Auto, become the shop that customers can't imagine going anywhere else. Build relationships where they trust only your techs with their vehicles. Offer services competitors don't — mobile diagnostics, real-time repair updates via text, a loyalty program that rewards long-term customers. When vendors depend on your volume, you negotiate from strength. When techs depend on your shop's culture and pay, retention is easy.",
    nourApplication: "Make NOUR OS indispensable to the shops that use it. Build deep integrations into their daily workflow so switching costs are enormous. In your personal network, be the person who connects people, solves problems, and creates opportunities — the node everyone routes through. The more people depend on your value, the more secure and free you become.",
    triggerPatterns: ["easily_replaceable", "no_dependency_created", "commodity_position", "low_switching_cost", "dispensable_role"],
  },
  {
    number: 12,
    title: "Use Selective Honesty and Generosity to Disarm Your Victim",
    shortTitle: "Selective Honesty",
    essence: "One sincere and honest move will cover over dozens of dishonest ones. Open-hearted gestures of honesty and generosity bring down the guard of even the most suspicious people. Once your selective honesty opens a hole in their armor, you can deceive and manipulate them at will.",
    shopApplication: "At Nick's Tire & Auto, when you honestly tell a customer 'your brakes are fine, you don't need new ones yet,' that moment of honesty earns trust that pays back tenfold when they do need a major repair. Be genuinely transparent about what's necessary versus what's optional — this disarms the skeptical customer who's been burned by other shops. One honest call builds a lifetime customer.",
    nourApplication: "When building business relationships, lead with genuine value before asking for anything. Give a potential partner a free insight, share useful data, or solve a small problem at no cost. This generosity disarms suspicion and opens doors that a cold pitch never would. In the tech world, open-sourcing a small tool or sharing knowledge freely builds trust that pays dividends later.",
    triggerPatterns: ["trust_building_opportunity", "disarming_moment", "honesty_leverage", "generosity_tactic", "guard_lowering"],
  },
  {
    number: 13,
    title: "When Asking for Help, Appeal to People's Self-Interest",
    shortTitle: "Appeal to Self-Interest",
    essence: "If you need to turn to an ally for help, do not bother to remind him of your past assistance and good deeds. He will find a way to ignore you. Instead, uncover something in your request that will benefit him, and emphasize it out of all proportion.",
    shopApplication: "At Nick's Tire & Auto, when negotiating with a parts supplier for better pricing, don't say 'we've been loyal customers for years.' Say 'we're expanding our fleet accounts and projecting 40% more volume next quarter — let's talk about pricing that makes us your biggest account in Cleveland.' Frame every ask around what the other party gains, not what you deserve.",
    nourApplication: "When pitching NOUR OS to a potential investor or partner, don't lead with 'I've worked so hard on this.' Lead with 'here's how this makes you money' or 'here's the market gap only we can fill.' People help when helping serves them. Frame every request around the other person's upside, not your need.",
    triggerPatterns: ["begging_for_help", "guilt_tripping", "reminding_past_favors", "self_centered_ask", "ignoring_their_interest"],
  },
  {
    number: 14,
    title: "Pose as a Friend, Work as a Spy",
    shortTitle: "Friendly Spy",
    essence: "Knowing about your rival is critical. Use spies to gather valuable information that will keep you a step ahead. Better still: play the spy yourself. In polite social encounters, learn to probe and find valuable information.",
    shopApplication: "At Nick's Tire & Auto, visit competitor shops as a 'customer' to see their pricing, wait times, customer experience, and facility quality. Chat with their techs at industry events — people love to talk about their frustrations. Monitor their Google reviews and social media for intelligence on their weaknesses. Every piece of competitive intel helps you position the shop better.",
    nourApplication: "Attend industry events, join auto shop owner forums, and engage with potential competitors' products — not to copy, but to understand the landscape. When meeting other tech founders, ask thoughtful questions that reveal their strategy, funding situation, and pain points. Information is leverage, and the best intelligence comes from friendly conversation, not formal research.",
    triggerPatterns: ["competitive_intel_needed", "information_gathering", "rival_assessment", "social_probing", "market_intelligence"],
  },
  {
    number: 15,
    title: "Crush Your Enemy Totally",
    shortTitle: "Crush Completely",
    essence: "All great leaders since Moses have known that a feared enemy must be crushed completely. If one ember is left alight, no matter how dimly it smolders, a fire will eventually break out. More is lost through stopping halfway than through total annihilation. The enemy will recover and seek revenge. Crush him totally.",
    shopApplication: "At Nick's Tire & Auto, if a competitor is spreading lies about your shop, undercutting with predatory pricing, or poaching your techs — don't respond with half-measures. Dominate the local SEO, lock down your best techs with retention packages, flood the market with your brand presence, and outservice them on every metric. A wounded competitor is more dangerous than a defeated one. If you're going to compete, compete to win decisively, not to coexist uncomfortably.",
    nourApplication: "When NOUR OS faces a direct competitor in the auto shop management space, don't aim for market share — aim for market dominance in your niche. Half-hearted competition leaves room for rivals to regroup, copy your features, and outspend you. If you identify a beatable competitor, outship them, out-market them, and capture their customers before they can pivot. In personal conflicts, don't leave loose ends that fester — resolve situations completely or they come back worse.",
    triggerPatterns: ["half_measures", "incomplete_victory", "lingering_threat", "wounded_enemy", "unfinished_conflict"],
  },
  {
    number: 16,
    title: "Use Absence to Increase Respect and Honor",
    shortTitle: "Strategic Absence",
    essence: "Too much circulation makes the price go down. The more you are seen and heard from, the more common you appear. If you are already established in a group, temporary withdrawal from it will make you more talked about, even more admired. You must learn when to leave. Create value through scarcity.",
    shopApplication: "At Nick's Tire & Auto, don't be the owner who's always hovering on the shop floor micromanaging. Strategic absence forces the team to step up, make decisions, and own their work. When you return, your presence carries more weight. For customers, limited-time offers and seasonal specials create urgency precisely because they're not always available. Scarcity drives action — in pricing and in presence.",
    nourApplication: "As a remote shop owner, your physical absence is already built in — leverage it as a strategic advantage rather than a weakness. When you do visit Cleveland or appear at events, it's an event in itself. In the NOUR OS community and on social media, don't post every day — post when you have something meaningful. Strategic silence makes your next move more impactful. The founder who's always available is taken for granted; the one who appears selectively commands attention.",
    triggerPatterns: ["overexposure", "too_available", "constant_presence", "diminishing_returns", "scarcity_opportunity"],
  },
  {
    number: 17,
    title: "Keep Others in Suspended Terror: Cultivate an Air of Unpredictability",
    shortTitle: "Be Unpredictable",
    essence: "Humans are creatures of habit with an insatiable need to see familiarity in other people's actions. Your predictability gives them a sense of control. Turn the tables: be deliberately unpredictable. Behavior that seems to have no consistency or purpose will keep them off-balance.",
    shopApplication: "At Nick's Tire & Auto, don't let competitors predict your moves. Surprise the market with an unexpected service offering, a flash promotion, or a partnership nobody saw coming. Internally, occasional unannounced quality checks keep the team sharp — not out of fear, but because they know standards matter every day, not just during scheduled reviews.",
    nourApplication: "In business negotiations, don't be the founder whose every move is predictable. Sometimes launch a feature with no announcement. Sometimes go silent for weeks then drop something major. Unpredictability in your professional moves keeps competitors guessing and keeps your audience engaged. Predictable founders get ignored; surprising ones get watched.",
    triggerPatterns: ["predictable_pattern", "routine_detected", "expected_behavior", "no_surprise_element", "competitor_anticipating"],
  },
  {
    number: 18,
    title: "Do Not Build Fortresses to Protect Yourself — Isolation Is Dangerous",
    shortTitle: "Avoid Isolation",
    essence: "The world is dangerous and enemies are everywhere — everyone has to protect themselves. A fortress seems the safest. But isolation exposes you to more dangers than it protects you from. Better to circulate among people, find allies, and mingle.",
    shopApplication: "At Nick's Tire & Auto, don't operate the shop as an island. Join the local chamber of commerce, attend SEMA or AAPEX, connect with other shop owners through industry groups. The shop owner who isolates himself from the industry misses trends, pricing shifts, and partnership opportunities. Build relationships with other shops — even competitors — because the network protects you more than walls do.",
    nourApplication: "Don't build NOUR OS in a vacuum. Engage with the auto shop community, attend conferences, participate in forums, and build relationships with potential users before the product is 'ready.' The isolated founder builds what nobody wants. The connected founder builds what the market is begging for. Remote work is not isolation — it's only isolation if you stop connecting with people.",
    triggerPatterns: ["self_isolation", "fortress_mentality", "avoiding_networking", "hermit_mode", "disconnection"],
  },
  {
    number: 19,
    title: "Know Who You're Dealing with — Do Not Offend the Wrong Person",
    shortTitle: "Know Your Target",
    essence: "There are many different kinds of people in the world, and you can never assume that everyone will react to your strategies in the same way. Deceive or outmaneuver some people and they will spend the rest of their lives seeking revenge. Choose your victims and opponents carefully.",
    shopApplication: "At Nick's Tire & Auto, not every difficult customer should be handled the same way. The Karen who posts one bad review and moves on is different from the connected business owner who sits on the local BBB board and has 10,000 followers. Know who you're dealing with before you push back. Similarly, don't lowball a vendor who has exclusive distribution on the parts you need most — they'll remember.",
    nourApplication: "In the Cleveland business ecosystem, research people before you negotiate hard or turn down requests. The quiet guy at the networking event might be the biggest fleet owner in Northeast Ohio. The investor you dismissed might be best friends with your next target partner. In tech, the developer you treat poorly today might be the hiring manager at a company you need tomorrow. Always know the terrain before you step.",
    triggerPatterns: ["unknown_opponent", "blind_offense", "underestimating_target", "careless_dismissal", "wrong_enemy"],
  },
  {
    number: 20,
    title: "Do Not Commit to Anyone",
    shortTitle: "Stay Uncommitted",
    essence: "It is the fool who always rushes to take sides. Do not commit to any side or cause but yourself. By maintaining your independence, you become the master of others — playing people against each other, making them pursue you.",
    shopApplication: "At Nick's Tire & Auto, don't lock into exclusive vendor agreements unless the terms are overwhelmingly in your favor. Keep multiple tire distributors competing for your business. Don't publicly ally with one competitor against another — stay neutral and let them come to you. The shop that stays flexible in its partnerships always gets the best deals because vendors know they can be replaced.",
    nourApplication: "Don't commit NOUR OS exclusively to one platform, one investor, or one market segment too early. Keep options open, let multiple parties compete for your attention, and maintain leverage by being the prize everyone wants to lock down. In personal relationships and business partnerships, premature commitment removes the leverage that comes from being courted.",
    triggerPatterns: ["premature_commitment", "exclusive_lock_in", "taking_sides", "losing_leverage", "over_attachment"],
  },
  {
    number: 21,
    title: "Play a Sucker to Catch a Sucker — Seem Dumber Than Your Mark",
    shortTitle: "Play Dumb",
    essence: "No one likes feeling stupider than the next person. The trick is to make your victims feel smart — and not just smart, but smarter than you are. Once convinced of this, they will never suspect that you may have ulterior motives.",
    shopApplication: "At Nick's Tire & Auto, when a parts vendor tries to oversell you on premium inventory, play along — ask naive questions, let them explain their pitch fully, and then use the information to negotiate from a position of knowledge they didn't expect you to have. When a competitor brags about their new equipment, nod and ask questions — they'll reveal more than they should.",
    nourApplication: "In tech conversations with potential competitors or investors, sometimes it pays to underplay your technical depth. Let people underestimate NOUR OS's capabilities. When they discover the reality, the surprise factor amplifies impact. The founder who seems humble and curious gets more honest information than the one who leads with brilliance. Use perceived naivety as a tool for intelligence gathering.",
    triggerPatterns: ["showing_full_hand", "appearing_too_smart", "intimidating_target", "missing_intel_opportunity", "ego_blocking_strategy"],
  },
  {
    number: 22,
    title: "Use the Surrender Tactic: Transform Weakness into Power",
    shortTitle: "Strategic Surrender",
    essence: "When you are weaker, never fight for honor's sake; choose surrender instead. Surrender gives you time to recover, time to torment and irritate your conqueror, time to wait for his power to wane. Do not give him the satisfaction of fighting and defeating you.",
    shopApplication: "At Nick's Tire & Auto, if a major competitor opens next door with deeper pockets, don't engage in a price war you'll lose. Yield the low-margin commodity work, focus on what they can't copy — relationships, specialized services, superior customer experience. Sometimes accepting a short-term loss positions you for a long-term win. Surviving is winning when the other guy is burning cash.",
    nourApplication: "If a well-funded competitor enters the auto shop management software space, don't try to outspend them. Yield the broad market and dominate a niche they're ignoring. Use the time to build deeper features, stronger relationships, and a more loyal user base. Strategic retreat is not defeat — it's repositioning for a stronger attack when the timing is right.",
    triggerPatterns: ["fighting_losing_battle", "ego_driven_conflict", "refusing_retreat", "wasting_resources", "pride_over_strategy"],
  },
  {
    number: 23,
    title: "Concentrate Your Forces",
    shortTitle: "Concentrate Forces",
    essence: "Conserve your forces and energies by keeping them concentrated at their strongest point. You gain more by finding a rich mine and mining it deeper than by flitting from one shallow mine to another. Intensity defeats extensity every time.",
    shopApplication: "At Nick's Tire & Auto, don't try to be everything — tires, body work, custom exhaust, detailing, window tinting. Master your core services and dominate them. A shop that does five things excellently beats one that does fifteen things mediocrely. Focus marketing spend on your highest-margin, highest-demand services rather than spreading thin across every category.",
    nourApplication: "With NOUR OS, focus on one vertical — auto shop management — and dominate it before expanding to other industries. Don't scatter development resources across ten features; ship three features that are genuinely best-in-class. Your time, money, and energy are finite. Concentrate them on the highest-leverage activities and say no to everything else until those are won.",
    triggerPatterns: ["spreading_thin", "lack_of_focus", "too_many_projects", "scattered_resources", "diluted_effort"],
  },
  {
    number: 24,
    title: "Play the Perfect Courtier",
    shortTitle: "Perfect Courtier",
    essence: "The perfect courtier thrives in a world where everything revolves around power and political dexterity. He masters the art of indirection; he flatters, yields to superiors, and asserts power over others in the most oblique and graceful manner.",
    shopApplication: "At Nick's Tire & Auto, the best service advisor is a courtier — they read the customer's mood, adapt their communication style, upsell without pressure, and make every customer feel like the most important person in the shop. Train your front-of-house team in this art. The tech who can explain a repair to a grandmother differently than to a car enthusiast is worth their weight in gold.",
    nourApplication: "Navigate Cleveland's business and social circles with finesse. Know when to be bold and when to be diplomatic. Adapt your communication style to your audience — investors want metrics, shop owners want practical value, developers want technical depth. The ability to read a room and adjust is the meta-skill that makes all other skills more effective.",
    triggerPatterns: ["social_clumsiness", "tone_deaf_communication", "failing_to_adapt", "political_misstep", "blunt_approach"],
  },
  {
    number: 25,
    title: "Re-Create Yourself",
    shortTitle: "Reinvent Yourself",
    essence: "Do not accept the roles that society foists on you. Re-create yourself by forging a new identity, one that commands attention and never bores the audience. Be the master of your own image rather than letting others define it for you. Incorporate dramatic devices into your public gestures and actions.",
    shopApplication: "At Nick's Tire & Auto, periodically reinvent the shop's brand and customer experience. Refresh the waiting area, update the website, introduce new services, rebrand your social media presence. A shop that looks and feels the same as it did five years ago signals stagnation. The market rewards evolution. Reinvent the customer experience before customers outgrow you and find a shop that feels more modern.",
    nourApplication: "You're not just 'a shop owner' or 'a developer' — you're building an entirely new category: the AI-powered remote shop operator. Craft that identity deliberately. Control your narrative before others define you. Reinvent your personal brand as you level up — the Nour who started is not the Nour who scales NOUR OS to multiple locations. Each phase of growth demands a new version of yourself. Shed old identities that no longer serve the mission.",
    triggerPatterns: ["identity_stagnation", "outdated_brand", "being_defined_by_others", "refusing_evolution", "static_image"],
  },
  {
    number: 26,
    title: "Keep Your Hands Clean",
    shortTitle: "Clean Hands",
    essence: "You must seem a paragon of civility and efficiency: your hands are never soiled by mistakes and nasty deeds. Maintain such a spotless appearance by using others as scapegoats and cat's-paws to disguise your involvement.",
    shopApplication: "At Nick's Tire & Auto, if a policy change will be unpopular — like stricter clock-in rules or reduced overtime — let the shop manager announce and enforce it. If a customer needs to hear bad news about a repair cost, let the service advisor deliver it while you step in as the 'good cop' offering a discount. The owner's hands stay clean, relationships intact, while necessary decisions still get made.",
    nourApplication: "When NOUR OS needs to make tough calls — dropping a feature users liked, raising prices, ending a partnership — use process and policy as the shield rather than making it personal. 'Our data shows this feature isn't serving users well' lands better than 'I decided to cut it.' Let systems and data take the heat while you maintain your reputation as a thoughtful, user-first founder.",
    triggerPatterns: ["getting_hands_dirty", "personal_blame_risk", "direct_confrontation", "reputation_exposure", "visible_dirty_work"],
  },
  {
    number: 27,
    title: "Play on People's Need to Believe to Create a Cultlike Following",
    shortTitle: "Create Following",
    essence: "People have an overwhelming desire to believe in something. Become the focal point of such desire by offering them a cause, a new faith to follow. Keep your words vague but full of promise; emphasize enthusiasm over rationality and clear thinking. Give your new disciples rituals to perform, and ask them to make sacrifices on your behalf.",
    shopApplication: "At Nick's Tire & Auto, build a culture that techs and customers believe in — not just a job or a service, but a mission. 'We keep Cleveland's families safe on the road' is a cause, not just a tagline. Create rituals: team huddles every morning, customer appreciation days quarterly, tech certifications celebrated publicly. People don't stay loyal to a tire shop — they stay loyal to a community and a mission.",
    nourApplication: "Build NOUR OS as more than software — build it as a movement. 'The future of shop management is AI-powered and owner-first.' Give early adopters a sense of belonging — beta tester communities, exclusive access, a voice in the roadmap. People who feel like they're part of building something will evangelize it for free. Cult-like loyalty isn't built on features; it's built on identity and belonging.",
    triggerPatterns: ["no_mission_defined", "transactional_relationship", "lacking_community", "feature_only_focus", "no_belief_system"],
  },
  {
    number: 28,
    title: "Enter Action with Boldness",
    shortTitle: "Act Boldly",
    essence: "If you are unsure of a course of action, do not attempt it. Your doubts and hesitations will infect your execution. Timidity is dangerous: better to enter with boldness. Any mistakes you commit through audacity are easily corrected with more audacity. Everyone admires the bold; no one honors the timid.",
    shopApplication: "At Nick's Tire & Auto, when you decide to expand services, raise prices, or rebrand — do it fully and confidently. A half-hearted price increase with apologetic language invites pushback. A bold one with clear value communication gets accepted. When launching a new service like mobile diagnostics, go all in with marketing, training, and equipment rather than testing it timidly. Bold moves generate momentum; timid ones generate doubt.",
    nourApplication: "Launch NOUR OS features with confidence, not caveats. Ship boldly, market boldly, price boldly. The founder who says 'we think this might work' inspires zero confidence. The one who says 'this changes everything for shop owners' commands attention. When making career or business moves — leaving a job, signing a lease, hiring a key person — commit fully. Hesitation is the enemy of execution. Boldness has a momentum that timidity can never match.",
    triggerPatterns: ["hesitation_detected", "timid_action", "half_commitment", "doubt_paralysis", "weak_launch"],
  },
  {
    number: 29,
    title: "Plan All the Way to the End",
    shortTitle: "Plan to End",
    essence: "The ending is everything. Plan all the way to it, taking into account all the possible consequences, obstacles, and twists of fortune that might reverse your hard work and give the glory to others. By planning to the end you will not be overwhelmed by circumstances and you will know when to stop.",
    shopApplication: "At Nick's Tire & Auto, before launching a promotion, plan the entire lifecycle: how it starts, how you handle the rush, what happens when inventory runs low, how you transition customers to full-price services after. Before hiring a new tech, plan not just the hire but the 90-day ramp, the training path, and the contingency if they don't work out. Every initiative needs an end-state vision, not just a starting gun.",
    nourApplication: "Before building any NOUR OS feature, plan from concept through deployment to maintenance to eventual deprecation. Before entering a market, plan the full arc: launch, growth, competition response, scaling, and exit options. Think three moves ahead in every negotiation. The founder who plans only the next step gets surprised by step three. The one who plans to the endgame controls the entire board. Reverse-engineer every goal from the finish line backward.",
    triggerPatterns: ["no_endgame", "short_term_thinking", "unplanned_initiative", "reactive_mode", "no_exit_strategy"],
  },
  {
    number: 30,
    title: "Make Your Accomplishments Seem Effortless",
    shortTitle: "Seem Effortless",
    essence: "Your actions must seem natural and executed with ease. All the toil and practice that go into them, and also all the clever tricks, must be concealed. When you act, act effortlessly, as if you could do much more. Avoid the temptation of revealing how hard you work — that only raises questions.",
    shopApplication: "At Nick's Tire & Auto, the customer should never see the chaos behind the curtain. The seamless experience — greeting, diagnosis, quote, repair, payment, follow-up — should feel smooth and professional even when the back end is scrambling. Don't tell customers 'we had to move mountains to get your part.' Just deliver excellence and let them assume it's how you always operate.",
    nourApplication: "Present NOUR OS and your accomplishments with calm confidence, not with war stories about all-nighters and debugging marathons. The perception of effortless competence is more powerful than the perception of grinding struggle. Let the product speak — clean UI, smooth workflows, reliable performance. Nobody needs to know about the three refactors it took to get there. Effortlessness is a brand, not a reality.",
    triggerPatterns: ["showing_struggle", "complaining_about_work", "revealing_effort", "seeking_sympathy", "visible_grind"],
  },
  {
    number: 31,
    title: "Control the Options: Get Others to Play with the Cards You Deal",
    shortTitle: "Control Options",
    essence: "The best deceptions are the ones that seem to give the other person a choice. Give people options that come out in your favor whichever one they choose. Force them to make choices between the lesser of two evils, both of which serve your purpose.",
    shopApplication: "At Nick's Tire & Auto, train service advisors to present repair options strategically: 'You can do the basic brake job for $300 or the complete brake service with rotor resurfacing for $450 — most customers choose the complete service for peace of mind.' Both options are profitable, but framing guides the customer toward the higher-value choice. Never present a single option — always offer a menu you've designed.",
    nourApplication: "When negotiating partnerships or pricing for NOUR OS, present options that all serve your interests. 'You can go with the standard plan at $X or the premium with analytics at $Y' — both are wins for you. In any negotiation, control the frame by defining the choices. The person who sets the menu controls the meal. Never let the other party define your options for you.",
    triggerPatterns: ["losing_frame_control", "single_option_presented", "opponent_setting_terms", "reactive_negotiation", "uncontrolled_choices"],
  },
  {
    number: 32,
    title: "Play to People's Fantasies",
    shortTitle: "Sell the Fantasy",
    essence: "The truth is often avoided because it is ugly and unpleasant. Never appeal to truth and reality unless you are prepared for the anger that comes from disenchantment. Life is so harsh and distressing that people who can manufacture romance or conjure up fantasy are like oases in the desert.",
    shopApplication: "At Nick's Tire & Auto, customers don't want to hear about the technical complexity of their repair — they want to hear that their car will be safe, reliable, and ready for their family road trip. Sell the outcome, not the process. 'Your kids will be safe in this car' hits harder than 'we replaced the CV joint and rebalanced the driveshaft.' The fantasy of worry-free driving is what they're actually buying.",
    nourApplication: "When pitching NOUR OS, don't lead with database schemas and API endpoints. Sell the fantasy: 'Imagine managing your shop from your phone while sitting on a beach — every metric, every customer interaction, every dollar, in real time.' The vision sells; the technical details close. People invest in dreams, not documentation. Paint the picture of what life looks like with NOUR OS, not what the code looks like under the hood.",
    triggerPatterns: ["too_technical", "killing_the_dream", "harsh_reality_dump", "no_vision_casting", "boring_pitch"],
  },
  {
    number: 33,
    title: "Discover Each Man's Thumbscrew",
    shortTitle: "Find Leverage",
    essence: "Everyone has a weakness, a gap in the castle wall. That weakness is usually an insecurity, an uncontrollable emotion or need; it can also be a small secret pleasure. Either way, once found, it is a thumbscrew you can turn to your advantage.",
    shopApplication: "At Nick's Tire & Auto, every vendor, competitor, and difficult customer has a pressure point. The vendor who's behind on quarterly targets will give you better pricing in the last week of the quarter. The competitor whose best tech is underpaid is vulnerable to a poaching offer. The angry customer who just wants to feel heard will become your biggest advocate once you acknowledge their frustration. Find the thumbscrew — not to exploit maliciously, but to navigate strategically.",
    nourApplication: "In every negotiation and relationship, understand what the other person truly wants — not what they say they want, but what drives them underneath. The investor motivated by FOMO, the partner motivated by status, the competitor motivated by fear. Once you understand the underlying driver, you can position NOUR OS and yourself to align with their deepest motivation. This isn't manipulation — it's strategic empathy applied with precision.",
    triggerPatterns: ["missing_leverage", "surface_level_negotiation", "ignoring_motivation", "no_pressure_point", "blind_negotiation"],
  },
  {
    number: 34,
    title: "Be Royal in Your Own Fashion: Act Like a King to Be Treated Like One",
    shortTitle: "Act Royal",
    essence: "The way you carry yourself will often determine how you are treated. In the long run, appearing vulgar or common will make people disrespect you. A king respects himself and inspires the same sentiment in others. By acting regally and confident of your powers, you make yourself seem destined to wear a crown.",
    shopApplication: "At Nick's Tire & Auto, the shop's presentation reflects ownership standards. A clean, organized shop with professional signage, uniformed techs, and a well-maintained waiting area commands premium pricing. Customers pay more at a shop that looks and feels premium. The owner who treats the business as a serious enterprise — not a grease pit — attracts better customers, better techs, and better vendor terms.",
    nourApplication: "Carry yourself as the founder of a serious technology company, not a hobbyist coding in his spare time. Professional communication, clean branding, polished demos, and confident pricing signal that NOUR OS is a real product worth investing in. How you present yourself in every interaction — email signature, LinkedIn profile, business cards, conference presence — shapes how people value you and your work. Demand respect through presence, not words.",
    triggerPatterns: ["self_deprecation", "undervaluing_self", "unprofessional_image", "cheap_presentation", "low_status_signals"],
  },
  {
    number: 35,
    title: "Master the Art of Timing",
    shortTitle: "Master Timing",
    essence: "Never seem to be in a hurry — hurrying betrays a lack of control over yourself and over time. Always seem patient, as if you know that everything will come to you eventually. Become a detective of the right moment; sniff out the spirit of the times, the trends that will carry you to power.",
    shopApplication: "At Nick's Tire & Auto, timing is everything — launch winter tire promotions before the first snowfall, not after. Stock up on AC parts before summer hits. Time your price increases with rising industry costs so they feel justified. Don't rush to fill a tech position with a bad hire; wait for the right candidate even if it means short-term pain. The shops that time their moves with the market outperform those that react to it.",
    nourApplication: "Time NOUR OS releases to market conditions and industry events. Don't launch a major feature on a holiday weekend. Don't pitch investors during market downturns unless you have exceptional leverage. In personal growth, recognize that some skills and opportunities require patience — rushing to scale before the product is ready burns credibility that takes years to rebuild. Master the difference between strategic patience and procrastination.",
    triggerPatterns: ["bad_timing", "rushing_decision", "missing_window", "impatient_action", "ignoring_market_timing"],
  },
  {
    number: 36,
    title: "Disdain Things You Cannot Have — Ignoring Them Is the Best Revenge",
    shortTitle: "Disdain the Unattainable",
    essence: "By acknowledging a petty problem you give it existence and credibility. The more attention you pay an enemy, the stronger you make him. The unattainable is more easily attained by seeming to disdain it. If there is something you want but cannot have, show contempt for it. The less interest you reveal, the more superior you seem.",
    shopApplication: "At Nick's Tire & Auto, if a competitor wins a fleet contract you wanted, don't obsess or bad-mouth them. Act as if it was never a priority. If a customer leaves for another shop, don't chase them desperately — maintain dignity and focus on serving the customers who chose you. Chasing what you've lost projects weakness. Indifference to setbacks projects strength that attracts better opportunities. The shop that appears unbothered by competition appears unbeatable.",
    nourApplication: "If a feature request is beyond current scope, if a competitor raises a round you couldn't, if a partnership falls through — don't dwell publicly. Show indifference to what you can't control and double down on what you can. The founder who obsesses over competitors on Twitter looks insecure. The one who ignores noise and ships product looks unstoppable. What you pay attention to grows; what you ignore withers. Choose your focus deliberately and let everything else fade to irrelevance.",
    triggerPatterns: ["obsessing_over_loss", "chasing_unattainable", "giving_enemy_attention", "public_frustration", "acknowledging_setback"],
  },
  {
    number: 37,
    title: "Create Compelling Spectacles",
    shortTitle: "Create Spectacles",
    essence: "Striking imagery and grand symbolic gestures create the aura of power — everyone responds to them. Stage spectacles for those around you, then, full of arresting visuals and radiant symbols that heighten your presence. Dazzled by appearances, no one will notice what you are really doing.",
    shopApplication: "At Nick's Tire & Auto, create visual experiences that customers remember and share. A before-and-after photo wall, a live stream of repairs in progress, a dramatic vehicle reveal after a major service — these moments generate social media content, Google reviews, and word-of-mouth. The shop that creates shareable moments markets itself for free. Transform routine tire changes into experiences worth talking about.",
    nourApplication: "When demoing NOUR OS, create wow moments — a live dashboard showing real-time shop data, a voice command that triggers a workflow, a split-screen showing manual vs. automated processes. In presentations and pitches, visuals beat slides full of text. Create moments that make audiences say 'whoa.' The spectacle is the message. People remember how you made them feel, not what you said.",
    triggerPatterns: ["boring_presentation", "no_visual_impact", "missed_spectacle", "bland_marketing", "forgettable_experience"],
  },
  {
    number: 38,
    title: "Think as You Like but Behave Like Others",
    shortTitle: "Blend Outwardly",
    essence: "If you make a show of going against the times, flaunting your unconventional ideas and unorthodox ways, people will think that you only want attention and that you look down upon them. They will find a way to punish you for making them feel inferior. It is far safer to blend in and nurture the common touch.",
    shopApplication: "At Nick's Tire & Auto, even if your internal systems are cutting-edge AI and automation, present the customer-facing experience in familiar, comfortable terms. Customers want to feel like they're at a trustworthy local shop, not a tech experiment. Keep the handshake, the walk-around inspection, the phone call follow-up — the human touches that make people comfortable. Revolutionize the back end; keep the front end familiar.",
    nourApplication: "In Cleveland's business community, don't lead with how different or disruptive you are — that alienates established players. Blend in at networking events, respect local business customs, and save the revolutionary talk for contexts where it's valued. Think like a Silicon Valley founder but behave like a Cleveland businessman. The ideas can be radical; the presentation should be relatable. You can transform an industry without making everyone in it feel obsolete — and the ones who feel obsolete become your enemies.",
    triggerPatterns: ["being_contrarian", "alienating_audience", "flaunting_difference", "making_others_inferior", "unconventional_display"],
  },
  {
    number: 39,
    title: "Stir Up Waters to Catch Fish",
    shortTitle: "Stir Waters",
    essence: "Anger and emotion are strategically counterproductive. You must always stay calm and objective. But if you can make your enemies angry while staying calm yourself, you gain a decided advantage. Put your enemies off-balance: find the chink in their vanity through which you can rattle them and you hold the strings.",
    shopApplication: "At Nick's Tire & Auto, if a competitor is engaging in aggressive tactics, stay composed publicly while strategically provoking their overreaction. A calm, professional response to a competitor's negative campaign makes them look unhinged while you look steady. If a difficult vendor is stalling, apply subtle pressure that forces them to react emotionally and reveal their true position.",
    nourApplication: "In negotiations and competitive situations, maintain emotional control while finding ways to disrupt your opponent's composure. The founder who stays cool under pressure while competitors panic commands respect and trust. When someone attacks NOUR OS publicly, a measured, factual response that subtly highlights their insecurity is more devastating than any angry clap-back. Emotional control is the ultimate competitive advantage.",
    triggerPatterns: ["emotional_reaction", "losing_composure", "opponent_calm", "anger_management", "reactive_behavior"],
  },
  {
    number: 40,
    title: "Despise the Free Lunch",
    shortTitle: "Nothing Is Free",
    essence: "What is offered for free is dangerous — it usually involves either a trick or a hidden obligation. What has worth is worth paying for. By paying your own way you stay clear of gratitude, guilt, and deceit. It is also often wise to pay the full price — there is no cutting corners with excellence.",
    shopApplication: "At Nick's Tire & Auto, don't chase free vendor promotions that lock you into bad long-term contracts. Don't accept 'free' diagnostic software that mines your customer data. Don't hire the friend-of-a-friend who'll 'work cheap' — you get what you pay for in techs, parts, and tools. Invest in quality equipment, quality training, and quality people. The 'savings' from cutting corners always cost more in callbacks, lost customers, and reputation damage.",
    nourApplication: "Pay for quality tools, services, and talent when building NOUR OS. Free hosting, free design work, free advice — they all come with hidden costs, whether it's unreliability, obligation, or inferior quality. When someone offers you something for free, ask what they're really buying. Invest in premium infrastructure, professional services, and your own skills. The free lunch mentality is a poverty mindset that caps your growth. Excellence requires investment, and that investment always pays returns.",
    triggerPatterns: ["seeking_free_stuff", "cutting_corners", "cheap_solution", "hidden_obligation", "false_economy"],
  },
  {
    number: 41,
    title: "Avoid Stepping into a Great Man's Shoes",
    shortTitle: "Forge Own Path",
    essence: "What happens first always appears better and more original than what comes after. If you succeed a great man or have a famous parent, you will have to accomplish double their achievements to outshine them. Do not get lost in their shadow or stuck in a past not of your own making.",
    shopApplication: "At Nick's Tire & Auto, if the shop was built on a previous owner's reputation, don't try to be them — be distinctly you. Rebrand, modernize, and put your stamp on the operation. Customers who loved the old way will resist, but new customers will be attracted to your fresh approach. The worst position is being a pale imitation of what came before. Forge a new identity that honors the legacy but clearly belongs to you.",
    nourApplication: "Don't model NOUR OS as 'the next Shopmonkey' or 'the next Tekmetric.' Build something so distinct that comparisons feel inadequate. In your personal journey, don't try to follow someone else's playbook exactly — your path as a young Cleveland shop owner building AI is unique. Own that uniqueness. The founders who succeed aren't the ones who copied a template; they're the ones who created a new category.",
    triggerPatterns: ["copying_predecessor", "shadow_of_greatness", "imitation_mode", "comparison_trap", "following_template"],
  },
  {
    number: 42,
    title: "Strike the Shepherd and the Sheep Will Scatter",
    shortTitle: "Strike the Shepherd",
    essence: "Trouble can often be traced to a single strong individual — the stirrer, the arrogant underling, the poisoner of goodwill. If you allow such people room to operate, others will succumb to their influence. Do not wait for the troubles they cause to multiply, do not try to negotiate — neutralize their influence by isolating or banishing them.",
    shopApplication: "At Nick's Tire & Auto, if one toxic tech is creating cliques, undermining management, or spreading negativity, don't address the group — address the individual. Remove or reform the ringleader and the rest of the team will realign. Every shop has had the 'alpha tech' who turns the floor against new policies. Address him directly — the followers will follow whoever leads, and that should be ownership.",
    nourApplication: "In any organization, community, or competitive landscape, identify the single point of influence causing problems. Whether it's a vocal critic in an online community, a difficult stakeholder blocking progress, or a competitor's key evangelist — neutralize the source and the effects dissipate. Don't waste energy fighting symptoms when you can address the cause. Strategic precision beats broad-based conflict every time.",
    triggerPatterns: ["group_problem", "toxic_leader_identified", "influence_source", "ringleader_detected", "scattered_resistance"],
  },
  {
    number: 43,
    title: "Work on the Hearts and Minds of Others",
    shortTitle: "Win Hearts & Minds",
    essence: "Coercion creates a reaction that will eventually work against you. You must seduce others into wanting to move in your direction. A person you have seduced becomes your loyal pawn. And the way to seduce others is to operate on their individual psychologies and weaknesses.",
    shopApplication: "At Nick's Tire & Auto, don't force techs to follow new processes with threats — win them over by showing how the new process makes their job easier, pays them more, or reduces callbacks that ruin their weekends. Don't demand customer loyalty through contracts — earn it through experiences that make them feel valued. The shop manager who leads through inspiration retains techs; the one who leads through fear loses them to the shop across town.",
    nourApplication: "Win NOUR OS users by making them love the product, not by locking them into contracts they can't escape. Build emotional investment through exceptional onboarding, responsive support, and features that genuinely improve their daily lives. In personal relationships and professional networks, influence through genuine connection and demonstrated value rather than pressure or obligation. Hearts and minds, once won, are the most durable form of loyalty.",
    triggerPatterns: ["coercive_approach", "forcing_compliance", "ignoring_emotions", "transactional_leadership", "fear_based_management"],
  },
  {
    number: 44,
    title: "Disarm and Infuriate with the Mirror Effect",
    shortTitle: "Mirror Effect",
    essence: "The mirror reflects reality, but it is also the perfect tool for deception: when you mirror your enemies, doing exactly as they do, they cannot figure out your strategy. The Mirror Effect mocks and humiliates them, making them overreact. Hold up a mirror to their psyches and you seduce them with the illusion that you share their values.",
    shopApplication: "At Nick's Tire & Auto, when a competitor copies your promotion, mirror it back with a better version — same concept, better execution. When a difficult customer is aggressive, mirror their intensity with calm professionalism — it disarms them because they expect a fight. When a vendor uses high-pressure tactics, reflect the same urgency back about your timeline, putting them on the defensive.",
    nourApplication: "When competitors copy NOUR OS features, take it as validation and mirror their best ideas right back with superior implementation. In negotiations, mirror the other party's communication style and energy to build instant rapport. In conflicts, reflect someone's behavior back to them calmly and watch them see themselves clearly for the first time. The mirror is both a bonding tool and a weapon, depending on how you angle it.",
    triggerPatterns: ["competitor_copying", "aggressive_opponent", "rapport_building_needed", "psychological_tactic", "reflection_opportunity"],
  },
  {
    number: 45,
    title: "Preach the Need for Change, but Never Reform Too Much at Once",
    shortTitle: "Gradual Change",
    essence: "Everyone understands the need for change in the abstract, but on the day-to-day level people are creatures of habit. Too much innovation is traumatic and will lead to revolt. If you are new to a position of power, make a show of respecting the old way of doing things.",
    shopApplication: "At Nick's Tire & Auto, don't overhaul everything on day one — new POS system, new scheduling, new uniform policy, new vendor all at once overwhelms the team and breeds resentment. Introduce one change at a time, let it settle, prove its value, then introduce the next. The shop owner who changes too much too fast loses his best techs to the familiar comfort of a competitor's shop.",
    nourApplication: "When onboarding new NOUR OS users, don't force them to change every process simultaneously. Start with one workflow — maybe scheduling — let them see the value, then expand to inventory, then to customer management. In your own life and business, sequence your transformations. The 16-phase infrastructure upgrade succeeds because it's phased, not because it's all-at-once. Sustainable change is sequential, not simultaneous.",
    triggerPatterns: ["too_much_change", "overwhelming_reform", "team_resistance", "change_fatigue", "revolutionary_overhaul"],
  },
  {
    number: 46,
    title: "Never Appear Too Perfect",
    shortTitle: "Show Flaws",
    essence: "Appearing better than others is always dangerous, but most dangerous of all is to appear to have no faults or weaknesses. Envy creates silent enemies. It is smart to occasionally display defects, and admit to harmless vices, in order to deflect envy and appear more human and approachable.",
    shopApplication: "At Nick's Tire & Auto, don't present the shop as flawless — customers see through it and competitors resent it. Share honest stories: 'We had a tough week but here's how we made it right for the customer.' Admit small mistakes publicly and show how you fixed them — it builds more trust than a fake five-star facade. A shop that seems too perfect seems untrustworthy. Humanity sells better than perfection.",
    nourApplication: "Don't present NOUR OS or yourself as having all the answers. Share your learning process, admit when a feature didn't work as planned, show vulnerability in your founder journey. The tech founder who appears infallible is either lying or about to fall hard. Strategic vulnerability — sharing real challenges and genuine growth — creates deeper connections with users, partners, and your community. Perfection creates distance; authenticity creates loyalty.",
    triggerPatterns: ["perfection_facade", "invulnerability_display", "no_admitted_flaws", "envy_generating", "unapproachable_image"],
  },
  {
    number: 47,
    title: "Do Not Go Past the Mark You Aimed For; In Victory, Learn When to Stop",
    shortTitle: "Know When to Stop",
    essence: "The moment of victory is often the moment of greatest peril. In the heat of victory, arrogance and overconfidence can push you past the goal you had aimed for, and by going too far, you make more enemies than you defeat. Set a goal, and when you reach it, stop.",
    shopApplication: "At Nick's Tire & Auto, when you've won a negotiation with a vendor — got the pricing you wanted — don't push for more just because you can. When you've successfully upsold a customer on necessary services, don't pile on unnecessary add-ons that breed buyer's remorse. When you've resolved a complaint and the customer is happy, stop talking. Over-winning creates resentment that poisons future interactions.",
    nourApplication: "When NOUR OS wins a major customer or milestone, celebrate and reset — don't immediately overextend by committing to features or markets you're not ready for. Victory creates a dangerous high that clouds judgment. After a successful launch, resist the urge to immediately announce five more products. Consolidate the win, strengthen the position, and plan the next move from a place of calm strategy, not euphoric overreach.",
    triggerPatterns: ["overreaching", "victory_arrogance", "pushing_too_far", "over_winning", "post_victory_recklessness"],
  },
  {
    number: 48,
    title: "Assume Formlessness",
    shortTitle: "Be Formless",
    essence: "By taking a shape, by having a visible plan, you open yourself to attack. Instead of taking a form for your enemy to grasp, keep yourself adaptable and on the move. Accept the fact that nothing is certain and no law is fixed. The best way to protect yourself is to be as fluid and formless as water.",
    shopApplication: "At Nick's Tire & Auto, don't lock into a rigid business model that can't adapt to market shifts. If EVs reduce traditional repair demand, pivot to EV maintenance. If a supply chain disruption hits, have backup vendors ready. If a new competitor enters the market, be ready to adjust pricing, services, and positioning overnight. The shop that's rigidly attached to 'how we've always done it' is the shop that closes. Fluidity is survival.",
    nourApplication: "Build NOUR OS with modular, adaptable architecture — not rigid structures that break when requirements change. Be willing to pivot the business model, the target market, or the feature set based on real feedback and market conditions. In your personal strategy, don't be so attached to a five-year plan that you miss a better opportunity at year two. Formlessness doesn't mean lacking direction — it means being able to flow around obstacles rather than crashing into them. Water finds every crack. Be water in business, in code, and in life.",
    triggerPatterns: ["rigid_structure", "inflexible_plan", "refusing_to_adapt", "fixed_mindset", "brittle_strategy"],
  },
];

export async function seed48Laws(prisma: PrismaClient) {
  console.log("Seeding 48 Laws of Power...");
  let count = 0;
  for (const law of laws) {
    await prisma.strategicLaw.upsert({
      where: { book_number: { book: "FORTY_EIGHT_LAWS", number: law.number } },
      update: {
        title: law.title,
        shortTitle: law.shortTitle,
        essence: law.essence,
        shopApplication: law.shopApplication,
        nourApplication: law.nourApplication,
        triggerPatterns: law.triggerPatterns,
      },
      create: {
        book: "FORTY_EIGHT_LAWS",
        number: law.number,
        title: law.title,
        shortTitle: law.shortTitle,
        essence: law.essence,
        shopApplication: law.shopApplication,
        nourApplication: law.nourApplication,
        triggerPatterns: law.triggerPatterns,
      },
    });
    count++;
  }
  console.log(`  ✓ ${count} laws of power seeded`);
}
